package com.transfer_funds.wvrtransferservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.transfer_funds.wvrtransferservice.WvrTransferService;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link WvrTransferService}.
 * @see WvrTransferService
 */
@RestController
@Api(value = "WvrTransferController", description = "controller class for java service execution")
@RequestMapping("/wvrTransfer")
public class WvrTransferController {

}

