package com.salesvision.testjavaservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.salesvision.testjavaservice.TestJavaService;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link TestJavaService}.
 * @see TestJavaService
 */
@RestController
@Api(value = "TestJavaController", description = "controller class for java service execution")
@RequestMapping("/testJava")
public class TestJavaController {

    @Autowired
    private TestJavaService testJavaService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/sampleJavaOperation", method = RequestMethod.GET)
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name,  HttpServletRequest request) {
        return testJavaService.sampleJavaOperation(name, request);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/test", method = RequestMethod.GET)
    public String test(@RequestParam(value = "name", required = false) String name,  HttpServletRequest request) {
        return testJavaService.test(name, request);
    }
}

