/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.salesvision.hrdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class SpringSessionAttributesId implements Serializable {

    private String attributeName;
    private String sessionPrimaryId;

    public String getAttributeName() {
        return this.attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    public String getSessionPrimaryId() {
        return this.sessionPrimaryId;
    }

    public void setSessionPrimaryId(String sessionPrimaryId) {
        this.sessionPrimaryId = sessionPrimaryId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SpringSessionAttributes)) return false;
        final SpringSessionAttributes springSessionAttributes = (SpringSessionAttributes) o;
        return Objects.equals(getAttributeName(), springSessionAttributes.getAttributeName()) &&
                Objects.equals(getSessionPrimaryId(), springSessionAttributes.getSessionPrimaryId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAttributeName(),
                getSessionPrimaryId());
    }
}