/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.salesvision.hrdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SpringSession generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SPRING_SESSION`", uniqueConstraints = {
            @UniqueConstraint(name = "`SPRING_SESSION_IX1`", columnNames = {"`SESSION_ID`"})})
public class SpringSession implements Serializable {

    private String primaryId;
    private String sessionId;
    private long creationTime;
    private long lastAccessTime;
    private int maxInactiveInterval;
    private long expiryTime;
    private String principalName;

    @Id
    @Column(name = "`PRIMARY_ID`", nullable = false, length = 36)
    public String getPrimaryId() {
        return this.primaryId;
    }

    public void setPrimaryId(String primaryId) {
        this.primaryId = primaryId;
    }

    @Column(name = "`SESSION_ID`", nullable = false, length = 36)
    public String getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    @Column(name = "`CREATION_TIME`", nullable = false, scale = 0, precision = 19)
    public long getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(long creationTime) {
        this.creationTime = creationTime;
    }

    @Column(name = "`LAST_ACCESS_TIME`", nullable = false, scale = 0, precision = 19)
    public long getLastAccessTime() {
        return this.lastAccessTime;
    }

    public void setLastAccessTime(long lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    @Column(name = "`MAX_INACTIVE_INTERVAL`", nullable = false, scale = 0, precision = 10)
    public int getMaxInactiveInterval() {
        return this.maxInactiveInterval;
    }

    public void setMaxInactiveInterval(int maxInactiveInterval) {
        this.maxInactiveInterval = maxInactiveInterval;
    }

    @Column(name = "`EXPIRY_TIME`", nullable = false, scale = 0, precision = 19)
    public long getExpiryTime() {
        return this.expiryTime;
    }

    public void setExpiryTime(long expiryTime) {
        this.expiryTime = expiryTime;
    }

    @Column(name = "`PRINCIPAL_NAME`", nullable = true, length = 100)
    public String getPrincipalName() {
        return this.principalName;
    }

    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SpringSession)) return false;
        final SpringSession springSession = (SpringSession) o;
        return Objects.equals(getPrimaryId(), springSession.getPrimaryId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPrimaryId());
    }
}