/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.BNKTransfer.model.FxcardtransparencyinfoFeeDetails;
import java.util.ArrayList;
import java.util.List;
/**
 * FxCardtransparencyinfoBody
 */

public class FxCardtransparencyinfoBody {
  @JsonProperty("scheme_name")
  private String scheme_name = null;

  @JsonProperty("transaction_date")
  private Object transaction_date = null;

  @JsonProperty("transaction_amount")
  private Object transaction_amount = null;

  @JsonProperty("fee_details")
  private List<FxcardtransparencyinfoFeeDetails> fee_details = null;

  @JsonProperty("billing_currency")
  private String billing_currency = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("transaction_currency")
  private Object transaction_currency = null;

  public FxCardtransparencyinfoBody scheme_name(String scheme_name) {
    this.scheme_name = scheme_name;
    return this;
  }

   /**
   * Name of the card scheme \&quot;MasterCard\&quot;, \&quot;Visa\&quot;.
   * @return scheme_name
  **/
  public String getSchemeName() {
    return scheme_name;
  }

  public void setSchemeName(String scheme_name) {
    this.scheme_name = scheme_name;
  }

  public FxCardtransparencyinfoBody transaction_date(Object transaction_date) {
    this.transaction_date = transaction_date;
    return this;
  }

   /**
   * Get transaction_date
   * @return transaction_date
  **/
  public Object getTransactionDate() {
    return transaction_date;
  }

  public void setTransactionDate(Object transaction_date) {
    this.transaction_date = transaction_date;
  }

  public FxCardtransparencyinfoBody transaction_amount(Object transaction_amount) {
    this.transaction_amount = transaction_amount;
    return this;
  }

   /**
   * Get transaction_amount
   * @return transaction_amount
  **/
  public Object getTransactionAmount() {
    return transaction_amount;
  }

  public void setTransactionAmount(Object transaction_amount) {
    this.transaction_amount = transaction_amount;
  }

  public FxCardtransparencyinfoBody fee_details(List<FxcardtransparencyinfoFeeDetails> fee_details) {
    this.fee_details = fee_details;
    return this;
  }

  public FxCardtransparencyinfoBody addFeeDetailsItem(FxcardtransparencyinfoFeeDetails fee_detailsItem) {
    if (this.fee_details == null) {
      this.fee_details = new ArrayList<>();
    }
    this.fee_details.add(fee_detailsItem);
    return this;
  }

   /**
   * Get fee_details
   * @return fee_details
  **/
  public List<FxcardtransparencyinfoFeeDetails> getFeeDetails() {
    return fee_details;
  }

  public void setFeeDetails(List<FxcardtransparencyinfoFeeDetails> fee_details) {
    this.fee_details = fee_details;
  }

  public FxCardtransparencyinfoBody billing_currency(String billing_currency) {
    this.billing_currency = billing_currency;
    return this;
  }

   /**
   * Currency. ISO 3 characters code.
   * @return billing_currency
  **/
  public String getBillingCurrency() {
    return billing_currency;
  }

  public void setBillingCurrency(String billing_currency) {
    this.billing_currency = billing_currency;
  }

  public FxCardtransparencyinfoBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public FxCardtransparencyinfoBody transaction_currency(Object transaction_currency) {
    this.transaction_currency = transaction_currency;
    return this;
  }

   /**
   * Get transaction_currency
   * @return transaction_currency
  **/
  public Object getTransactionCurrency() {
    return transaction_currency;
  }

  public void setTransactionCurrency(Object transaction_currency) {
    this.transaction_currency = transaction_currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FxCardtransparencyinfoBody fx_cardtransparencyinfo_body = (FxCardtransparencyinfoBody) o;
    return Objects.equals(this.scheme_name, fx_cardtransparencyinfo_body.scheme_name) &&
        Objects.equals(this.transaction_date, fx_cardtransparencyinfo_body.transaction_date) &&
        Objects.equals(this.transaction_amount, fx_cardtransparencyinfo_body.transaction_amount) &&
        Objects.equals(this.fee_details, fx_cardtransparencyinfo_body.fee_details) &&
        Objects.equals(this.billing_currency, fx_cardtransparencyinfo_body.billing_currency) &&
        Objects.equals(this.entity_id, fx_cardtransparencyinfo_body.entity_id) &&
        Objects.equals(this.transaction_currency, fx_cardtransparencyinfo_body.transaction_currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheme_name, transaction_date, transaction_amount, fee_details, billing_currency, entity_id, transaction_currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FxCardtransparencyinfoBody {\n");
    
    sb.append("    scheme_name: ").append(toIndentedString(scheme_name)).append("\n");
    sb.append("    transaction_date: ").append(toIndentedString(transaction_date)).append("\n");
    sb.append("    transaction_amount: ").append(toIndentedString(transaction_amount)).append("\n");
    sb.append("    fee_details: ").append(toIndentedString(fee_details)).append("\n");
    sb.append("    billing_currency: ").append(toIndentedString(billing_currency)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    transaction_currency: ").append(toIndentedString(transaction_currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
