/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * GeoprofileCreateBody
 */

public class GeoprofileCreateBody {
  @JsonProperty("geo_profile_name")
  private String geo_profile_name = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("region_code")
  private Object region_code = null;

  public GeoprofileCreateBody geo_profile_name(String geo_profile_name) {
    this.geo_profile_name = geo_profile_name;
    return this;
  }

   /**
   * Name of the geo profile
   * @return geo_profile_name
  **/
  public String getGeoProfileName() {
    return geo_profile_name;
  }

  public void setGeoProfileName(String geo_profile_name) {
    this.geo_profile_name = geo_profile_name;
  }

  public GeoprofileCreateBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public GeoprofileCreateBody region_code(Object region_code) {
    this.region_code = region_code;
    return this;
  }

   /**
   * Get region_code
   * @return region_code
  **/
  public Object getRegionCode() {
    return region_code;
  }

  public void setRegionCode(Object region_code) {
    this.region_code = region_code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoprofileCreateBody geoprofile_create_body = (GeoprofileCreateBody) o;
    return Objects.equals(this.geo_profile_name, geoprofile_create_body.geo_profile_name) &&
        Objects.equals(this.entity_id, geoprofile_create_body.entity_id) &&
        Objects.equals(this.region_code, geoprofile_create_body.region_code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geo_profile_name, entity_id, region_code);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoprofileCreateBody {\n");
    
    sb.append("    geo_profile_name: ").append(toIndentedString(geo_profile_name)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    region_code: ").append(toIndentedString(region_code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
