/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * IbanprofileupgradeProfileUpgrades
 */

public class IbanprofileupgradeProfileUpgrades {
  @JsonProperty("new_profile_code")
  private Object new_profile_code = null;

  @JsonProperty("iban")
  private String iban = null;

  @JsonProperty("bic")
  private String bic = null;

  public IbanprofileupgradeProfileUpgrades new_profile_code(Object new_profile_code) {
    this.new_profile_code = new_profile_code;
    return this;
  }

   /**
   * Get new_profile_code
   * @return new_profile_code
  **/
  public Object getNewProfileCode() {
    return new_profile_code;
  }

  public void setNewProfileCode(Object new_profile_code) {
    this.new_profile_code = new_profile_code;
  }

  public IbanprofileupgradeProfileUpgrades iban(String iban) {
    this.iban = iban;
    return this;
  }

   /**
   * The International Bank Account Number.
   * @return iban
  **/
  public String getIban() {
    return iban;
  }

  public void setIban(String iban) {
    this.iban = iban;
  }

  public IbanprofileupgradeProfileUpgrades bic(String bic) {
    this.bic = bic;
    return this;
  }

   /**
   * The BIC code of the Bank where the account is held.
   * @return bic
  **/
  public String getBic() {
    return bic;
  }

  public void setBic(String bic) {
    this.bic = bic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IbanprofileupgradeProfileUpgrades ibanprofileupgrade_profile_upgrades = (IbanprofileupgradeProfileUpgrades) o;
    return Objects.equals(this.new_profile_code, ibanprofileupgrade_profile_upgrades.new_profile_code) &&
        Objects.equals(this.iban, ibanprofileupgrade_profile_upgrades.iban) &&
        Objects.equals(this.bic, ibanprofileupgrade_profile_upgrades.bic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(new_profile_code, iban, bic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IbanprofileupgradeProfileUpgrades {\n");
    
    sb.append("    new_profile_code: ").append(toIndentedString(new_profile_code)).append("\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
