/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.BNKTransfer.model.InlineResponse20072PayerPhysicalAccountInfo;
/**
 * InlineResponse20072SuspendedPayments
 */

public class InlineResponse20072SuspendedPayments {
  @JsonProperty("reference")
  private String reference = null;

  @JsonProperty("reason")
  private Object reason = null;

  @JsonProperty("amount")
  private Object amount = null;

  @JsonProperty("date_time")
  private Object date_time = null;

  @JsonProperty("corporate_client_code")
  private Object corporate_client_code = null;

  @JsonProperty("virtual_account_ref")
  private Object virtual_account_ref = null;

  @JsonProperty("operation_id")
  private String operation_id = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("payer_physical_account_info")
  private InlineResponse20072PayerPhysicalAccountInfo payer_physical_account_info = null;

  public InlineResponse20072SuspendedPayments reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Reference of the inbound suspended payment
   * @return reference
  **/
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public InlineResponse20072SuspendedPayments reason(Object reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  public Object getReason() {
    return reason;
  }

  public void setReason(Object reason) {
    this.reason = reason;
  }

  public InlineResponse20072SuspendedPayments amount(Object amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  public Object getAmount() {
    return amount;
  }

  public void setAmount(Object amount) {
    this.amount = amount;
  }

  public InlineResponse20072SuspendedPayments date_time(Object date_time) {
    this.date_time = date_time;
    return this;
  }

   /**
   * Get date_time
   * @return date_time
  **/
  public Object getDateTime() {
    return date_time;
  }

  public void setDateTime(Object date_time) {
    this.date_time = date_time;
  }

  public InlineResponse20072SuspendedPayments corporate_client_code(Object corporate_client_code) {
    this.corporate_client_code = corporate_client_code;
    return this;
  }

   /**
   * Get corporate_client_code
   * @return corporate_client_code
  **/
  public Object getCorporateClientCode() {
    return corporate_client_code;
  }

  public void setCorporateClientCode(Object corporate_client_code) {
    this.corporate_client_code = corporate_client_code;
  }

  public InlineResponse20072SuspendedPayments virtual_account_ref(Object virtual_account_ref) {
    this.virtual_account_ref = virtual_account_ref;
    return this;
  }

   /**
   * Get virtual_account_ref
   * @return virtual_account_ref
  **/
  public Object getVirtualAccountRef() {
    return virtual_account_ref;
  }

  public void setVirtualAccountRef(Object virtual_account_ref) {
    this.virtual_account_ref = virtual_account_ref;
  }

  public InlineResponse20072SuspendedPayments operation_id(String operation_id) {
    this.operation_id = operation_id;
    return this;
  }

   /**
   * Bankable reference of the operation.
   * @return operation_id
  **/
  public String getOperationId() {
    return operation_id;
  }

  public void setOperationId(String operation_id) {
    this.operation_id = operation_id;
  }

  public InlineResponse20072SuspendedPayments currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency. ISO 3 characters code.
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public InlineResponse20072SuspendedPayments payer_physical_account_info(InlineResponse20072PayerPhysicalAccountInfo payer_physical_account_info) {
    this.payer_physical_account_info = payer_physical_account_info;
    return this;
  }

   /**
   * Get payer_physical_account_info
   * @return payer_physical_account_info
  **/
  public InlineResponse20072PayerPhysicalAccountInfo getPayerPhysicalAccountInfo() {
    return payer_physical_account_info;
  }

  public void setPayerPhysicalAccountInfo(InlineResponse20072PayerPhysicalAccountInfo payer_physical_account_info) {
    this.payer_physical_account_info = payer_physical_account_info;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20072SuspendedPayments inline_response_200_72_suspended_payments = (InlineResponse20072SuspendedPayments) o;
    return Objects.equals(this.reference, inline_response_200_72_suspended_payments.reference) &&
        Objects.equals(this.reason, inline_response_200_72_suspended_payments.reason) &&
        Objects.equals(this.amount, inline_response_200_72_suspended_payments.amount) &&
        Objects.equals(this.date_time, inline_response_200_72_suspended_payments.date_time) &&
        Objects.equals(this.corporate_client_code, inline_response_200_72_suspended_payments.corporate_client_code) &&
        Objects.equals(this.virtual_account_ref, inline_response_200_72_suspended_payments.virtual_account_ref) &&
        Objects.equals(this.operation_id, inline_response_200_72_suspended_payments.operation_id) &&
        Objects.equals(this.currency, inline_response_200_72_suspended_payments.currency) &&
        Objects.equals(this.payer_physical_account_info, inline_response_200_72_suspended_payments.payer_physical_account_info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reference, reason, amount, date_time, corporate_client_code, virtual_account_ref, operation_id, currency, payer_physical_account_info);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20072SuspendedPayments {\n");
    
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    date_time: ").append(toIndentedString(date_time)).append("\n");
    sb.append("    corporate_client_code: ").append(toIndentedString(corporate_client_code)).append("\n");
    sb.append("    virtual_account_ref: ").append(toIndentedString(virtual_account_ref)).append("\n");
    sb.append("    operation_id: ").append(toIndentedString(operation_id)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    payer_physical_account_info: ").append(toIndentedString(payer_physical_account_info)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
