/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse20034
 */

public class InlineResponse20034 {
  /**
   * Status of the card.
   */
  public enum CardStatusEnum {
    ACT("ACT"),
    BLO("BLO"),
    LOS("LOS"),
    NEW("NEW"),
    STO("STO"),
    DAM("DAM"),
    EXP("EXP"),
    CAN("CAN"),
    REA("REA"),
    PRE("PRE"),
    CBL("CBL"),
    CMD("CMD"),
    ABO("ABO");

    private String value;

    CardStatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CardStatusEnum fromValue(String input) {
      for (CardStatusEnum b : CardStatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("card_status")
  private CardStatusEnum card_status = null;

  @JsonProperty("request")
  private String request = null;

  @JsonProperty("transac_id")
  private String transac_id = null;

  @JsonProperty("card_client_code")
  private String card_client_code = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("card_exp_date")
  private String card_exp_date = null;

  public InlineResponse20034 card_status(CardStatusEnum card_status) {
    this.card_status = card_status;
    return this;
  }

   /**
   * Status of the card.
   * @return card_status
  **/
  public CardStatusEnum getCardStatus() {
    return card_status;
  }

  public void setCardStatus(CardStatusEnum card_status) {
    this.card_status = card_status;
  }

  public InlineResponse20034 request(String request) {
    this.request = request;
    return this;
  }

   /**
   * The command that was requested
   * @return request
  **/
  public String getRequest() {
    return request;
  }

  public void setRequest(String request) {
    this.request = request;
  }

  public InlineResponse20034 transac_id(String transac_id) {
    this.transac_id = transac_id;
    return this;
  }

   /**
   * Unique id of the request
   * @return transac_id
  **/
  public String getTransacId() {
    return transac_id;
  }

  public void setTransacId(String transac_id) {
    this.transac_id = transac_id;
  }

  public InlineResponse20034 card_client_code(String card_client_code) {
    this.card_client_code = card_client_code;
    return this;
  }

   /**
   * Reference id of the card
   * @return card_client_code
  **/
  public String getCardClientCode() {
    return card_client_code;
  }

  public void setCardClientCode(String card_client_code) {
    this.card_client_code = card_client_code;
  }

  public InlineResponse20034 entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public InlineResponse20034 card_exp_date(String card_exp_date) {
    this.card_exp_date = card_exp_date;
    return this;
  }

   /**
   * The expiry date of the card (format yyyy-mm-dd).
   * @return card_exp_date
  **/
  public String getCardExpDate() {
    return card_exp_date;
  }

  public void setCardExpDate(String card_exp_date) {
    this.card_exp_date = card_exp_date;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20034 inline_response_200_34 = (InlineResponse20034) o;
    return Objects.equals(this.card_status, inline_response_200_34.card_status) &&
        Objects.equals(this.request, inline_response_200_34.request) &&
        Objects.equals(this.transac_id, inline_response_200_34.transac_id) &&
        Objects.equals(this.card_client_code, inline_response_200_34.card_client_code) &&
        Objects.equals(this.entity_id, inline_response_200_34.entity_id) &&
        Objects.equals(this.card_exp_date, inline_response_200_34.card_exp_date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(card_status, request, transac_id, card_client_code, entity_id, card_exp_date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20034 {\n");
    
    sb.append("    card_status: ").append(toIndentedString(card_status)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    transac_id: ").append(toIndentedString(transac_id)).append("\n");
    sb.append("    card_client_code: ").append(toIndentedString(card_client_code)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    card_exp_date: ").append(toIndentedString(card_exp_date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
