/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.BNKTransfer.model.FxcardtransparencyinfoFeeDetails;
import com.transfer_funds.BNKTransfer.model.InlineResponse20040Balances;
import com.transfer_funds.BNKTransfer.model.InlineResponse20040Transactions;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20040
 */

public class InlineResponse20040 {
  @JsonProperty("request")
  private String request = null;

  @JsonProperty("transac_id")
  private String transac_id = null;

  @JsonProperty("balances")
  private InlineResponse20040Balances balances = null;

  @JsonProperty("nb_txns_ret")
  private Integer nb_txns_ret = null;

  @JsonProperty("fee_details")
  private List<FxcardtransparencyinfoFeeDetails> fee_details = null;

  @JsonProperty("card_client_code")
  private String card_client_code = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("transactions")
  private List<InlineResponse20040Transactions> transactions = null;

  public InlineResponse20040 request(String request) {
    this.request = request;
    return this;
  }

   /**
   * The command that was requested
   * @return request
  **/
  public String getRequest() {
    return request;
  }

  public void setRequest(String request) {
    this.request = request;
  }

  public InlineResponse20040 transac_id(String transac_id) {
    this.transac_id = transac_id;
    return this;
  }

   /**
   * Unique id of the request
   * @return transac_id
  **/
  public String getTransacId() {
    return transac_id;
  }

  public void setTransacId(String transac_id) {
    this.transac_id = transac_id;
  }

  public InlineResponse20040 balances(InlineResponse20040Balances balances) {
    this.balances = balances;
    return this;
  }

   /**
   * Get balances
   * @return balances
  **/
  public InlineResponse20040Balances getBalances() {
    return balances;
  }

  public void setBalances(InlineResponse20040Balances balances) {
    this.balances = balances;
  }

  public InlineResponse20040 nb_txns_ret(Integer nb_txns_ret) {
    this.nb_txns_ret = nb_txns_ret;
    return this;
  }

   /**
   * Number of transactions returned.
   * @return nb_txns_ret
  **/
  public Integer getNbTxnsRet() {
    return nb_txns_ret;
  }

  public void setNbTxnsRet(Integer nb_txns_ret) {
    this.nb_txns_ret = nb_txns_ret;
  }

  public InlineResponse20040 fee_details(List<FxcardtransparencyinfoFeeDetails> fee_details) {
    this.fee_details = fee_details;
    return this;
  }

  public InlineResponse20040 addFeeDetailsItem(FxcardtransparencyinfoFeeDetails fee_detailsItem) {
    if (this.fee_details == null) {
      this.fee_details = new ArrayList<>();
    }
    this.fee_details.add(fee_detailsItem);
    return this;
  }

   /**
   * Get fee_details
   * @return fee_details
  **/
  public List<FxcardtransparencyinfoFeeDetails> getFeeDetails() {
    return fee_details;
  }

  public void setFeeDetails(List<FxcardtransparencyinfoFeeDetails> fee_details) {
    this.fee_details = fee_details;
  }

  public InlineResponse20040 card_client_code(String card_client_code) {
    this.card_client_code = card_client_code;
    return this;
  }

   /**
   * Reference id of the card
   * @return card_client_code
  **/
  public String getCardClientCode() {
    return card_client_code;
  }

  public void setCardClientCode(String card_client_code) {
    this.card_client_code = card_client_code;
  }

  public InlineResponse20040 entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public InlineResponse20040 transactions(List<InlineResponse20040Transactions> transactions) {
    this.transactions = transactions;
    return this;
  }

  public InlineResponse20040 addTransactionsItem(InlineResponse20040Transactions transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Get transactions
   * @return transactions
  **/
  public List<InlineResponse20040Transactions> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<InlineResponse20040Transactions> transactions) {
    this.transactions = transactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20040 inline_response_200_40 = (InlineResponse20040) o;
    return Objects.equals(this.request, inline_response_200_40.request) &&
        Objects.equals(this.transac_id, inline_response_200_40.transac_id) &&
        Objects.equals(this.balances, inline_response_200_40.balances) &&
        Objects.equals(this.nb_txns_ret, inline_response_200_40.nb_txns_ret) &&
        Objects.equals(this.fee_details, inline_response_200_40.fee_details) &&
        Objects.equals(this.card_client_code, inline_response_200_40.card_client_code) &&
        Objects.equals(this.entity_id, inline_response_200_40.entity_id) &&
        Objects.equals(this.transactions, inline_response_200_40.transactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, transac_id, balances, nb_txns_ret, fee_details, card_client_code, entity_id, transactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20040 {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    transac_id: ").append(toIndentedString(transac_id)).append("\n");
    sb.append("    balances: ").append(toIndentedString(balances)).append("\n");
    sb.append("    nb_txns_ret: ").append(toIndentedString(nb_txns_ret)).append("\n");
    sb.append("    fee_details: ").append(toIndentedString(fee_details)).append("\n");
    sb.append("    card_client_code: ").append(toIndentedString(card_client_code)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
