/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * CardGeoprofileremoveBody
 */

public class CardGeoprofileremoveBody {
  @JsonProperty("geo_profile_code")
  private String geo_profile_code = null;

  @JsonProperty("card_client_code")
  private String card_client_code = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  public CardGeoprofileremoveBody geo_profile_code(String geo_profile_code) {
    this.geo_profile_code = geo_profile_code;
    return this;
  }

   /**
   * Unique Identifier of geo profile
   * @return geo_profile_code
  **/
  public String getGeoProfileCode() {
    return geo_profile_code;
  }

  public void setGeoProfileCode(String geo_profile_code) {
    this.geo_profile_code = geo_profile_code;
  }

  public CardGeoprofileremoveBody card_client_code(String card_client_code) {
    this.card_client_code = card_client_code;
    return this;
  }

   /**
   * Reference id of the card
   * @return card_client_code
  **/
  public String getCardClientCode() {
    return card_client_code;
  }

  public void setCardClientCode(String card_client_code) {
    this.card_client_code = card_client_code;
  }

  public CardGeoprofileremoveBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardGeoprofileremoveBody card_geoprofileremove_body = (CardGeoprofileremoveBody) o;
    return Objects.equals(this.geo_profile_code, card_geoprofileremove_body.geo_profile_code) &&
        Objects.equals(this.card_client_code, card_geoprofileremove_body.card_client_code) &&
        Objects.equals(this.entity_id, card_geoprofileremove_body.entity_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geo_profile_code, card_client_code, entity_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardGeoprofileremoveBody {\n");
    
    sb.append("    geo_profile_code: ").append(toIndentedString(geo_profile_code)).append("\n");
    sb.append("    card_client_code: ").append(toIndentedString(card_client_code)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
