/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ConsumerUpdateBody
 */

public class ConsumerUpdateBody {
  @JsonProperty("address")
  private Object address = null;

  /**
   * Gender of individual
   */
  public enum GenderEnum {
    M("M"),
    F("F"),
    S("S"),
    X("X");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static GenderEnum fromValue(String input) {
      for (GenderEnum b : GenderEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("gender")
  private GenderEnum gender = null;

  @JsonProperty("date_of_birth")
  private String date_of_birth = null;

  @JsonProperty("mobile_no")
  private String mobile_no = null;

  @JsonProperty("last_name")
  private String last_name = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("ch_client_code")
  private String ch_client_code = null;

  @JsonProperty("tel_no")
  private String tel_no = null;

  @JsonProperty("tel_ext")
  private String tel_ext = null;

  @JsonProperty("first_name")
  private String first_name = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("mobile_ext")
  private String mobile_ext = null;

  public ConsumerUpdateBody address(Object address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public Object getAddress() {
    return address;
  }

  public void setAddress(Object address) {
    this.address = address;
  }

  public ConsumerUpdateBody gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Gender of individual
   * @return gender
  **/
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public ConsumerUpdateBody date_of_birth(String date_of_birth) {
    this.date_of_birth = date_of_birth;
    return this;
  }

   /**
   * Date of birth of the individual, formatted yyyy-mm-dd.
   * @return date_of_birth
  **/
  public String getDateOfBirth() {
    return date_of_birth;
  }

  public void setDateOfBirth(String date_of_birth) {
    this.date_of_birth = date_of_birth;
  }

  public ConsumerUpdateBody mobile_no(String mobile_no) {
    this.mobile_no = mobile_no;
    return this;
  }

   /**
   * Mandatory for 3D- Secure e-commerce payments. Mobile number of the individual.
   * @return mobile_no
  **/
  public String getMobileNo() {
    return mobile_no;
  }

  public void setMobileNo(String mobile_no) {
    this.mobile_no = mobile_no;
  }

  public ConsumerUpdateBody last_name(String last_name) {
    this.last_name = last_name;
    return this;
  }

   /**
   * Contact Last Name or Department
   * @return last_name
  **/
  public String getLastName() {
    return last_name;
  }

  public void setLastName(String last_name) {
    this.last_name = last_name;
  }

  public ConsumerUpdateBody language(String language) {
    this.language = language;
    return this;
  }

   /**
   * The communication language requested by the consumer following ISO 639-1 language code. E.g. en - English.
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public ConsumerUpdateBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public ConsumerUpdateBody ch_client_code(String ch_client_code) {
    this.ch_client_code = ch_client_code;
    return this;
  }

   /**
   * Unique identifier of a consumer. If this field is provided, the virtual account will be trated as a consumer account, belonging to a consumer of the corporation with provided corporate_id.
   * @return ch_client_code
  **/
  public String getChClientCode() {
    return ch_client_code;
  }

  public void setChClientCode(String ch_client_code) {
    this.ch_client_code = ch_client_code;
  }

  public ConsumerUpdateBody tel_no(String tel_no) {
    this.tel_no = tel_no;
    return this;
  }

   /**
   * The primary household landline telephone number of the consumer.
   * @return tel_no
  **/
  public String getTelNo() {
    return tel_no;
  }

  public void setTelNo(String tel_no) {
    this.tel_no = tel_no;
  }

  public ConsumerUpdateBody tel_ext(String tel_ext) {
    this.tel_ext = tel_ext;
    return this;
  }

   /**
   * Country Code extension for landline telephone number.
   * @return tel_ext
  **/
  public String getTelExt() {
    return tel_ext;
  }

  public void setTelExt(String tel_ext) {
    this.tel_ext = tel_ext;
  }

  public ConsumerUpdateBody first_name(String first_name) {
    this.first_name = first_name;
    return this;
  }

   /**
   * Contact First Name or Department
   * @return first_name
  **/
  public String getFirstName() {
    return first_name;
  }

  public void setFirstName(String first_name) {
    this.first_name = first_name;
  }

  public ConsumerUpdateBody email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the individual.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ConsumerUpdateBody mobile_ext(String mobile_ext) {
    this.mobile_ext = mobile_ext;
    return this;
  }

   /**
   * Country Code extension for mobile telephone number.
   * @return mobile_ext
  **/
  public String getMobileExt() {
    return mobile_ext;
  }

  public void setMobileExt(String mobile_ext) {
    this.mobile_ext = mobile_ext;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsumerUpdateBody consumer_update_body = (ConsumerUpdateBody) o;
    return Objects.equals(this.address, consumer_update_body.address) &&
        Objects.equals(this.gender, consumer_update_body.gender) &&
        Objects.equals(this.date_of_birth, consumer_update_body.date_of_birth) &&
        Objects.equals(this.mobile_no, consumer_update_body.mobile_no) &&
        Objects.equals(this.last_name, consumer_update_body.last_name) &&
        Objects.equals(this.language, consumer_update_body.language) &&
        Objects.equals(this.entity_id, consumer_update_body.entity_id) &&
        Objects.equals(this.ch_client_code, consumer_update_body.ch_client_code) &&
        Objects.equals(this.tel_no, consumer_update_body.tel_no) &&
        Objects.equals(this.tel_ext, consumer_update_body.tel_ext) &&
        Objects.equals(this.first_name, consumer_update_body.first_name) &&
        Objects.equals(this.email, consumer_update_body.email) &&
        Objects.equals(this.mobile_ext, consumer_update_body.mobile_ext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, gender, date_of_birth, mobile_no, last_name, language, entity_id, ch_client_code, tel_no, tel_ext, first_name, email, mobile_ext);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsumerUpdateBody {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    date_of_birth: ").append(toIndentedString(date_of_birth)).append("\n");
    sb.append("    mobile_no: ").append(toIndentedString(mobile_no)).append("\n");
    sb.append("    last_name: ").append(toIndentedString(last_name)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    ch_client_code: ").append(toIndentedString(ch_client_code)).append("\n");
    sb.append("    tel_no: ").append(toIndentedString(tel_no)).append("\n");
    sb.append("    tel_ext: ").append(toIndentedString(tel_ext)).append("\n");
    sb.append("    first_name: ").append(toIndentedString(first_name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    mobile_ext: ").append(toIndentedString(mobile_ext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
