/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse20040OriginalTransaction
 */

public class InlineResponse20040OriginalTransaction {
  @JsonProperty("amount")
  private Object amount = null;

  @JsonProperty("amount_billed")
  private Object amount_billed = null;

  /**
   * -1 for debit and +1 for credit.
   */
  public enum DebitOrCreditEnum {
    _1("-1"),
    _1_1("1");

    private String value;

    DebitOrCreditEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DebitOrCreditEnum fromValue(String input) {
      for (DebitOrCreditEnum b : DebitOrCreditEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("debit_or_credit")
  private DebitOrCreditEnum debit_or_credit = null;

  @JsonProperty("fx_rate")
  private String fx_rate = null;

  public InlineResponse20040OriginalTransaction amount(Object amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  public Object getAmount() {
    return amount;
  }

  public void setAmount(Object amount) {
    this.amount = amount;
  }

  public InlineResponse20040OriginalTransaction amount_billed(Object amount_billed) {
    this.amount_billed = amount_billed;
    return this;
  }

   /**
   * Get amount_billed
   * @return amount_billed
  **/
  public Object getAmountBilled() {
    return amount_billed;
  }

  public void setAmountBilled(Object amount_billed) {
    this.amount_billed = amount_billed;
  }

  public InlineResponse20040OriginalTransaction debit_or_credit(DebitOrCreditEnum debit_or_credit) {
    this.debit_or_credit = debit_or_credit;
    return this;
  }

   /**
   * -1 for debit and +1 for credit.
   * @return debit_or_credit
  **/
  public DebitOrCreditEnum getDebitOrCredit() {
    return debit_or_credit;
  }

  public void setDebitOrCredit(DebitOrCreditEnum debit_or_credit) {
    this.debit_or_credit = debit_or_credit;
  }

  public InlineResponse20040OriginalTransaction fx_rate(String fx_rate) {
    this.fx_rate = fx_rate;
    return this;
  }

   /**
   * The FX rate expressed as amount/amount_billed
   * @return fx_rate
  **/
  public String getFxRate() {
    return fx_rate;
  }

  public void setFxRate(String fx_rate) {
    this.fx_rate = fx_rate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20040OriginalTransaction inline_response_200_40_original_transaction = (InlineResponse20040OriginalTransaction) o;
    return Objects.equals(this.amount, inline_response_200_40_original_transaction.amount) &&
        Objects.equals(this.amount_billed, inline_response_200_40_original_transaction.amount_billed) &&
        Objects.equals(this.debit_or_credit, inline_response_200_40_original_transaction.debit_or_credit) &&
        Objects.equals(this.fx_rate, inline_response_200_40_original_transaction.fx_rate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, amount_billed, debit_or_credit, fx_rate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20040OriginalTransaction {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    amount_billed: ").append(toIndentedString(amount_billed)).append("\n");
    sb.append("    debit_or_credit: ").append(toIndentedString(debit_or_credit)).append("\n");
    sb.append("    fx_rate: ").append(toIndentedString(fx_rate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
