/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse20061
 */

public class InlineResponse20061 {
  @JsonProperty("request")
  private String request = null;

  @JsonProperty("transac_id")
  private String transac_id = null;

  @JsonProperty("enable_outbound_payments")
  private String enable_outbound_payments = null;

  @JsonProperty("corporate_client_code")
  private String corporate_client_code = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  public InlineResponse20061 request(String request) {
    this.request = request;
    return this;
  }

   /**
   * The command that was requested
   * @return request
  **/
  public String getRequest() {
    return request;
  }

  public void setRequest(String request) {
    this.request = request;
  }

  public InlineResponse20061 transac_id(String transac_id) {
    this.transac_id = transac_id;
    return this;
  }

   /**
   * Unique id of the request
   * @return transac_id
  **/
  public String getTransacId() {
    return transac_id;
  }

  public void setTransacId(String transac_id) {
    this.transac_id = transac_id;
  }

  public InlineResponse20061 enable_outbound_payments(String enable_outbound_payments) {
    this.enable_outbound_payments = enable_outbound_payments;
    return this;
  }

   /**
   * true â Make and receive false â Receive only
   * @return enable_outbound_payments
  **/
  public String getEnableOutboundPayments() {
    return enable_outbound_payments;
  }

  public void setEnableOutboundPayments(String enable_outbound_payments) {
    this.enable_outbound_payments = enable_outbound_payments;
  }

  public InlineResponse20061 corporate_client_code(String corporate_client_code) {
    this.corporate_client_code = corporate_client_code;
    return this;
  }

   /**
   * The corporate client code (unique identifier) of the corporate.
   * @return corporate_client_code
  **/
  public String getCorporateClientCode() {
    return corporate_client_code;
  }

  public void setCorporateClientCode(String corporate_client_code) {
    this.corporate_client_code = corporate_client_code;
  }

  public InlineResponse20061 entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20061 inline_response_200_61 = (InlineResponse20061) o;
    return Objects.equals(this.request, inline_response_200_61.request) &&
        Objects.equals(this.transac_id, inline_response_200_61.transac_id) &&
        Objects.equals(this.enable_outbound_payments, inline_response_200_61.enable_outbound_payments) &&
        Objects.equals(this.corporate_client_code, inline_response_200_61.corporate_client_code) &&
        Objects.equals(this.entity_id, inline_response_200_61.entity_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, transac_id, enable_outbound_payments, corporate_client_code, entity_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20061 {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    transac_id: ").append(toIndentedString(transac_id)).append("\n");
    sb.append("    enable_outbound_payments: ").append(toIndentedString(enable_outbound_payments)).append("\n");
    sb.append("    corporate_client_code: ").append(toIndentedString(corporate_client_code)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
