/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse2003PendingStatementTransactionMerchant
 */

public class InlineResponse2003PendingStatementTransactionMerchant {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("categoryCode")
  private String categoryCode = null;

  public InlineResponse2003PendingStatementTransactionMerchant code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Merchant Code
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public InlineResponse2003PendingStatementTransactionMerchant name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Merchant Name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse2003PendingStatementTransactionMerchant categoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
    return this;
  }

   /**
   * Merchant Category Code
   * @return categoryCode
  **/
  public String getCategoryCode() {
    return categoryCode;
  }

  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003PendingStatementTransactionMerchant inline_response_200_3_pendingStatementTransaction_merchant = (InlineResponse2003PendingStatementTransactionMerchant) o;
    return Objects.equals(this.code, inline_response_200_3_pendingStatementTransaction_merchant.code) &&
        Objects.equals(this.name, inline_response_200_3_pendingStatementTransaction_merchant.name) &&
        Objects.equals(this.categoryCode, inline_response_200_3_pendingStatementTransaction_merchant.categoryCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, categoryCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003PendingStatementTransactionMerchant {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    categoryCode: ").append(toIndentedString(categoryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
