/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ProfileUpdateBody
 */

public class ProfileUpdateBody {
  @JsonProperty("profile_name")
  private String profile_name = null;

  @JsonProperty("limit_rules")
  private Object limit_rules = null;

  @JsonProperty("profile_code")
  private String profile_code = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  public ProfileUpdateBody profile_name(String profile_name) {
    this.profile_name = profile_name;
    return this;
  }

   /**
   * Profile name for the platform limits and fees.
   * @return profile_name
  **/
  public String getProfileName() {
    return profile_name;
  }

  public void setProfileName(String profile_name) {
    this.profile_name = profile_name;
  }

  public ProfileUpdateBody limit_rules(Object limit_rules) {
    this.limit_rules = limit_rules;
    return this;
  }

   /**
   * Get limit_rules
   * @return limit_rules
  **/
  public Object getLimitRules() {
    return limit_rules;
  }

  public void setLimitRules(Object limit_rules) {
    this.limit_rules = limit_rules;
  }

  public ProfileUpdateBody profile_code(String profile_code) {
    this.profile_code = profile_code;
    return this;
  }

   /**
   * Profile of limits, velocities, and fees of the virtual account. Not available on all packages.
   * @return profile_code
  **/
  public String getProfileCode() {
    return profile_code;
  }

  public void setProfileCode(String profile_code) {
    this.profile_code = profile_code;
  }

  public ProfileUpdateBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileUpdateBody profile_update_body = (ProfileUpdateBody) o;
    return Objects.equals(this.profile_name, profile_update_body.profile_name) &&
        Objects.equals(this.limit_rules, profile_update_body.limit_rules) &&
        Objects.equals(this.profile_code, profile_update_body.profile_code) &&
        Objects.equals(this.entity_id, profile_update_body.entity_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profile_name, limit_rules, profile_code, entity_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileUpdateBody {\n");
    
    sb.append("    profile_name: ").append(toIndentedString(profile_name)).append("\n");
    sb.append("    limit_rules: ").append(toIndentedString(limit_rules)).append("\n");
    sb.append("    profile_code: ").append(toIndentedString(profile_code)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
