/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * SuspendedpaymentReleaseBody
 */

public class SuspendedpaymentReleaseBody {
  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("operation_id")
  private Object operation_id = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  public SuspendedpaymentReleaseBody description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public SuspendedpaymentReleaseBody operation_id(Object operation_id) {
    this.operation_id = operation_id;
    return this;
  }

   /**
   * Get operation_id
   * @return operation_id
  **/
  public Object getOperationId() {
    return operation_id;
  }

  public void setOperationId(Object operation_id) {
    this.operation_id = operation_id;
  }

  public SuspendedpaymentReleaseBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuspendedpaymentReleaseBody suspendedpayment_release_body = (SuspendedpaymentReleaseBody) o;
    return Objects.equals(this.description, suspendedpayment_release_body.description) &&
        Objects.equals(this.operation_id, suspendedpayment_release_body.operation_id) &&
        Objects.equals(this.entity_id, suspendedpayment_release_body.entity_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, operation_id, entity_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuspendedpaymentReleaseBody {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    operation_id: ").append(toIndentedString(operation_id)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
