/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * VirtualaccountStatementBody
 */

public class VirtualaccountStatementBody {
  @JsonProperty("end_date")
  private Object end_date = null;

  @JsonProperty("offset")
  private Integer offset = null;

  @JsonProperty("virtual_account_ref")
  private String virtual_account_ref = null;

  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("start_date")
  private Object start_date = null;

  public VirtualaccountStatementBody end_date(Object end_date) {
    this.end_date = end_date;
    return this;
  }

   /**
   * Get end_date
   * @return end_date
  **/
  public Object getEndDate() {
    return end_date;
  }

  public void setEndDate(Object end_date) {
    this.end_date = end_date;
  }

  public VirtualaccountStatementBody offset(Integer offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Start of the selection entry. Statement will be ordered based on the operation date. If count provided, offset must be provided.
   * @return offset
  **/
  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public VirtualaccountStatementBody virtual_account_ref(String virtual_account_ref) {
    this.virtual_account_ref = virtual_account_ref;
    return this;
  }

   /**
   * Reference ID of the virtual account
   * @return virtual_account_ref
  **/
  public String getVirtualAccountRef() {
    return virtual_account_ref;
  }

  public void setVirtualAccountRef(String virtual_account_ref) {
    this.virtual_account_ref = virtual_account_ref;
  }

  public VirtualaccountStatementBody count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of the selection entry. Statement will be ordered based on the operation date. If not set, the complete list will be retrieved. If offset is set, count will be effective.
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public VirtualaccountStatementBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public VirtualaccountStatementBody start_date(Object start_date) {
    this.start_date = start_date;
    return this;
  }

   /**
   * Get start_date
   * @return start_date
  **/
  public Object getStartDate() {
    return start_date;
  }

  public void setStartDate(Object start_date) {
    this.start_date = start_date;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualaccountStatementBody virtualaccount_statement_body = (VirtualaccountStatementBody) o;
    return Objects.equals(this.end_date, virtualaccount_statement_body.end_date) &&
        Objects.equals(this.offset, virtualaccount_statement_body.offset) &&
        Objects.equals(this.virtual_account_ref, virtualaccount_statement_body.virtual_account_ref) &&
        Objects.equals(this.count, virtualaccount_statement_body.count) &&
        Objects.equals(this.entity_id, virtualaccount_statement_body.entity_id) &&
        Objects.equals(this.start_date, virtualaccount_statement_body.start_date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(end_date, offset, virtual_account_ref, count, entity_id, start_date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualaccountStatementBody {\n");
    
    sb.append("    end_date: ").append(toIndentedString(end_date)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    virtual_account_ref: ").append(toIndentedString(virtual_account_ref)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    start_date: ").append(toIndentedString(start_date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
