/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * CardholderInfoBody
 */

public class CardholderInfoBody {
  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("ch_client_code")
  private String ch_client_code = null;

  public CardholderInfoBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public CardholderInfoBody ch_client_code(String ch_client_code) {
    this.ch_client_code = ch_client_code;
    return this;
  }

   /**
   * Unique identifier of a consumer. If this field is provided, the virtual account will be trated as a consumer account, belonging to a consumer of the corporation with provided corporate_id.
   * @return ch_client_code
  **/
  public String getChClientCode() {
    return ch_client_code;
  }

  public void setChClientCode(String ch_client_code) {
    this.ch_client_code = ch_client_code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardholderInfoBody cardholder_info_body = (CardholderInfoBody) o;
    return Objects.equals(this.entity_id, cardholder_info_body.entity_id) &&
        Objects.equals(this.ch_client_code, cardholder_info_body.ch_client_code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entity_id, ch_client_code);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardholderInfoBody {\n");
    
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    ch_client_code: ").append(toIndentedString(ch_client_code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
