/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.BNKTransfer.model.CardholderupdateCardholderMobileAdd;
/**
 * CardholderupdateCardholder
 */

public class CardholderupdateCardholder {
  @JsonProperty("delivery_address")
  private Object delivery_address = null;

  @JsonProperty("address")
  private Object address = null;

  /**
   * Gender of individual
   */
  public enum GenderEnum {
    M("M"),
    F("F"),
    S("S"),
    X("X");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static GenderEnum fromValue(String input) {
      for (GenderEnum b : GenderEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("gender")
  private GenderEnum gender = null;

  @JsonProperty("date_of_birth")
  private String date_of_birth = null;

  @JsonProperty("mobile_no")
  private String mobile_no = null;

  @JsonProperty("last_name")
  private String last_name = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("tel_no")
  private String tel_no = null;

  @JsonProperty("tel_ext")
  private String tel_ext = null;

  @JsonProperty("miduserid")
  private String miduserid = null;

  @JsonProperty("first_name")
  private String first_name = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("mobile_ext")
  private String mobile_ext = null;

  @JsonProperty("mobile_add")
  private CardholderupdateCardholderMobileAdd mobile_add = null;

  public CardholderupdateCardholder delivery_address(Object delivery_address) {
    this.delivery_address = delivery_address;
    return this;
  }

   /**
   * Get delivery_address
   * @return delivery_address
  **/
  public Object getDeliveryAddress() {
    return delivery_address;
  }

  public void setDeliveryAddress(Object delivery_address) {
    this.delivery_address = delivery_address;
  }

  public CardholderupdateCardholder address(Object address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public Object getAddress() {
    return address;
  }

  public void setAddress(Object address) {
    this.address = address;
  }

  public CardholderupdateCardholder gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Gender of individual
   * @return gender
  **/
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public CardholderupdateCardholder date_of_birth(String date_of_birth) {
    this.date_of_birth = date_of_birth;
    return this;
  }

   /**
   * Date of birth of the individual, formatted yyyy-mm-dd.
   * @return date_of_birth
  **/
  public String getDateOfBirth() {
    return date_of_birth;
  }

  public void setDateOfBirth(String date_of_birth) {
    this.date_of_birth = date_of_birth;
  }

  public CardholderupdateCardholder mobile_no(String mobile_no) {
    this.mobile_no = mobile_no;
    return this;
  }

   /**
   * Mandatory for 3D- Secure e-commerce payments. Mobile number of the individual.
   * @return mobile_no
  **/
  public String getMobileNo() {
    return mobile_no;
  }

  public void setMobileNo(String mobile_no) {
    this.mobile_no = mobile_no;
  }

  public CardholderupdateCardholder last_name(String last_name) {
    this.last_name = last_name;
    return this;
  }

   /**
   * Contact Last Name or Department
   * @return last_name
  **/
  public String getLastName() {
    return last_name;
  }

  public void setLastName(String last_name) {
    this.last_name = last_name;
  }

  public CardholderupdateCardholder language(String language) {
    this.language = language;
    return this;
  }

   /**
   * The communication language requested by the consumer following ISO 639-1 language code. E.g. en - English.
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public CardholderupdateCardholder tel_no(String tel_no) {
    this.tel_no = tel_no;
    return this;
  }

   /**
   * The primary household landline telephone number of the consumer.
   * @return tel_no
  **/
  public String getTelNo() {
    return tel_no;
  }

  public void setTelNo(String tel_no) {
    this.tel_no = tel_no;
  }

  public CardholderupdateCardholder tel_ext(String tel_ext) {
    this.tel_ext = tel_ext;
    return this;
  }

   /**
   * Country Code extension for landline telephone number.
   * @return tel_ext
  **/
  public String getTelExt() {
    return tel_ext;
  }

  public void setTelExt(String tel_ext) {
    this.tel_ext = tel_ext;
  }

  public CardholderupdateCardholder miduserid(String miduserid) {
    this.miduserid = miduserid;
    return this;
  }

   /**
   * Modirum User ID for 3D Secure SDK users
   * @return miduserid
  **/
  public String getMiduserid() {
    return miduserid;
  }

  public void setMiduserid(String miduserid) {
    this.miduserid = miduserid;
  }

  public CardholderupdateCardholder first_name(String first_name) {
    this.first_name = first_name;
    return this;
  }

   /**
   * Contact First Name or Department
   * @return first_name
  **/
  public String getFirstName() {
    return first_name;
  }

  public void setFirstName(String first_name) {
    this.first_name = first_name;
  }

  public CardholderupdateCardholder email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the individual.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CardholderupdateCardholder mobile_ext(String mobile_ext) {
    this.mobile_ext = mobile_ext;
    return this;
  }

   /**
   * Country Code extension for mobile telephone number.
   * @return mobile_ext
  **/
  public String getMobileExt() {
    return mobile_ext;
  }

  public void setMobileExt(String mobile_ext) {
    this.mobile_ext = mobile_ext;
  }

  public CardholderupdateCardholder mobile_add(CardholderupdateCardholderMobileAdd mobile_add) {
    this.mobile_add = mobile_add;
    return this;
  }

   /**
   * Get mobile_add
   * @return mobile_add
  **/
  public CardholderupdateCardholderMobileAdd getMobileAdd() {
    return mobile_add;
  }

  public void setMobileAdd(CardholderupdateCardholderMobileAdd mobile_add) {
    this.mobile_add = mobile_add;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardholderupdateCardholder cardholderupdate_cardholder = (CardholderupdateCardholder) o;
    return Objects.equals(this.delivery_address, cardholderupdate_cardholder.delivery_address) &&
        Objects.equals(this.address, cardholderupdate_cardholder.address) &&
        Objects.equals(this.gender, cardholderupdate_cardholder.gender) &&
        Objects.equals(this.date_of_birth, cardholderupdate_cardholder.date_of_birth) &&
        Objects.equals(this.mobile_no, cardholderupdate_cardholder.mobile_no) &&
        Objects.equals(this.last_name, cardholderupdate_cardholder.last_name) &&
        Objects.equals(this.language, cardholderupdate_cardholder.language) &&
        Objects.equals(this.tel_no, cardholderupdate_cardholder.tel_no) &&
        Objects.equals(this.tel_ext, cardholderupdate_cardholder.tel_ext) &&
        Objects.equals(this.miduserid, cardholderupdate_cardholder.miduserid) &&
        Objects.equals(this.first_name, cardholderupdate_cardholder.first_name) &&
        Objects.equals(this.email, cardholderupdate_cardholder.email) &&
        Objects.equals(this.mobile_ext, cardholderupdate_cardholder.mobile_ext) &&
        Objects.equals(this.mobile_add, cardholderupdate_cardholder.mobile_add);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delivery_address, address, gender, date_of_birth, mobile_no, last_name, language, tel_no, tel_ext, miduserid, first_name, email, mobile_ext, mobile_add);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardholderupdateCardholder {\n");
    
    sb.append("    delivery_address: ").append(toIndentedString(delivery_address)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    date_of_birth: ").append(toIndentedString(date_of_birth)).append("\n");
    sb.append("    mobile_no: ").append(toIndentedString(mobile_no)).append("\n");
    sb.append("    last_name: ").append(toIndentedString(last_name)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    tel_no: ").append(toIndentedString(tel_no)).append("\n");
    sb.append("    tel_ext: ").append(toIndentedString(tel_ext)).append("\n");
    sb.append("    miduserid: ").append(toIndentedString(miduserid)).append("\n");
    sb.append("    first_name: ").append(toIndentedString(first_name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    mobile_ext: ").append(toIndentedString(mobile_ext)).append("\n");
    sb.append("    mobile_add: ").append(toIndentedString(mobile_add)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
