/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.BNKTransfer.model.InlineResponse20042Device;
/**
 * InlineResponse20042DigitalWalletTokens
 */

public class InlineResponse20042DigitalWalletTokens {
  @JsonProperty("token_requestor_name")
  private String token_requestor_name = null;

  @JsonProperty("state_reason")
  private String state_reason = null;

  @JsonProperty("fulfillment_status")
  private String fulfillment_status = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("digital_wallet_token")
  private String digital_wallet_token = null;

  @JsonProperty("device")
  private InlineResponse20042Device device = null;

  public InlineResponse20042DigitalWalletTokens token_requestor_name(String token_requestor_name) {
    this.token_requestor_name = token_requestor_name;
    return this;
  }

   /**
   * Name of the token provider.
   * @return token_requestor_name
  **/
  public String getTokenRequestorName() {
    return token_requestor_name;
  }

  public void setTokenRequestorName(String token_requestor_name) {
    this.token_requestor_name = token_requestor_name;
  }

  public InlineResponse20042DigitalWalletTokens state_reason(String state_reason) {
    this.state_reason = state_reason;
    return this;
  }

   /**
   * Reason for state of the token
   * @return state_reason
  **/
  public String getStateReason() {
    return state_reason;
  }

  public void setStateReason(String state_reason) {
    this.state_reason = state_reason;
  }

  public InlineResponse20042DigitalWalletTokens fulfillment_status(String fulfillment_status) {
    this.fulfillment_status = fulfillment_status;
    return this;
  }

   /**
   * The digital wallet token provisioning status: Allowable Values: DECISION_RED, DECISION_YELLOW, DECISION_GREEN, REJECTED, PROVISIONED
   * @return fulfillment_status
  **/
  public String getFulfillmentStatus() {
    return fulfillment_status;
  }

  public void setFulfillmentStatus(String fulfillment_status) {
    this.fulfillment_status = fulfillment_status;
  }

  public InlineResponse20042DigitalWalletTokens state(String state) {
    this.state = state;
    return this;
  }

   /**
   * State of the token Allowable Values: REQUESTED, REQUEST_DECLINED, ACTIVE, SUSPENDED, TERMINATED
   * @return state
  **/
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public InlineResponse20042DigitalWalletTokens digital_wallet_token(String digital_wallet_token) {
    this.digital_wallet_token = digital_wallet_token;
    return this;
  }

   /**
   * Unique ID of the token
   * @return digital_wallet_token
  **/
  public String getDigitalWalletToken() {
    return digital_wallet_token;
  }

  public void setDigitalWalletToken(String digital_wallet_token) {
    this.digital_wallet_token = digital_wallet_token;
  }

  public InlineResponse20042DigitalWalletTokens device(InlineResponse20042Device device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  public InlineResponse20042Device getDevice() {
    return device;
  }

  public void setDevice(InlineResponse20042Device device) {
    this.device = device;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20042DigitalWalletTokens inline_response_200_42_digital_wallet_tokens = (InlineResponse20042DigitalWalletTokens) o;
    return Objects.equals(this.token_requestor_name, inline_response_200_42_digital_wallet_tokens.token_requestor_name) &&
        Objects.equals(this.state_reason, inline_response_200_42_digital_wallet_tokens.state_reason) &&
        Objects.equals(this.fulfillment_status, inline_response_200_42_digital_wallet_tokens.fulfillment_status) &&
        Objects.equals(this.state, inline_response_200_42_digital_wallet_tokens.state) &&
        Objects.equals(this.digital_wallet_token, inline_response_200_42_digital_wallet_tokens.digital_wallet_token) &&
        Objects.equals(this.device, inline_response_200_42_digital_wallet_tokens.device);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token_requestor_name, state_reason, fulfillment_status, state, digital_wallet_token, device);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20042DigitalWalletTokens {\n");
    
    sb.append("    token_requestor_name: ").append(toIndentedString(token_requestor_name)).append("\n");
    sb.append("    state_reason: ").append(toIndentedString(state_reason)).append("\n");
    sb.append("    fulfillment_status: ").append(toIndentedString(fulfillment_status)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    digital_wallet_token: ").append(toIndentedString(digital_wallet_token)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
