/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse20040Balances
 */

public class InlineResponse20040Balances {
  @JsonProperty("product_id")
  private String product_id = null;

  @JsonProperty("card_available_amount")
  private Object card_available_amount = null;

  @JsonProperty("card_pending_amount")
  private Object card_pending_amount = null;

  @JsonProperty("card_curr")
  private String card_curr = null;

  @JsonProperty("card_balance")
  private Object card_balance = null;

  public InlineResponse20040Balances product_id(String product_id) {
    this.product_id = product_id;
    return this;
  }

   /**
   * Bankable reference of the operation.
   * @return product_id
  **/
  public String getProductId() {
    return product_id;
  }

  public void setProductId(String product_id) {
    this.product_id = product_id;
  }

  public InlineResponse20040Balances card_available_amount(Object card_available_amount) {
    this.card_available_amount = card_available_amount;
    return this;
  }

   /**
   * Get card_available_amount
   * @return card_available_amount
  **/
  public Object getCardAvailableAmount() {
    return card_available_amount;
  }

  public void setCardAvailableAmount(Object card_available_amount) {
    this.card_available_amount = card_available_amount;
  }

  public InlineResponse20040Balances card_pending_amount(Object card_pending_amount) {
    this.card_pending_amount = card_pending_amount;
    return this;
  }

   /**
   * Get card_pending_amount
   * @return card_pending_amount
  **/
  public Object getCardPendingAmount() {
    return card_pending_amount;
  }

  public void setCardPendingAmount(Object card_pending_amount) {
    this.card_pending_amount = card_pending_amount;
  }

  public InlineResponse20040Balances card_curr(String card_curr) {
    this.card_curr = card_curr;
    return this;
  }

   /**
   * Currency. ISO 3 characters code.
   * @return card_curr
  **/
  public String getCardCurr() {
    return card_curr;
  }

  public void setCardCurr(String card_curr) {
    this.card_curr = card_curr;
  }

  public InlineResponse20040Balances card_balance(Object card_balance) {
    this.card_balance = card_balance;
    return this;
  }

   /**
   * Get card_balance
   * @return card_balance
  **/
  public Object getCardBalance() {
    return card_balance;
  }

  public void setCardBalance(Object card_balance) {
    this.card_balance = card_balance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20040Balances inline_response_200_40_balances = (InlineResponse20040Balances) o;
    return Objects.equals(this.product_id, inline_response_200_40_balances.product_id) &&
        Objects.equals(this.card_available_amount, inline_response_200_40_balances.card_available_amount) &&
        Objects.equals(this.card_pending_amount, inline_response_200_40_balances.card_pending_amount) &&
        Objects.equals(this.card_curr, inline_response_200_40_balances.card_curr) &&
        Objects.equals(this.card_balance, inline_response_200_40_balances.card_balance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(product_id, card_available_amount, card_pending_amount, card_curr, card_balance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20040Balances {\n");
    
    sb.append("    product_id: ").append(toIndentedString(product_id)).append("\n");
    sb.append("    card_available_amount: ").append(toIndentedString(card_available_amount)).append("\n");
    sb.append("    card_pending_amount: ").append(toIndentedString(card_pending_amount)).append("\n");
    sb.append("    card_curr: ").append(toIndentedString(card_curr)).append("\n");
    sb.append("    card_balance: ").append(toIndentedString(card_balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
