/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.BNKTransfer.model.FxcardtransparencyinfoFeeDetails;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2009
 */

public class InlineResponse2009 {
  @JsonProperty("request")
  private String request = null;

  @JsonProperty("transac_id")
  private String transac_id = null;

  @JsonProperty("card_line_4")
  private String card_line_4 = null;

  @JsonProperty("card_name")
  private String card_name = null;

  @JsonProperty("fee_details")
  private List<FxcardtransparencyinfoFeeDetails> fee_details = null;

  @JsonProperty("card_pan")
  private String card_pan = null;

  @JsonProperty("card_client_code")
  private String card_client_code = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("card_exp_date")
  private String card_exp_date = null;

  @JsonProperty("card_cvc2")
  private String card_cvc2 = null;

  public InlineResponse2009 request(String request) {
    this.request = request;
    return this;
  }

   /**
   * The command that was requested
   * @return request
  **/
  public String getRequest() {
    return request;
  }

  public void setRequest(String request) {
    this.request = request;
  }

  public InlineResponse2009 transac_id(String transac_id) {
    this.transac_id = transac_id;
    return this;
  }

   /**
   * Unique id of the request
   * @return transac_id
  **/
  public String getTransacId() {
    return transac_id;
  }

  public void setTransacId(String transac_id) {
    this.transac_id = transac_id;
  }

  public InlineResponse2009 card_line_4(String card_line_4) {
    this.card_line_4 = card_line_4;
    return this;
  }

   /**
   * Free text field. For line 4 variable data. A regular expression for control will put in place.
   * @return card_line_4
  **/
  public String getCardLine4() {
    return card_line_4;
  }

  public void setCardLine4(String card_line_4) {
    this.card_line_4 = card_line_4;
  }

  public InlineResponse2009 card_name(String card_name) {
    this.card_name = card_name;
    return this;
  }

   /**
   * The name to appear on the card. If omitted then the card name will be composed by: &lt;first_name&gt;&lt;&gt;&lt;last_name&gt; or if abbreviation is needed &lt;first letter of first_name&gt;&lt;&gt;&lt;last_name&gt;. The field length can vary depending on the card design and is also restricted to a maximum of 21 if the provider is Marqeta.
   * @return card_name
  **/
  public String getCardName() {
    return card_name;
  }

  public void setCardName(String card_name) {
    this.card_name = card_name;
  }

  public InlineResponse2009 fee_details(List<FxcardtransparencyinfoFeeDetails> fee_details) {
    this.fee_details = fee_details;
    return this;
  }

  public InlineResponse2009 addFeeDetailsItem(FxcardtransparencyinfoFeeDetails fee_detailsItem) {
    if (this.fee_details == null) {
      this.fee_details = new ArrayList<>();
    }
    this.fee_details.add(fee_detailsItem);
    return this;
  }

   /**
   * Get fee_details
   * @return fee_details
  **/
  public List<FxcardtransparencyinfoFeeDetails> getFeeDetails() {
    return fee_details;
  }

  public void setFeeDetails(List<FxcardtransparencyinfoFeeDetails> fee_details) {
    this.fee_details = fee_details;
  }

  public InlineResponse2009 card_pan(String card_pan) {
    this.card_pan = card_pan;
    return this;
  }

   /**
   * 16 or 19 digit card number. Only in the response if the card is virtual and the client is authorised to receive this secure data.
   * @return card_pan
  **/
  public String getCardPan() {
    return card_pan;
  }

  public void setCardPan(String card_pan) {
    this.card_pan = card_pan;
  }

  public InlineResponse2009 card_client_code(String card_client_code) {
    this.card_client_code = card_client_code;
    return this;
  }

   /**
   * Reference id of the card
   * @return card_client_code
  **/
  public String getCardClientCode() {
    return card_client_code;
  }

  public void setCardClientCode(String card_client_code) {
    this.card_client_code = card_client_code;
  }

  public InlineResponse2009 entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public InlineResponse2009 card_exp_date(String card_exp_date) {
    this.card_exp_date = card_exp_date;
    return this;
  }

   /**
   * The expiry date of the card (format yyyy-mm-dd).
   * @return card_exp_date
  **/
  public String getCardExpDate() {
    return card_exp_date;
  }

  public void setCardExpDate(String card_exp_date) {
    this.card_exp_date = card_exp_date;
  }

  public InlineResponse2009 card_cvc2(String card_cvc2) {
    this.card_cvc2 = card_cvc2;
    return this;
  }

   /**
   * The CVC2 number for the card. Only in the response if the card is virtual and the client is authorised to receive this secure data.
   * @return card_cvc2
  **/
  public String getCardCvc2() {
    return card_cvc2;
  }

  public void setCardCvc2(String card_cvc2) {
    this.card_cvc2 = card_cvc2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2009 inline_response_200_9 = (InlineResponse2009) o;
    return Objects.equals(this.request, inline_response_200_9.request) &&
        Objects.equals(this.transac_id, inline_response_200_9.transac_id) &&
        Objects.equals(this.card_line_4, inline_response_200_9.card_line_4) &&
        Objects.equals(this.card_name, inline_response_200_9.card_name) &&
        Objects.equals(this.fee_details, inline_response_200_9.fee_details) &&
        Objects.equals(this.card_pan, inline_response_200_9.card_pan) &&
        Objects.equals(this.card_client_code, inline_response_200_9.card_client_code) &&
        Objects.equals(this.entity_id, inline_response_200_9.entity_id) &&
        Objects.equals(this.card_exp_date, inline_response_200_9.card_exp_date) &&
        Objects.equals(this.card_cvc2, inline_response_200_9.card_cvc2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, transac_id, card_line_4, card_name, fee_details, card_pan, card_client_code, entity_id, card_exp_date, card_cvc2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2009 {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    transac_id: ").append(toIndentedString(transac_id)).append("\n");
    sb.append("    card_line_4: ").append(toIndentedString(card_line_4)).append("\n");
    sb.append("    card_name: ").append(toIndentedString(card_name)).append("\n");
    sb.append("    fee_details: ").append(toIndentedString(fee_details)).append("\n");
    sb.append("    card_pan: ").append(toIndentedString(card_pan)).append("\n");
    sb.append("    card_client_code: ").append(toIndentedString(card_client_code)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    card_exp_date: ").append(toIndentedString(card_exp_date)).append("\n");
    sb.append("    card_cvc2: ").append(toIndentedString(card_cvc2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
