/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse20050
 */

public class InlineResponse20050 {
  @JsonProperty("request")
  private String request = null;

  @JsonProperty("transac_id")
  private String transac_id = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("ch_client_code")
  private String ch_client_code = null;

  public InlineResponse20050 request(String request) {
    this.request = request;
    return this;
  }

   /**
   * The command that was requested
   * @return request
  **/
  public String getRequest() {
    return request;
  }

  public void setRequest(String request) {
    this.request = request;
  }

  public InlineResponse20050 transac_id(String transac_id) {
    this.transac_id = transac_id;
    return this;
  }

   /**
   * Unique id of the request
   * @return transac_id
  **/
  public String getTransacId() {
    return transac_id;
  }

  public void setTransacId(String transac_id) {
    this.transac_id = transac_id;
  }

  public InlineResponse20050 entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public InlineResponse20050 ch_client_code(String ch_client_code) {
    this.ch_client_code = ch_client_code;
    return this;
  }

   /**
   * Unique identifier of a consumer. If this field is provided, the virtual account will be trated as a consumer account, belonging to a consumer of the corporation with provided corporate_id.
   * @return ch_client_code
  **/
  public String getChClientCode() {
    return ch_client_code;
  }

  public void setChClientCode(String ch_client_code) {
    this.ch_client_code = ch_client_code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20050 inline_response_200_50 = (InlineResponse20050) o;
    return Objects.equals(this.request, inline_response_200_50.request) &&
        Objects.equals(this.transac_id, inline_response_200_50.transac_id) &&
        Objects.equals(this.entity_id, inline_response_200_50.entity_id) &&
        Objects.equals(this.ch_client_code, inline_response_200_50.ch_client_code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, transac_id, entity_id, ch_client_code);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20050 {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    transac_id: ").append(toIndentedString(transac_id)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    ch_client_code: ").append(toIndentedString(ch_client_code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
