/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse2003PendingStatementTransactionPendingFees
 */

public class InlineResponse2003PendingStatementTransactionPendingFees {
  @JsonProperty("fxFeeAmount")
  private String fxFeeAmount = null;

  @JsonProperty("atmFeeAmount")
  private String atmFeeAmount = null;

  @JsonProperty("otherFeeAmount")
  private String otherFeeAmount = null;

  public InlineResponse2003PendingStatementTransactionPendingFees fxFeeAmount(String fxFeeAmount) {
    this.fxFeeAmount = fxFeeAmount;
    return this;
  }

   /**
   * Amount of the FX fee.
   * @return fxFeeAmount
  **/
  public String getFxFeeAmount() {
    return fxFeeAmount;
  }

  public void setFxFeeAmount(String fxFeeAmount) {
    this.fxFeeAmount = fxFeeAmount;
  }

  public InlineResponse2003PendingStatementTransactionPendingFees atmFeeAmount(String atmFeeAmount) {
    this.atmFeeAmount = atmFeeAmount;
    return this;
  }

   /**
   * The ATM fee amount settled in the account currency. ISO format currency amount. Number of decimal places is defined by the currency type may be between 0 and 4.
   * @return atmFeeAmount
  **/
  public String getAtmFeeAmount() {
    return atmFeeAmount;
  }

  public void setAtmFeeAmount(String atmFeeAmount) {
    this.atmFeeAmount = atmFeeAmount;
  }

  public InlineResponse2003PendingStatementTransactionPendingFees otherFeeAmount(String otherFeeAmount) {
    this.otherFeeAmount = otherFeeAmount;
    return this;
  }

   /**
   * The sum of all other fees settled in the account currency. ISO format currency amount. Number of decimal places is defined by the currency type may be between 0 and 4.
   * @return otherFeeAmount
  **/
  public String getOtherFeeAmount() {
    return otherFeeAmount;
  }

  public void setOtherFeeAmount(String otherFeeAmount) {
    this.otherFeeAmount = otherFeeAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003PendingStatementTransactionPendingFees inline_response_200_3_pendingStatementTransaction_pending_fees = (InlineResponse2003PendingStatementTransactionPendingFees) o;
    return Objects.equals(this.fxFeeAmount, inline_response_200_3_pendingStatementTransaction_pending_fees.fxFeeAmount) &&
        Objects.equals(this.atmFeeAmount, inline_response_200_3_pendingStatementTransaction_pending_fees.atmFeeAmount) &&
        Objects.equals(this.otherFeeAmount, inline_response_200_3_pendingStatementTransaction_pending_fees.otherFeeAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fxFeeAmount, atmFeeAmount, otherFeeAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003PendingStatementTransactionPendingFees {\n");
    
    sb.append("    fxFeeAmount: ").append(toIndentedString(fxFeeAmount)).append("\n");
    sb.append("    atmFeeAmount: ").append(toIndentedString(atmFeeAmount)).append("\n");
    sb.append("    otherFeeAmount: ").append(toIndentedString(otherFeeAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
