/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse20015VirtualAccount
 */

public class InlineResponse20015VirtualAccount {
  @JsonProperty("virtual_account_name")
  private String virtual_account_name = null;

  @JsonProperty("virtual_account_ref")
  private String virtual_account_ref = null;

  public InlineResponse20015VirtualAccount virtual_account_name(String virtual_account_name) {
    this.virtual_account_name = virtual_account_name;
    return this;
  }

   /**
   * Account name
   * @return virtual_account_name
  **/
  public String getVirtualAccountName() {
    return virtual_account_name;
  }

  public void setVirtualAccountName(String virtual_account_name) {
    this.virtual_account_name = virtual_account_name;
  }

  public InlineResponse20015VirtualAccount virtual_account_ref(String virtual_account_ref) {
    this.virtual_account_ref = virtual_account_ref;
    return this;
  }

   /**
   * Reference ID of the virtual account
   * @return virtual_account_ref
  **/
  public String getVirtualAccountRef() {
    return virtual_account_ref;
  }

  public void setVirtualAccountRef(String virtual_account_ref) {
    this.virtual_account_ref = virtual_account_ref;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20015VirtualAccount inline_response_200_15_virtual_account = (InlineResponse20015VirtualAccount) o;
    return Objects.equals(this.virtual_account_name, inline_response_200_15_virtual_account.virtual_account_name) &&
        Objects.equals(this.virtual_account_ref, inline_response_200_15_virtual_account.virtual_account_ref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(virtual_account_name, virtual_account_ref);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20015VirtualAccount {\n");
    
    sb.append("    virtual_account_name: ").append(toIndentedString(virtual_account_name)).append("\n");
    sb.append("    virtual_account_ref: ").append(toIndentedString(virtual_account_ref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
