/*
 * Bankable API
 * Bankable API description
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.BNKTransfer.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RegionCreateBody
 */

public class RegionCreateBody {
  @JsonProperty("region_name")
  private String region_name = null;

  @JsonProperty("entity_id")
  private String entity_id = null;

  @JsonProperty("country_list")
  private String country_list = null;

  public RegionCreateBody region_name(String region_name) {
    this.region_name = region_name;
    return this;
  }

   /**
   * Name of the region.
   * @return region_name
  **/
  public String getRegionName() {
    return region_name;
  }

  public void setRegionName(String region_name) {
    this.region_name = region_name;
  }

  public RegionCreateBody entity_id(String entity_id) {
    this.entity_id = entity_id;
    return this;
  }

   /**
   * Identity of the client
   * @return entity_id
  **/
  public String getEntityId() {
    return entity_id;
  }

  public void setEntityId(String entity_id) {
    this.entity_id = entity_id;
  }

  public RegionCreateBody country_list(String country_list) {
    this.country_list = country_list;
    return this;
  }

   /**
   * Country list to be provided in ISO format separated by comma (,). Example FR,GB,NL.
   * @return country_list
  **/
  public String getCountryList() {
    return country_list;
  }

  public void setCountryList(String country_list) {
    this.country_list = country_list;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionCreateBody region_create_body = (RegionCreateBody) o;
    return Objects.equals(this.region_name, region_create_body.region_name) &&
        Objects.equals(this.entity_id, region_create_body.entity_id) &&
        Objects.equals(this.country_list, region_create_body.country_list);
  }

  @Override
  public int hashCode() {
    return Objects.hash(region_name, entity_id, country_list);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionCreateBody {\n");
    
    sb.append("    region_name: ").append(toIndentedString(region_name)).append("\n");
    sb.append("    entity_id: ").append(toIndentedString(entity_id)).append("\n");
    sb.append("    country_list: ").append(toIndentedString(country_list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
