/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
/**
 * CardsCardIdBody
 */

public class CardsCardIdBody {
  @JsonProperty("card_rules")
  private List<String> card_rules = new ArrayList<>();

  public CardsCardIdBody card_rules(List<String> card_rules) {
    this.card_rules = card_rules;
    return this;
  }

  public CardsCardIdBody addCardRulesItem(String card_rulesItem) {
    this.card_rules.add(card_rulesItem);
    return this;
  }

   /**
   * Get card_rules
   * @return card_rules
  **/
  public List<String> getCardRules() {
    return card_rules;
  }

  public void setCardRules(List<String> card_rules) {
    this.card_rules = card_rules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardsCardIdBody cards_card_id_body = (CardsCardIdBody) o;
    return Objects.equals(this.card_rules, cards_card_id_body.card_rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(card_rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardsCardIdBody {\n");
    
    sb.append("    card_rules: ").append(toIndentedString(card_rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
