/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.RBSwagger.model.V1customerbeneficiariesCompany1;
import com.transfer_funds.RBSwagger.model.V1customerbeneficiariesDefaultAccount1;
import com.transfer_funds.RBSwagger.model.V1customerbeneficiariesPerson1;
/**
 * CustomerBeneficiariesBody
 */

public class CustomerBeneficiariesBody {
  @JsonProperty("uk_account_number")
  private String uk_account_number = null;

  /**
   * Gets or Sets asset_class
   */
  public enum AssetClassEnum {
    COMMODITY("commodity"),
    CURRENCY("currency");

    private String value;

    AssetClassEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AssetClassEnum fromValue(String input) {
      for (AssetClassEnum b : AssetClassEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("asset_class")
  private AssetClassEnum asset_class = null;

  @JsonProperty("bank_country")
  private String bank_country = null;

  @JsonProperty("beneficiary_meta")
  private Object beneficiary_meta = null;

  @JsonProperty("default_account")
  private V1customerbeneficiariesDefaultAccount1 default_account = null;

  @JsonProperty("bic_swift")
  private String bic_swift = null;

  @JsonProperty("uk_sort_code")
  private String uk_sort_code = null;

  @JsonProperty("person")
  private V1customerbeneficiariesPerson1 person = null;

  @JsonProperty("holder_id")
  private String holder_id = null;

  @JsonProperty("iban")
  private String iban = null;

  /**
   * Gets or Sets asset_type
   */
  public enum AssetTypeEnum {
    PLN("pln"),
    AUD("aud"),
    CHF("chf"),
    CAD("cad"),
    SEK("sek"),
    GOLDBLOC("goldbloc"),
    USD("usd"),
    NOK("nok"),
    WHISKY("whisky"),
    VIRTUAL_CURRENCY("virtual-currency"),
    JPY("jpy"),
    HUF("huf"),
    NZD("nzd"),
    GOLD("gold"),
    CZK("czk"),
    SGD("sgd"),
    RON("ron"),
    GBP("gbp"),
    HRK("hrk"),
    EUR("eur");

    private String value;

    AssetTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AssetTypeEnum fromValue(String input) {
      for (AssetTypeEnum b : AssetTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("asset_type")
  private AssetTypeEnum asset_type = null;

  @JsonProperty("bank_name")
  private String bank_name = null;

  @JsonProperty("company")
  private V1customerbeneficiariesCompany1 company = null;

  public CustomerBeneficiariesBody uk_account_number(String uk_account_number) {
    this.uk_account_number = uk_account_number;
    return this;
  }

   /**
   * Get uk_account_number
   * @return uk_account_number
  **/
  public String getUkAccountNumber() {
    return uk_account_number;
  }

  public void setUkAccountNumber(String uk_account_number) {
    this.uk_account_number = uk_account_number;
  }

  public CustomerBeneficiariesBody asset_class(AssetClassEnum asset_class) {
    this.asset_class = asset_class;
    return this;
  }

   /**
   * Get asset_class
   * @return asset_class
  **/
  public AssetClassEnum getAssetClass() {
    return asset_class;
  }

  public void setAssetClass(AssetClassEnum asset_class) {
    this.asset_class = asset_class;
  }

  public CustomerBeneficiariesBody bank_country(String bank_country) {
    this.bank_country = bank_country;
    return this;
  }

   /**
   * Get bank_country
   * @return bank_country
  **/
  public String getBankCountry() {
    return bank_country;
  }

  public void setBankCountry(String bank_country) {
    this.bank_country = bank_country;
  }

  public CustomerBeneficiariesBody beneficiary_meta(Object beneficiary_meta) {
    this.beneficiary_meta = beneficiary_meta;
    return this;
  }

   /**
   * Get beneficiary_meta
   * @return beneficiary_meta
  **/
  public Object getBeneficiaryMeta() {
    return beneficiary_meta;
  }

  public void setBeneficiaryMeta(Object beneficiary_meta) {
    this.beneficiary_meta = beneficiary_meta;
  }

  public CustomerBeneficiariesBody default_account(V1customerbeneficiariesDefaultAccount1 default_account) {
    this.default_account = default_account;
    return this;
  }

   /**
   * Get default_account
   * @return default_account
  **/
  public V1customerbeneficiariesDefaultAccount1 getDefaultAccount() {
    return default_account;
  }

  public void setDefaultAccount(V1customerbeneficiariesDefaultAccount1 default_account) {
    this.default_account = default_account;
  }

  public CustomerBeneficiariesBody bic_swift(String bic_swift) {
    this.bic_swift = bic_swift;
    return this;
  }

   /**
   * Get bic_swift
   * @return bic_swift
  **/
  public String getBicSwift() {
    return bic_swift;
  }

  public void setBicSwift(String bic_swift) {
    this.bic_swift = bic_swift;
  }

  public CustomerBeneficiariesBody uk_sort_code(String uk_sort_code) {
    this.uk_sort_code = uk_sort_code;
    return this;
  }

   /**
   * Get uk_sort_code
   * @return uk_sort_code
  **/
  public String getUkSortCode() {
    return uk_sort_code;
  }

  public void setUkSortCode(String uk_sort_code) {
    this.uk_sort_code = uk_sort_code;
  }

  public CustomerBeneficiariesBody person(V1customerbeneficiariesPerson1 person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public V1customerbeneficiariesPerson1 getPerson() {
    return person;
  }

  public void setPerson(V1customerbeneficiariesPerson1 person) {
    this.person = person;
  }

  public CustomerBeneficiariesBody holder_id(String holder_id) {
    this.holder_id = holder_id;
    return this;
  }

   /**
   * Get holder_id
   * @return holder_id
  **/
  public String getHolderId() {
    return holder_id;
  }

  public void setHolderId(String holder_id) {
    this.holder_id = holder_id;
  }

  public CustomerBeneficiariesBody iban(String iban) {
    this.iban = iban;
    return this;
  }

   /**
   * Get iban
   * @return iban
  **/
  public String getIban() {
    return iban;
  }

  public void setIban(String iban) {
    this.iban = iban;
  }

  public CustomerBeneficiariesBody asset_type(AssetTypeEnum asset_type) {
    this.asset_type = asset_type;
    return this;
  }

   /**
   * Get asset_type
   * @return asset_type
  **/
  public AssetTypeEnum getAssetType() {
    return asset_type;
  }

  public void setAssetType(AssetTypeEnum asset_type) {
    this.asset_type = asset_type;
  }

  public CustomerBeneficiariesBody bank_name(String bank_name) {
    this.bank_name = bank_name;
    return this;
  }

   /**
   * Get bank_name
   * @return bank_name
  **/
  public String getBankName() {
    return bank_name;
  }

  public void setBankName(String bank_name) {
    this.bank_name = bank_name;
  }

  public CustomerBeneficiariesBody company(V1customerbeneficiariesCompany1 company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  public V1customerbeneficiariesCompany1 getCompany() {
    return company;
  }

  public void setCompany(V1customerbeneficiariesCompany1 company) {
    this.company = company;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerBeneficiariesBody customer_beneficiaries_body = (CustomerBeneficiariesBody) o;
    return Objects.equals(this.uk_account_number, customer_beneficiaries_body.uk_account_number) &&
        Objects.equals(this.asset_class, customer_beneficiaries_body.asset_class) &&
        Objects.equals(this.bank_country, customer_beneficiaries_body.bank_country) &&
        Objects.equals(this.beneficiary_meta, customer_beneficiaries_body.beneficiary_meta) &&
        Objects.equals(this.default_account, customer_beneficiaries_body.default_account) &&
        Objects.equals(this.bic_swift, customer_beneficiaries_body.bic_swift) &&
        Objects.equals(this.uk_sort_code, customer_beneficiaries_body.uk_sort_code) &&
        Objects.equals(this.person, customer_beneficiaries_body.person) &&
        Objects.equals(this.holder_id, customer_beneficiaries_body.holder_id) &&
        Objects.equals(this.iban, customer_beneficiaries_body.iban) &&
        Objects.equals(this.asset_type, customer_beneficiaries_body.asset_type) &&
        Objects.equals(this.bank_name, customer_beneficiaries_body.bank_name) &&
        Objects.equals(this.company, customer_beneficiaries_body.company);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uk_account_number, asset_class, bank_country, beneficiary_meta, default_account, bic_swift, uk_sort_code, person, holder_id, iban, asset_type, bank_name, company);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerBeneficiariesBody {\n");
    
    sb.append("    uk_account_number: ").append(toIndentedString(uk_account_number)).append("\n");
    sb.append("    asset_class: ").append(toIndentedString(asset_class)).append("\n");
    sb.append("    bank_country: ").append(toIndentedString(bank_country)).append("\n");
    sb.append("    beneficiary_meta: ").append(toIndentedString(beneficiary_meta)).append("\n");
    sb.append("    default_account: ").append(toIndentedString(default_account)).append("\n");
    sb.append("    bic_swift: ").append(toIndentedString(bic_swift)).append("\n");
    sb.append("    uk_sort_code: ").append(toIndentedString(uk_sort_code)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    holder_id: ").append(toIndentedString(holder_id)).append("\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    asset_type: ").append(toIndentedString(asset_type)).append("\n");
    sb.append("    bank_name: ").append(toIndentedString(bank_name)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
