/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * CustomerCompliancefirewallstaticdataBody
 */

public class CustomerCompliancefirewallstaticdataBody {
  @JsonProperty("dataset_data")
  private String dataset_data = null;

  @JsonProperty("dataset_name")
  private String dataset_name = null;

  public CustomerCompliancefirewallstaticdataBody dataset_data(String dataset_data) {
    this.dataset_data = dataset_data;
    return this;
  }

   /**
   * Get dataset_data
   * @return dataset_data
  **/
  public String getDatasetData() {
    return dataset_data;
  }

  public void setDatasetData(String dataset_data) {
    this.dataset_data = dataset_data;
  }

  public CustomerCompliancefirewallstaticdataBody dataset_name(String dataset_name) {
    this.dataset_name = dataset_name;
    return this;
  }

   /**
   * Get dataset_name
   * @return dataset_name
  **/
  public String getDatasetName() {
    return dataset_name;
  }

  public void setDatasetName(String dataset_name) {
    this.dataset_name = dataset_name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerCompliancefirewallstaticdataBody customer_compliancefirewallstaticdata_body = (CustomerCompliancefirewallstaticdataBody) o;
    return Objects.equals(this.dataset_data, customer_compliancefirewallstaticdata_body.dataset_data) &&
        Objects.equals(this.dataset_name, customer_compliancefirewallstaticdata_body.dataset_name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataset_data, dataset_name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerCompliancefirewallstaticdataBody {\n");
    
    sb.append("    dataset_data: ").append(toIndentedString(dataset_data)).append("\n");
    sb.append("    dataset_name: ").append(toIndentedString(dataset_name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
