/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse2001
 */

public class InlineResponse2001 {
  @JsonProperty("beneficiary_id")
  private String beneficiary_id = null;

  public InlineResponse2001 beneficiary_id(String beneficiary_id) {
    this.beneficiary_id = beneficiary_id;
    return this;
  }

   /**
   * The receiving Railsbank Beneficiary ID
   * @return beneficiary_id
  **/
  public String getBeneficiaryId() {
    return beneficiary_id;
  }

  public void setBeneficiaryId(String beneficiary_id) {
    this.beneficiary_id = beneficiary_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inline_response_200_1 = (InlineResponse2001) o;
    return Objects.equals(this.beneficiary_id, inline_response_200_1.beneficiary_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beneficiary_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    beneficiary_id: ").append(toIndentedString(beneficiary_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
