/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20093
 */

public class InlineResponse20093 {
  /**
   * Gets or Sets idv_documents_missing
   */
  public enum IdvDocumentsMissingEnum {
    DRIVING_LICENCE_FRONT("driving-licence-front"),
    NATIONAL_IDENTITY_FRONT("national-identity-front"),
    PASSPORT("passport"),
    DRIVING_LICENCE_BACK("driving-licence-back"),
    NATIONAL_IDENTITY_BACK("national-identity-back");

    private String value;

    IdvDocumentsMissingEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static IdvDocumentsMissingEnum fromValue(String input) {
      for (IdvDocumentsMissingEnum b : IdvDocumentsMissingEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("idv_documents_missing")
  private List<IdvDocumentsMissingEnum> idv_documents_missing = null;

  /**
   * Gets or Sets idv_documents_uploaded
   */
  public enum IdvDocumentsUploadedEnum {
    DRIVING_LICENCE_FRONT("driving-licence-front"),
    NATIONAL_IDENTITY_FRONT("national-identity-front"),
    PASSPORT("passport"),
    DRIVING_LICENCE_BACK("driving-licence-back"),
    NATIONAL_IDENTITY_BACK("national-identity-back");

    private String value;

    IdvDocumentsUploadedEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static IdvDocumentsUploadedEnum fromValue(String input) {
      for (IdvDocumentsUploadedEnum b : IdvDocumentsUploadedEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("idv_documents_uploaded")
  private List<IdvDocumentsUploadedEnum> idv_documents_uploaded = null;

  public InlineResponse20093 idv_documents_missing(List<IdvDocumentsMissingEnum> idv_documents_missing) {
    this.idv_documents_missing = idv_documents_missing;
    return this;
  }

  public InlineResponse20093 addIdvDocumentsMissingItem(IdvDocumentsMissingEnum idv_documents_missingItem) {
    if (this.idv_documents_missing == null) {
      this.idv_documents_missing = new ArrayList<>();
    }
    this.idv_documents_missing.add(idv_documents_missingItem);
    return this;
  }

   /**
   * Get idv_documents_missing
   * @return idv_documents_missing
  **/
  public List<IdvDocumentsMissingEnum> getIdvDocumentsMissing() {
    return idv_documents_missing;
  }

  public void setIdvDocumentsMissing(List<IdvDocumentsMissingEnum> idv_documents_missing) {
    this.idv_documents_missing = idv_documents_missing;
  }

  public InlineResponse20093 idv_documents_uploaded(List<IdvDocumentsUploadedEnum> idv_documents_uploaded) {
    this.idv_documents_uploaded = idv_documents_uploaded;
    return this;
  }

  public InlineResponse20093 addIdvDocumentsUploadedItem(IdvDocumentsUploadedEnum idv_documents_uploadedItem) {
    if (this.idv_documents_uploaded == null) {
      this.idv_documents_uploaded = new ArrayList<>();
    }
    this.idv_documents_uploaded.add(idv_documents_uploadedItem);
    return this;
  }

   /**
   * Get idv_documents_uploaded
   * @return idv_documents_uploaded
  **/
  public List<IdvDocumentsUploadedEnum> getIdvDocumentsUploaded() {
    return idv_documents_uploaded;
  }

  public void setIdvDocumentsUploaded(List<IdvDocumentsUploadedEnum> idv_documents_uploaded) {
    this.idv_documents_uploaded = idv_documents_uploaded;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20093 inline_response_200_93 = (InlineResponse20093) o;
    return Objects.equals(this.idv_documents_missing, inline_response_200_93.idv_documents_missing) &&
        Objects.equals(this.idv_documents_uploaded, inline_response_200_93.idv_documents_uploaded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idv_documents_missing, idv_documents_uploaded);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20093 {\n");
    
    sb.append("    idv_documents_missing: ").append(toIndentedString(idv_documents_missing)).append("\n");
    sb.append("    idv_documents_uploaded: ").append(toIndentedString(idv_documents_uploaded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
