/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDateTime;
/**
 * InlineResponse20043ApiKeysCustomer
 */

public class InlineResponse20043ApiKeysCustomer {
  @JsonProperty("api_key_description")
  private String api_key_description = null;

  @JsonProperty("api_key_created_at")
  private LocalDateTime api_key_created_at = null;

  /**
   * Gets or Sets api_key_role
   */
  public enum ApiKeyRoleEnum {
    READ_ONLY("customer-read-only"),
    ADMIN("customer-admin");

    private String value;

    ApiKeyRoleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ApiKeyRoleEnum fromValue(String input) {
      for (ApiKeyRoleEnum b : ApiKeyRoleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("api_key_role")
  private ApiKeyRoleEnum api_key_role = null;

  @JsonProperty("api_key_id")
  private String api_key_id = null;

  public InlineResponse20043ApiKeysCustomer api_key_description(String api_key_description) {
    this.api_key_description = api_key_description;
    return this;
  }

   /**
   * Get api_key_description
   * @return api_key_description
  **/
  public String getApiKeyDescription() {
    return api_key_description;
  }

  public void setApiKeyDescription(String api_key_description) {
    this.api_key_description = api_key_description;
  }

  public InlineResponse20043ApiKeysCustomer api_key_created_at(LocalDateTime api_key_created_at) {
    this.api_key_created_at = api_key_created_at;
    return this;
  }

   /**
   * Get api_key_created_at
   * @return api_key_created_at
  **/
  public LocalDateTime getApiKeyCreatedAt() {
    return api_key_created_at;
  }

  public void setApiKeyCreatedAt(LocalDateTime api_key_created_at) {
    this.api_key_created_at = api_key_created_at;
  }

  public InlineResponse20043ApiKeysCustomer api_key_role(ApiKeyRoleEnum api_key_role) {
    this.api_key_role = api_key_role;
    return this;
  }

   /**
   * Get api_key_role
   * @return api_key_role
  **/
  public ApiKeyRoleEnum getApiKeyRole() {
    return api_key_role;
  }

  public void setApiKeyRole(ApiKeyRoleEnum api_key_role) {
    this.api_key_role = api_key_role;
  }

  public InlineResponse20043ApiKeysCustomer api_key_id(String api_key_id) {
    this.api_key_id = api_key_id;
    return this;
  }

   /**
   * Get api_key_id
   * @return api_key_id
  **/
  public String getApiKeyId() {
    return api_key_id;
  }

  public void setApiKeyId(String api_key_id) {
    this.api_key_id = api_key_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20043ApiKeysCustomer inline_response_200_43_api_keys_customer = (InlineResponse20043ApiKeysCustomer) o;
    return Objects.equals(this.api_key_description, inline_response_200_43_api_keys_customer.api_key_description) &&
        Objects.equals(this.api_key_created_at, inline_response_200_43_api_keys_customer.api_key_created_at) &&
        Objects.equals(this.api_key_role, inline_response_200_43_api_keys_customer.api_key_role) &&
        Objects.equals(this.api_key_id, inline_response_200_43_api_keys_customer.api_key_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(api_key_description, api_key_created_at, api_key_role, api_key_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20043ApiKeysCustomer {\n");
    
    sb.append("    api_key_description: ").append(toIndentedString(api_key_description)).append("\n");
    sb.append("    api_key_created_at: ").append(toIndentedString(api_key_created_at)).append("\n");
    sb.append("    api_key_role: ").append(toIndentedString(api_key_role)).append("\n");
    sb.append("    api_key_id: ").append(toIndentedString(api_key_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
