/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse20022
 */

public class InlineResponse20022 {
  @JsonProperty("card_rule_id")
  private String card_rule_id = null;

  public InlineResponse20022 card_rule_id(String card_rule_id) {
    this.card_rule_id = card_rule_id;
    return this;
  }

   /**
   * The rule&#x27;s uuid
   * @return card_rule_id
  **/
  public String getCardRuleId() {
    return card_rule_id;
  }

  public void setCardRuleId(String card_rule_id) {
    this.card_rule_id = card_rule_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20022 inline_response_200_22 = (InlineResponse20022) o;
    return Objects.equals(this.card_rule_id, inline_response_200_22.card_rule_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(card_rule_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20022 {\n");
    
    sb.append("    card_rule_id: ").append(toIndentedString(card_rule_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
