/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse20049
 */

public class InlineResponse20049 {
  @JsonProperty("slack_channel")
  private String slack_channel = null;

  @JsonProperty("slack_domain")
  private String slack_domain = null;

  @JsonProperty("email")
  private String email = null;

  public InlineResponse20049 slack_channel(String slack_channel) {
    this.slack_channel = slack_channel;
    return this;
  }

   /**
   * Get slack_channel
   * @return slack_channel
  **/
  public String getSlackChannel() {
    return slack_channel;
  }

  public void setSlackChannel(String slack_channel) {
    this.slack_channel = slack_channel;
  }

  public InlineResponse20049 slack_domain(String slack_domain) {
    this.slack_domain = slack_domain;
    return this;
  }

   /**
   * Get slack_domain
   * @return slack_domain
  **/
  public String getSlackDomain() {
    return slack_domain;
  }

  public void setSlackDomain(String slack_domain) {
    this.slack_domain = slack_domain;
  }

  public InlineResponse20049 email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20049 inline_response_200_49 = (InlineResponse20049) o;
    return Objects.equals(this.slack_channel, inline_response_200_49.slack_channel) &&
        Objects.equals(this.slack_domain, inline_response_200_49.slack_domain) &&
        Objects.equals(this.email, inline_response_200_49.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slack_channel, slack_domain, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20049 {\n");
    
    sb.append("    slack_channel: ").append(toIndentedString(slack_channel)).append("\n");
    sb.append("    slack_domain: ").append(toIndentedString(slack_domain)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
