/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.RBSwagger.model.V1customercardsAdditionalLedgers;
import com.transfer_funds.RBSwagger.model.V1customercardsCardDeliveryAddress;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20082
 */

public class InlineResponse20082 {
  @JsonProperty("card_design")
  private String card_design = null;

  @JsonProperty("additional_ledgers")
  private List<V1customercardsAdditionalLedgers> additional_ledgers = null;

  @JsonProperty("card_expiry_date")
  private String card_expiry_date = null;

  @JsonProperty("replaced_card_id")
  private String replaced_card_id = null;

  @JsonProperty("created_at")
  private LocalDateTime created_at = null;

  @JsonProperty("card_rules")
  private List<String> card_rules = null;

  /**
   * The type of card.
   */
  public enum CardTypeEnum {
    VIRTUAL("virtual"),
    PHYSICAL("physical");

    private String value;

    CardTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CardTypeEnum fromValue(String input) {
      for (CardTypeEnum b : CardTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("card_type")
  private CardTypeEnum card_type = null;

  /**
   * Human readable identifier of the Railsbank product that provides card functionality.
   */
  public enum PartnerProductEnum {
    CREDIT_CARD_1("Railsbank-Credit-Card-1"),
    DEBIT_CARD_3("Railsbank-Debit-Card-3"),
    DEBIT_CARD_1("Railsbank-Debit-Card-1"),
    DEBIT_CARD_2("Railsbank-Debit-Card-2");

    private String value;

    PartnerProductEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PartnerProductEnum fromValue(String input) {
      for (PartnerProductEnum b : PartnerProductEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("partner_product")
  private PartnerProductEnum partner_product = null;

  @JsonProperty("card_id")
  private String card_id = null;

  @JsonProperty("card_status_reason")
  private String card_status_reason = null;

  @JsonProperty("truncated_pan")
  private String truncated_pan = null;

  /**
   * The shipping method used to deliver the card, if delivery address is outside the UK, it must be international-mail
   */
  public enum CardDeliveryMethodEnum {
    STANDARD_FIRST_CLASS("standard-first-class"),
    INTERNATIONAL_MAIL("international-mail"),
    DHL("dhl"),
    COURIER("courier");

    private String value;

    CardDeliveryMethodEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CardDeliveryMethodEnum fromValue(String input) {
      for (CardDeliveryMethodEnum b : CardDeliveryMethodEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("card_delivery_method")
  private CardDeliveryMethodEnum card_delivery_method = null;

  /**
   * The carrier type to be used for the card when delivered.
   */
  public enum CardCarrierTypeEnum {
    RENEWAL("renewal"),
    REPLACEMENT("replacement"),
    STANDARD("standard");

    private String value;

    CardCarrierTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CardCarrierTypeEnum fromValue(String input) {
      for (CardCarrierTypeEnum b : CardCarrierTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("card_carrier_type")
  private CardCarrierTypeEnum card_carrier_type = null;

  /**
   * Current card status.
   */
  public enum CardStatusEnum {
    CARD_STATUS_ACTIVE("card-status-active"),
    CARD_STATUS_FAILED("card-status-failed"),
    CARD_STATUS_REACTIVATING("card-status-reactivating"),
    CARD_STATUS_SUSPENDING("card-status-suspending"),
    CARD_STATUS_AWAITING_ACTIVATION("card-status-awaiting-activation"),
    CARD_STATUS_CREATED("card-status-created"),
    CARD_STATUS_SUSPENDED("card-status-suspended"),
    CARD_STATUS_CLOSED("card-status-closed"),
    CARD_STATUS_ACTIVATING("card-status-activating"),
    ENTITY_STATUS_INTERNAL_ERROR("entity-status-internal-error");

    private String value;

    CardStatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CardStatusEnum fromValue(String input) {
      for (CardStatusEnum b : CardStatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("card_status")
  private CardStatusEnum card_status = null;

  @JsonProperty("card_delivery_address")
  private V1customercardsCardDeliveryAddress card_delivery_address = null;

  @JsonProperty("card_programme")
  private String card_programme = null;

  @JsonProperty("qr_code_content")
  private String qr_code_content = null;

  @JsonProperty("card_delivery_name")
  private String card_delivery_name = null;

  @JsonProperty("card_token")
  private String card_token = null;

  @JsonProperty("replaced_card_token")
  private String replaced_card_token = null;

  @JsonProperty("ledger_id")
  private String ledger_id = null;

  @JsonProperty("name_on_card")
  private String name_on_card = null;

  public InlineResponse20082 card_design(String card_design) {
    this.card_design = card_design;
    return this;
  }

   /**
   * The card design to be used for the card when issued, from the list of Railsbank configured card designs.
   * @return card_design
  **/
  public String getCardDesign() {
    return card_design;
  }

  public void setCardDesign(String card_design) {
    this.card_design = card_design;
  }

  public InlineResponse20082 additional_ledgers(List<V1customercardsAdditionalLedgers> additional_ledgers) {
    this.additional_ledgers = additional_ledgers;
    return this;
  }

  public InlineResponse20082 addAdditionalLedgersItem(V1customercardsAdditionalLedgers additional_ledgersItem) {
    if (this.additional_ledgers == null) {
      this.additional_ledgers = new ArrayList<>();
    }
    this.additional_ledgers.add(additional_ledgersItem);
    return this;
  }

   /**
   * Get additional_ledgers
   * @return additional_ledgers
  **/
  public List<V1customercardsAdditionalLedgers> getAdditionalLedgers() {
    return additional_ledgers;
  }

  public void setAdditionalLedgers(List<V1customercardsAdditionalLedgers> additional_ledgers) {
    this.additional_ledgers = additional_ledgers;
  }

  public InlineResponse20082 card_expiry_date(String card_expiry_date) {
    this.card_expiry_date = card_expiry_date;
    return this;
  }

   /**
   * Get card_expiry_date
   * @return card_expiry_date
  **/
  public String getCardExpiryDate() {
    return card_expiry_date;
  }

  public void setCardExpiryDate(String card_expiry_date) {
    this.card_expiry_date = card_expiry_date;
  }

  public InlineResponse20082 replaced_card_id(String replaced_card_id) {
    this.replaced_card_id = replaced_card_id;
    return this;
  }

   /**
   * Unique identifier of the old card.
   * @return replaced_card_id
  **/
  public String getReplacedCardId() {
    return replaced_card_id;
  }

  public void setReplacedCardId(String replaced_card_id) {
    this.replaced_card_id = replaced_card_id;
  }

  public InlineResponse20082 created_at(LocalDateTime created_at) {
    this.created_at = created_at;
    return this;
  }

   /**
   * Get created_at
   * @return created_at
  **/
  public LocalDateTime getCreatedAt() {
    return created_at;
  }

  public void setCreatedAt(LocalDateTime created_at) {
    this.created_at = created_at;
  }

  public InlineResponse20082 card_rules(List<String> card_rules) {
    this.card_rules = card_rules;
    return this;
  }

  public InlineResponse20082 addCardRulesItem(String card_rulesItem) {
    if (this.card_rules == null) {
      this.card_rules = new ArrayList<>();
    }
    this.card_rules.add(card_rulesItem);
    return this;
  }

   /**
   * Get card_rules
   * @return card_rules
  **/
  public List<String> getCardRules() {
    return card_rules;
  }

  public void setCardRules(List<String> card_rules) {
    this.card_rules = card_rules;
  }

  public InlineResponse20082 card_type(CardTypeEnum card_type) {
    this.card_type = card_type;
    return this;
  }

   /**
   * The type of card.
   * @return card_type
  **/
  public CardTypeEnum getCardType() {
    return card_type;
  }

  public void setCardType(CardTypeEnum card_type) {
    this.card_type = card_type;
  }

  public InlineResponse20082 partner_product(PartnerProductEnum partner_product) {
    this.partner_product = partner_product;
    return this;
  }

   /**
   * Human readable identifier of the Railsbank product that provides card functionality.
   * @return partner_product
  **/
  public PartnerProductEnum getPartnerProduct() {
    return partner_product;
  }

  public void setPartnerProduct(PartnerProductEnum partner_product) {
    this.partner_product = partner_product;
  }

  public InlineResponse20082 card_id(String card_id) {
    this.card_id = card_id;
    return this;
  }

   /**
   * Railsbank&#x27;s unique identifier for the card.
   * @return card_id
  **/
  public String getCardId() {
    return card_id;
  }

  public void setCardId(String card_id) {
    this.card_id = card_id;
  }

  public InlineResponse20082 card_status_reason(String card_status_reason) {
    this.card_status_reason = card_status_reason;
    return this;
  }

   /**
   * Get card_status_reason
   * @return card_status_reason
  **/
  public String getCardStatusReason() {
    return card_status_reason;
  }

  public void setCardStatusReason(String card_status_reason) {
    this.card_status_reason = card_status_reason;
  }

  public InlineResponse20082 truncated_pan(String truncated_pan) {
    this.truncated_pan = truncated_pan;
    return this;
  }

   /**
   * Last 4 characters of the PAN.
   * @return truncated_pan
  **/
  public String getTruncatedPan() {
    return truncated_pan;
  }

  public void setTruncatedPan(String truncated_pan) {
    this.truncated_pan = truncated_pan;
  }

  public InlineResponse20082 card_delivery_method(CardDeliveryMethodEnum card_delivery_method) {
    this.card_delivery_method = card_delivery_method;
    return this;
  }

   /**
   * The shipping method used to deliver the card, if delivery address is outside the UK, it must be international-mail
   * @return card_delivery_method
  **/
  public CardDeliveryMethodEnum getCardDeliveryMethod() {
    return card_delivery_method;
  }

  public void setCardDeliveryMethod(CardDeliveryMethodEnum card_delivery_method) {
    this.card_delivery_method = card_delivery_method;
  }

  public InlineResponse20082 card_carrier_type(CardCarrierTypeEnum card_carrier_type) {
    this.card_carrier_type = card_carrier_type;
    return this;
  }

   /**
   * The carrier type to be used for the card when delivered.
   * @return card_carrier_type
  **/
  public CardCarrierTypeEnum getCardCarrierType() {
    return card_carrier_type;
  }

  public void setCardCarrierType(CardCarrierTypeEnum card_carrier_type) {
    this.card_carrier_type = card_carrier_type;
  }

  public InlineResponse20082 card_status(CardStatusEnum card_status) {
    this.card_status = card_status;
    return this;
  }

   /**
   * Current card status.
   * @return card_status
  **/
  public CardStatusEnum getCardStatus() {
    return card_status;
  }

  public void setCardStatus(CardStatusEnum card_status) {
    this.card_status = card_status;
  }

  public InlineResponse20082 card_delivery_address(V1customercardsCardDeliveryAddress card_delivery_address) {
    this.card_delivery_address = card_delivery_address;
    return this;
  }

   /**
   * Get card_delivery_address
   * @return card_delivery_address
  **/
  public V1customercardsCardDeliveryAddress getCardDeliveryAddress() {
    return card_delivery_address;
  }

  public void setCardDeliveryAddress(V1customercardsCardDeliveryAddress card_delivery_address) {
    this.card_delivery_address = card_delivery_address;
  }

  public InlineResponse20082 card_programme(String card_programme) {
    this.card_programme = card_programme;
    return this;
  }

   /**
   * The card programme to issue the card against, from Railsbank configuration.
   * @return card_programme
  **/
  public String getCardProgramme() {
    return card_programme;
  }

  public void setCardProgramme(String card_programme) {
    this.card_programme = card_programme;
  }

  public InlineResponse20082 qr_code_content(String qr_code_content) {
    this.qr_code_content = qr_code_content;
    return this;
  }

   /**
   * The string to be encoded in the auto-generated QR code on a physical card. For example, a URL, SMS message, in app action, an event etc.
   * @return qr_code_content
  **/
  public String getQrCodeContent() {
    return qr_code_content;
  }

  public void setQrCodeContent(String qr_code_content) {
    this.qr_code_content = qr_code_content;
  }

  public InlineResponse20082 card_delivery_name(String card_delivery_name) {
    this.card_delivery_name = card_delivery_name;
    return this;
  }

   /**
   * The name which the delivery will be addressed to (can differ from cardholder name).
   * @return card_delivery_name
  **/
  public String getCardDeliveryName() {
    return card_delivery_name;
  }

  public void setCardDeliveryName(String card_delivery_name) {
    this.card_delivery_name = card_delivery_name;
  }

  public InlineResponse20082 card_token(String card_token) {
    this.card_token = card_token;
    return this;
  }

   /**
   * Enduser facing card identifier printed on the card. Unique per card programme. Shorter than card_id.
   * @return card_token
  **/
  public String getCardToken() {
    return card_token;
  }

  public void setCardToken(String card_token) {
    this.card_token = card_token;
  }

  public InlineResponse20082 replaced_card_token(String replaced_card_token) {
    this.replaced_card_token = replaced_card_token;
    return this;
  }

   /**
   * Enduser facing card identifier of the old card.
   * @return replaced_card_token
  **/
  public String getReplacedCardToken() {
    return replaced_card_token;
  }

  public void setReplacedCardToken(String replaced_card_token) {
    this.replaced_card_token = replaced_card_token;
  }

  public InlineResponse20082 ledger_id(String ledger_id) {
    this.ledger_id = ledger_id;
    return this;
  }

   /**
   * Railsbank Ledger ID which the card was issued against.
   * @return ledger_id
  **/
  public String getLedgerId() {
    return ledger_id;
  }

  public void setLedgerId(String ledger_id) {
    this.ledger_id = ledger_id;
  }

  public InlineResponse20082 name_on_card(String name_on_card) {
    this.name_on_card = name_on_card;
    return this;
  }

   /**
   * The cardholder&#x27;s name to be printed or embossed on the card. It accepts ISO basic Latin alphabet and can be up to 21 characters long including spaces.
   * @return name_on_card
  **/
  public String getNameOnCard() {
    return name_on_card;
  }

  public void setNameOnCard(String name_on_card) {
    this.name_on_card = name_on_card;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20082 inline_response_200_82 = (InlineResponse20082) o;
    return Objects.equals(this.card_design, inline_response_200_82.card_design) &&
        Objects.equals(this.additional_ledgers, inline_response_200_82.additional_ledgers) &&
        Objects.equals(this.card_expiry_date, inline_response_200_82.card_expiry_date) &&
        Objects.equals(this.replaced_card_id, inline_response_200_82.replaced_card_id) &&
        Objects.equals(this.created_at, inline_response_200_82.created_at) &&
        Objects.equals(this.card_rules, inline_response_200_82.card_rules) &&
        Objects.equals(this.card_type, inline_response_200_82.card_type) &&
        Objects.equals(this.partner_product, inline_response_200_82.partner_product) &&
        Objects.equals(this.card_id, inline_response_200_82.card_id) &&
        Objects.equals(this.card_status_reason, inline_response_200_82.card_status_reason) &&
        Objects.equals(this.truncated_pan, inline_response_200_82.truncated_pan) &&
        Objects.equals(this.card_delivery_method, inline_response_200_82.card_delivery_method) &&
        Objects.equals(this.card_carrier_type, inline_response_200_82.card_carrier_type) &&
        Objects.equals(this.card_status, inline_response_200_82.card_status) &&
        Objects.equals(this.card_delivery_address, inline_response_200_82.card_delivery_address) &&
        Objects.equals(this.card_programme, inline_response_200_82.card_programme) &&
        Objects.equals(this.qr_code_content, inline_response_200_82.qr_code_content) &&
        Objects.equals(this.card_delivery_name, inline_response_200_82.card_delivery_name) &&
        Objects.equals(this.card_token, inline_response_200_82.card_token) &&
        Objects.equals(this.replaced_card_token, inline_response_200_82.replaced_card_token) &&
        Objects.equals(this.ledger_id, inline_response_200_82.ledger_id) &&
        Objects.equals(this.name_on_card, inline_response_200_82.name_on_card);
  }

  @Override
  public int hashCode() {
    return Objects.hash(card_design, additional_ledgers, card_expiry_date, replaced_card_id, created_at, card_rules, card_type, partner_product, card_id, card_status_reason, truncated_pan, card_delivery_method, card_carrier_type, card_status, card_delivery_address, card_programme, qr_code_content, card_delivery_name, card_token, replaced_card_token, ledger_id, name_on_card);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20082 {\n");
    
    sb.append("    card_design: ").append(toIndentedString(card_design)).append("\n");
    sb.append("    additional_ledgers: ").append(toIndentedString(additional_ledgers)).append("\n");
    sb.append("    card_expiry_date: ").append(toIndentedString(card_expiry_date)).append("\n");
    sb.append("    replaced_card_id: ").append(toIndentedString(replaced_card_id)).append("\n");
    sb.append("    created_at: ").append(toIndentedString(created_at)).append("\n");
    sb.append("    card_rules: ").append(toIndentedString(card_rules)).append("\n");
    sb.append("    card_type: ").append(toIndentedString(card_type)).append("\n");
    sb.append("    partner_product: ").append(toIndentedString(partner_product)).append("\n");
    sb.append("    card_id: ").append(toIndentedString(card_id)).append("\n");
    sb.append("    card_status_reason: ").append(toIndentedString(card_status_reason)).append("\n");
    sb.append("    truncated_pan: ").append(toIndentedString(truncated_pan)).append("\n");
    sb.append("    card_delivery_method: ").append(toIndentedString(card_delivery_method)).append("\n");
    sb.append("    card_carrier_type: ").append(toIndentedString(card_carrier_type)).append("\n");
    sb.append("    card_status: ").append(toIndentedString(card_status)).append("\n");
    sb.append("    card_delivery_address: ").append(toIndentedString(card_delivery_address)).append("\n");
    sb.append("    card_programme: ").append(toIndentedString(card_programme)).append("\n");
    sb.append("    qr_code_content: ").append(toIndentedString(qr_code_content)).append("\n");
    sb.append("    card_delivery_name: ").append(toIndentedString(card_delivery_name)).append("\n");
    sb.append("    card_token: ").append(toIndentedString(card_token)).append("\n");
    sb.append("    replaced_card_token: ").append(toIndentedString(replaced_card_token)).append("\n");
    sb.append("    ledger_id: ").append(toIndentedString(ledger_id)).append("\n");
    sb.append("    name_on_card: ").append(toIndentedString(name_on_card)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
