/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * V1customerbeneficiariesCompanyStockExchanges
 */

public class V1customerbeneficiariesCompanyStockExchanges {
  /**
   * Gets or Sets stock_exchange_name
   */
  public enum StockExchangeNameEnum {
    AR_ROSARIO_STOCK_EXCHANGE_BCR("AR-Rosario-Stock-Exchange-BCR"),
    JP_TOKYO_STOCK_EXCHANGE_TSE("JP-Tokyo-Stock-Exchange-TSE"),
    IS_ICELAND_STOCK_EXCHANGE_XICE("IS-Iceland-Stock-Exchange-XICE"),
    US_C2_OPTIONS_EXCHANGE_C2("US-C2-Options-Exchange-C2"),
    AI_EASTERN_CARIBBEAN_SECURITIES_EXCHANGE_ECSE("AI-Eastern-Caribbean-Securities-Exchange-ECSE"),
    BM_BERMUDA_STOCK_EXCHANGE_BSX("BM-Bermuda-Stock-Exchange-BSX"),
    MV_MALDIVES_STOCK_EXCHANGE_MSE("MV-Maldives-Stock-Exchange-MSE"),
    JO_AMMAN_STOCK_EXCHANGE_ASE("JO-Amman-Stock-Exchange-ASE"),
    MX_BOLSA_MEXICANA_DE_VALORES_BMV("MX-Bolsa-Mexicana-de-Valores-BMV"),
    PH_MANILA_COMMODITY_EXCHANGE_MCX("PH-Manila-Commodity-Exchange-MCX"),
    SA_TADAWUL_TADAWUL("SA-Tadawul-Tadawul"),
    GT_BOLSA_NACIONAL_DE_VALORES_BNV("GT-Bolsa-Nacional-de-Valores-BNV"),
    CN_SHENZHEN_STOCK_EXCHANGE_SZSE("CN-Shenzhen-Stock-Exchange-SZSE"),
    CL_BOLSA_COMERCIO_DE_SANTIAGO_MILA_SSE("CL-Bolsa-Comercio-de-Santiago-MILA-SSE"),
    US_BATS_Y_EXCHANGE_BYX("US-BATS-Y-Exchange-BYX"),
    JP_HERCULES_FORMERLY_NASDAQ_JAPAN_OSE_HERCULES("JP-Hercules-formerly-Nasdaq-Japan-OSE-Hercules"),
    PK_ISLAMABAD_STOCK_EXCHANGE("PK-Islamabad-Stock-Exchange"),
    MS_EASTERN_CARIBBEAN_SECURITIES_EXCHANGE_ECSE("MS-Eastern-Caribbean-Securities-Exchange-ECSE"),
    DE_EUREX_EXCHANGE_XEUR("DE-Eurex-Exchange-XEUR"),
    AM_ARMENIAN_STOCK_EXCHANGE_XARM("AM-Armenian-Stock-Exchange-XARM"),
    HN_BOLSA_CENTROAMERICANA_DE_VALORES_BCV("HN-Bolsa-Centroamericana-de-Valores-BCV"),
    HN_BOLSA_HONDURAS_DE_VALORES_BHV("HN-Bolsa-Honduras-de-Valores-BHV"),
    US_NASDAQ_OMX_BX_BX("US-NASDAQ-OMX-BX-BX"),
    US_NYSE_MKT_NYSE_MKT("US-NYSE-MKT-NYSE-MKT"),
    CY_CYPRUS_STOCK_EXCHANGE_XCYS("CY-Cyprus-Stock-Exchange-XCYS"),
    US_ISE_AND_ISE_GEMINI_ISE("US-ISE-and-ISE-Gemini-ISE"),
    OM_MUSCAT_SECURITIES_MARKET_MSM("OM-Muscat-Securities-Market-MSM"),
    DE_BORSE_MUNCHEN_XMUN("DE-Borse-Munchen-XMUN"),
    BW_BOTSWANA_STOCK_EXCHANGE_BSE("BW-Botswana-Stock-Exchange-BSE"),
    BD_CHITTAGONG_STOCK_EXCHANGE_CSE("BD-Chittagong-Stock-Exchange-CSE"),
    MY_MALAYSIA_DERIVATIVES_EXCHANGE("MY-Malaysia-Derivatives-Exchange"),
    MM_YANGON_STOCK_EXCHANGE_YSX("MM-Yangon-Stock-Exchange-YSX"),
    IN_CALCUTTA_STOCK_EXCHANGE("IN-Calcutta-Stock-Exchange"),
    IN_MADRAS_STOCK_EXCHANGE("IN-Madras-Stock-Exchange"),
    CN_SHANGHAI_STOCK_EXCHANGE_SSE("CN-Shanghai-Stock-Exchange-SSE"),
    AL_TIRANA_STOCK_EXCHANGE_XTIR("AL-Tirana-Stock-Exchange-XTIR"),
    ES_BOLSA_DE_MADRID_BMEX("ES-Bolsa-de-Madrid-BMEX"),
    BR_BRAZILIAN_MERCANTILE_AND_FUTURES_EXCHANGE_BM_F("BR-Brazilian-Mercantile-and-Futures-Exchange-BM-F"),
    KN_EASTERN_CARIBBEAN_SECURITIES_EXCHANGE_ECSE("KN-Eastern-Caribbean-Securities-Exchange-ECSE"),
    AU_ASIA_PACIFIC_STOCK_EXCHANGE("AU-Asia-Pacific-Stock-Exchange"),
    IN_INTER_CONNECTED_STOCK_EXCHANGE_OF_INDIA("IN-Inter-connected-Stock-Exchange-of-India"),
    UG_UGANDA_SECURITIES_EXCHANGE_USE("UG-Uganda-Securities-Exchange-USE"),
    IN_BHUBANESWAR_STOCK_EXCHANGE("IN-Bhubaneswar-Stock-Exchange"),
    LB_BEIRUT_STOCK_EXCHANGE_BSE("LB-Beirut-Stock-Exchange-BSE"),
    BR_RIO_DE_JANEIRO_STOCK_EXCHANGE_BVRJ("BR-Rio-de-Janeiro-Stock-Exchange-BVRJ"),
    KW_KUWAIT_STOCK_EXCHANGE_KSE("KW-Kuwait-Stock-Exchange-KSE"),
    JP_OSAKA_SECURITIES_EXCHANGE_OSE("JP-Osaka-Securities-Exchange-OSE"),
    JP_AMBITIOUS_AMB("JP-Ambitious-AMB"),
    JP_CENTREX_CENTREX("JP-Centrex-Centrex"),
    CZ_PRAGUE_STOCK_EXCHANGE_XPRA("CZ-Prague-Stock-Exchange-XPRA"),
    CA_MONTREAL_EXCHANGE_MX("CA-Montreal-Exchange-MX"),
    KZ_KAZAKHSTAN_STOCK_EXCHANGE_KASE("KZ-Kazakhstan-Stock-Exchange-KASE"),
    EE_TALLINN_STOCK_EXCHANGE_XTAL("EE-Tallinn-Stock-Exchange-XTAL"),
    IN_OTC_EXCHANGE_OF_INDIA("IN-OTC-Exchange-of-India"),
    TH_MARKET_FOR_ALTERNATIVE_INVESTMENT_MAI("TH-Market-for-Alternative-Investment-MAI"),
    NP_NEPAL_STOCK_EXCHANGE_NEPSE("NP-Nepal-Stock-Exchange-NEPSE"),
    GE_GEORGIAN_STOCK_EXCHANGE_XGSE("GE-Georgian-Stock-Exchange-XGSE"),
    LS_MASERU_SECURITIES_EXCHANGE_MSM("LS-Maseru-Securities-Exchange-MSM"),
    RO_BUCHAREST_STOCK_EXCHANGE_XBSE("RO-Bucharest-Stock-Exchange-XBSE"),
    CA_TORONTO_STOCK_EXCHANGE_TSX("CA-Toronto-Stock-Exchange-TSX"),
    PT_OPEX_OPEX("PT-OPEX-OPEX"),
    SV_BOLSA_DE_VALORES_DE_EL_SALVADOR_BVES("SV-Bolsa-de-Valores-de-El-Salvador-BVES"),
    ES_BOLSA_DE_VALORES_DE_BARCELONA_BMEX("ES-Bolsa-de-Valores-de-Barcelona-BMEX"),
    CV_BOLSA_DE_VALORES_DE_CABO_VERDE_BVC("CV-Bolsa-de-Valores-de-Cabo-Verde-BVC"),
    BA_SARAJEVO_STOCK_EXCHANGE_XSSE("BA-Sarajevo-Stock-Exchange-XSSE"),
    DE_FRANKFURT_STOCK_EXCHANGE_XFRA("DE-Frankfurt-Stock-Exchange-XFRA"),
    IR_IRAN_FARA_BOURSE_IFB("IR-Iran-Fara-Bourse-IFB"),
    TH_STOCK_EXCHANGE_OF_THAILAND_SET("TH-Stock-Exchange-of-Thailand-SET"),
    AM_ARMENIAN_STOCK_EXCHANGE_NASDAQ_OMX_ARMENIA("AM-Armenian-Stock-Exchange-NASDAQ-OMX-Armenia"),
    DZ_ALGIERS_STOCK_EXCHANGE_SGBV("DZ-Algiers-Stock-Exchange-SGBV"),
    JP_NAGOYA_STOCK_EXCHANGE_NSE("JP-Nagoya-Stock-Exchange-NSE"),
    ZM_AGRICULTURAL_COMMODITIES_EXCHANGE_OF_ZAMBIA_ZAMACE("ZM-Agricultural-Commodities-Exchange-of-Zambia-ZAMACE"),
    DO_BOLSA_DE_VALORES_DE_LA_REPUBLICA_DOMINICANA_BVRD("DO-Bolsa-de-Valores-de-la-Republica-Dominicana-BVRD"),
    IN_LUDHIANA_STOCK_EXCHANGE_ASSOCIATION("IN-Ludhiana-Stock-Exchange-Association"),
    DK_COPENHAGEN_STOCK_EXCHANGE_XCSE("DK-Copenhagen-Stock-Exchange-XCSE"),
    IN_UNITED_STOCK_EXCHANGE_OF_INDIA("IN-United-Stock-Exchange-of-India"),
    PL_WARSAW_STOCK_EXCHANGE_XWAR("PL-Warsaw-Stock-Exchange-XWAR"),
    RU_SAINT_PETERSBURG_STOCK_EXCHANGE_SPIM("RU-Saint-Petersburg-Stock-Exchange-SPIM"),
    NO_NORWAY_OTC("NO-Norway-OTC"),
    IN_MADHYA_PRADESH_STOCK_EXCHANGE("IN-Madhya-Pradesh-Stock-Exchange"),
    SO_SOMALI_STOCK_EXCHANGE_SSE("SO-Somali-Stock-Exchange-SSE"),
    MK_MACEDONIAN_STOCK_EXCHANGE_XMAE("MK-Macedonian-Stock-Exchange-XMAE"),
    SD_KHARTOUM_STOCK_EXCHANGE_KSE("SD-Khartoum-Stock-Exchange-KSE"),
    MA_CASABLANCA_STOCK_EXCHANGE_CASA_SE("MA-Casablanca-Stock-Exchange-Casa-SE"),
    RO_SIBIU_STOCK_EXCHANGE_BMFX("RO-Sibiu-Stock-Exchange-BMFX"),
    MY_MESDAQ_MESDAQ("MY-MESDAQ-MESDAQ"),
    JP_JASDAQ_JASDAQ("JP-JASDAQ-JASDAQ"),
    IN_BANGALORE_STOCK_EXCHANGE("IN-Bangalore-Stock-Exchange"),
    RU_MOSCOW_EXCHANGE_MISX("RU-Moscow-Exchange-MISX"),
    DM_EASTERN_CARIBBEAN_SECURITIES_EXCHANGE_ECSE("DM-Eastern-Caribbean-Securities-Exchange-ECSE"),
    KH_CAMBODIA_SECURITIES_EXCHANGE_CSX("KH-Cambodia-Securities-Exchange-CSX"),
    US_MIAMI_INTERNATIONAL_SECURITIES_EXCHANGE_MIAX("US-Miami-International-Securities-Exchange-MIAX"),
    AU_NATIONAL_STOCK_EXCHANGE_OF_AUSTRALIA_NSXA("AU-National-Stock-Exchange-of-Australia-nsxa"),
    CA_TSX_VENTURE_EXCHANGE_TSX("CA-TSX-Venture-Exchange-TSX"),
    FO_FAROESE_SECURITIES_MARKET_VMFX("FO-Faroese-Securities-Market-VMFX"),
    CH_SIX_SWISS_EXCHANGE_XSWX("CH-SIX-Swiss-Exchange-XSWX"),
    SZ_SWAZILAND_STOCK_EXCHANGE_SSX("SZ-Swaziland-Stock-Exchange-SSX"),
    BG_BULGARIAN_STOCK_EXCHANGE_XBUL("BG-Bulgarian-Stock-Exchange-XBUL"),
    US_BOSTON_OPTIONS_EXCHANGE_BOX("US-Boston-Options-Exchange-BOX"),
    CY_CYPRUS_STOCK_EXCHANGE_CSE("CY-Cyprus-Stock-Exchange-CSE"),
    GB_THE_INTERNATIONAL_STOCK_EXCHANGE_XCIE("GB-The-International-Stock-Exchange-XCIE"),
    HT_HAITIAN_STOCK_EXCHANGE_HSE("HT-Haitian-Stock-Exchange-HSE"),
    PK_PAKISTAN_STOCK_EXCHANGE_PSX("PK-Pakistan-Stock-Exchange-PSX"),
    PA_BOLSA_DE_VALORES_DE_PANAMA_BVP("PA-Bolsa-de-Valores-de-Panama-BVP"),
    DE_DEUTSCHE_BORSE_GROUP_XETR_XFRA("DE-Deutsche-Borse-Group-XETR-XFRA"),
    CA_CANADIAN_SECURITIES_EXCHANGE_CSE("CA-Canadian-Securities-Exchange-CSE"),
    SG_STOCK_EXCHANGE_OF_SINGAPORE_SES("SG-Stock-Exchange-of-Singapore-SES"),
    IN_SAURASHTRA_KUTCH_STOCK_EXCHANGE("IN-Saurashtra-Kutch-Stock-Exchange"),
    AR_BUENOS_AIRES_STOCK_EXCHANGE_BCBA("AR-Buenos-Aires-Stock-Exchange-BCBA"),
    SC_SEYCHELLES_SECURITIES_EXCHANGE_TROP_X_SSE("SC-Seychelles-Securities-Exchange-Trop-X-SSE"),
    ES_MERCADO_OFICIAL_ESPANOL_DE_FUTUROS_Y_OPCIONES_BMEX("ES-Mercado-Oficial-Espanol-de-Futuros-y-Opciones-BMEX"),
    ES_BOLSA_DE_VALORES_DE_BILBAO_BMEX("ES-Bolsa-de-Valores-de-Bilbao-BMEX"),
    NZ_NEW_ZEALAND_EXCHANGE("NZ-New-Zealand-Exchange"),
    UZ_TASHKENT_REPUBLICAN_STOCK_EXCHANGE("UZ-Tashkent-Republican-Stock-Exchange"),
    BE_EURONEXT_BRUSSELS_XBRU("BE-Euronext-Brussels-XBRU"),
    AE_NASDAQ_DUBAI_NASDAQ_DUBAI("AE-NASDAQ-Dubai-NASDAQ-Dubai"),
    UY_BOLSA_DE_VALORES_DE_MONTEVIDEO_BVM("UY-Bolsa-de-Valores-de-Montevideo-BVM"),
    PH_PHILIPPINE_DEALING_EXCHANGE_PDEX("PH-Philippine-Dealing-Exchange-PDEx"),
    IN_NATIONAL_STOCK_EXCHANGE_OF_INDIA("IN-National-Stock-Exchange-of-India"),
    SE_NORDIC_GROWTH_MARKET_XNGM("SE-Nordic-Growth-Market-XNGM"),
    JP_Q_BOARD_QB("JP-Q-Board-QB"),
    US_NASDAQ_OMX_PHLX_PHLX("US-NASDAQ-OMX-PHLX-PHLX"),
    QA_DOHA_SECURITIES_MARKET_DSM("QA-Doha-Securities-Market-DSM"),
    IN_COIMBATORE_STOCK_EXCHANGE("IN-Coimbatore-Stock-Exchange"),
    ID_JAKARTA_ISLAMIC_INDEX_JII("ID-Jakarta-Islamic-Index-JII"),
    NI_BOLSA_DE_VALORES_DE_NICARAGUA_BVDN("NI-Bolsa-de-Valores-de-Nicaragua-BVDN"),
    PE_BOLSA_DE_VALORES_DE_LIMA_MILA_BVL("PE-Bolsa-de-Valores-de-Lima-MILA-BVL"),
    US_IEX_IEX("US-IEX-IEX"),
    IN_BOMBAY_STOCK_EXCHANGE("IN-Bombay-Stock-Exchange"),
    BR_BOLSA_DE_CEREAIS_E_MERCARDORIAS_DE_MARINGA_BCMM("BR-Bolsa-de-Cereais-e-Mercardorias-de-Maringa-BCMM"),
    HR_ZAGREB_STOCK_EXCHANGE_XZAG("HR-Zagreb-Stock-Exchange-XZAG"),
    BA_BANJA_LUKA_STOCK_EXCHANGE_XBLB("BA-Banja-Luka-Stock-Exchange-XBLB"),
    AU_AUSTRALIAN_SECURITIES_EXCHANGE_ASX("AU-Australian-Securities-Exchange-asx"),
    CL_BOLSA_ELECTRONICA_DE_CHILE_BEC("CL-Bolsa-Electronica-de-Chile-Bec"),
    TH_AFET_AFEX("TH-AFET-AFEX"),
    US_CHICAGO_STOCK_EXCHANGE_CHX("US-Chicago-Stock-Exchange-CHX"),
    KR_KOSDAQ_KOSDAQ("KR-KOSDAQ-KOSDAQ"),
    BB_BARBADOS_STOCK_EXCHANGE_BSE("BB-Barbados-Stock-Exchange-BSE"),
    IN_PUNE_STOCK_EXCHANGE("IN-Pune-Stock-Exchange"),
    FI_HELSINKI_STOCK_EXCHANGE_XHEL("FI-Helsinki-Stock-Exchange-XHEL"),
    LA_LAO_SECURITIES_EXCHANGE("LA-Lao-Securities-Exchange"),
    IN_UP_STOCK_EXCHANGE("IN-UP-Stock-Exchange"),
    US_NATIONAL_STOCK_EXCHANGE_NSX("US-National-Stock-Exchange-NSX"),
    TZ_DAR_ES_SALAAM_STOCK_EXCHANGE_DSE("TZ-Dar-es-Salaam-Stock-Exchange-DSE"),
    US_CBOE_STOCK_EXCHANGE_CBOE("US-CBOE-Stock-Exchange-CBOE"),
    PT_EURONEXT_LISBON_XLIS("PT-Euronext-Lisbon-XLIS"),
    SG_SINGAPORE_EXCHANGE_SGX("SG-Singapore-Exchange-SGX"),
    MU_STOCK_EXCHANGE_OF_MAURITIUS_SEM("MU-Stock-Exchange-of-Mauritius-SEM"),
    LK_COLOMBO_STOCK_EXCHANGE_CSE("LK-Colombo-Stock-Exchange-CSE"),
    VE_BOLSA_DE_VALORES_DE_CARACAS_BVC("VE-Bolsa-de-Valores-de-Caracas-BVC"),
    UG_ALTX_EAST_AFRICA_EXCHANGE_ALTX("UG-ALTX-East-Africa-Exchange-ALTX"),
    CA_NASDAQ_CANADA_NASDAQ_CANADA("CA-NASDAQ-Canada-Nasdaq-Canada"),
    SK_BRATISLAVA_STOCK_EXCHANGE_XBRA("SK-Bratislava-Stock-Exchange-XBRA"),
    EE_EURONEXT("EE-Euronext"),
    ZA_JSE_LIMITED_JSE("ZA-JSE-Limited-JSE"),
    IL_TEL_AVIV_STOCK_EXCHANGE_TASE("IL-Tel-Aviv-Stock-Exchange-TASE"),
    BH_BAHRAIN_STOCK_EXCHANGE_BSE("BH-Bahrain-Stock-Exchange-BSE"),
    AZ_BAKU_STOCK_EXCHANGE_BFB("AZ-Baku-Stock-Exchange-BFB"),
    ZM_LUSAKA_STOCK_EXCHANGE_LUSE("ZM-Lusaka-Stock-Exchange-LuSE"),
    BT_ROYAL_SECURITIES_EXCHANGE_OF_BHUTAN_RSEBL("BT-Royal-Securities-Exchange-of-Bhutan-RSEBL"),
    BD_CHITTAGONG_TEA_AUCTION("BD-Chittagong-Tea-Auction"),
    DO_LATIN_AMERICAN_INTERNATIONAL_FINANCIAL_EXCHANGE_LAIFEX("DO-Latin-American-International-Financial-Exchange-LAIFEX"),
    DE_BERLINER_BORSE_XBER("DE-Berliner-Borse-XBER"),
    MZ_BOLSA_DE_VALORES_DE_MOZAMBIQUE_BVM("MZ-Bolsa-de-Valores-de-Mozambique-BVM"),
    ID_JAKARTA_FUTURES_EXCHANGE_JFX("ID-Jakarta-Futures-Exchange-JFX"),
    OTHER("Other"),
    BO_BOLSA_BOLIVIANA_DE_VALORES_BVB("BO-Bolsa-Boliviana-de-Valores-BVB"),
    LY_LIBYAN_STOCK_MARKET_LSM("LY-Libyan-Stock-Market-LSM"),
    FR_ESE_EUROPEAN_STOCK_EXCHANGE_XPAR("FR-ESE-European-Stock-Exchange-XPAR"),
    IN_VADODARA_STOCK_EXCHANGE("IN-Vadodara-Stock-Exchange"),
    MY_BURSA_MALAYSIA_MYX("MY-Bursa-Malaysia-MYX"),
    JM_JAMAICA_STOCK_EXCHANGE_JSE("JM-Jamaica-Stock-Exchange-JSE"),
    VC_EASTERN_CARIBBEAN_SECURITIES_EXCHANGE_ECSE("VC-Eastern-Caribbean-Securities-Exchange-ECSE"),
    EG_EGYPTIAN_EXCHANGE_EGX("EG-Egyptian-Exchange-EGX"),
    LU_LUXEMBOURG_STOCK_EXCHANGE_XLUX("LU-Luxembourg-Stock-Exchange-XLUX"),
    PY_BOLSA_DE_VALORES_Y_PRODUCTOS_DE_ASUNCION_BVPASA("PY-Bolsa-de-Valores-y-Productos-de-Asuncion-BVPASA"),
    MM_MYANMAR_SECURITIES_EXCHANGE_CENTRE_MSEC("MM-Myanmar-Securities-Exchange-Centre-MSEC"),
    LV_RIGA_STOCK_EXCHANGE_XRIS("LV-Riga-Stock-Exchange-XRIS"),
    GY_GUYANA_STOCK_EXCHANGE_GASCI("GY-Guyana-Stock-Exchange-GASCI"),
    JP_FUKUOKA_FSE("JP-Fukuoka-FSE"),
    AZ_BAKU_STOCK_EXCHANGE_BSEX("AZ-Baku-Stock-Exchange-BSEX"),
    GH_GHANA_STOCK_EXCHANGE_GSE("GH-Ghana-Stock-Exchange-GSE"),
    ID_INDONESIA_STOCK_EXCHANGE_IDX("ID-Indonesia-Stock-Exchange-IDX"),
    UA_PFTS_UKRAINE_STOCK_EXCHANGE_PFTS("UA-PFTS-Ukraine-Stock-Exchange-PFTS"),
    US_EDGA_AND_EDGX_EDGA_AND_EDGX("US-EDGA-and-EDGX-EDGA-and-EDGX"),
    EC_BOLSA_DE_VALORES_DE_QUITO_BVQ("EC-Bolsa-de-Valores-de-Quito-BVQ"),
    PH_PHILIPPINE_STOCK_EXCHANGE_PSE("PH-Philippine-Stock-Exchange-PSE"),
    CO_BOLSA_DE_VALORES_DE_COLOMBIA_MILA_BVC("CO-Bolsa-de-Valores-de-Colombia-MILA-BVC"),
    IN_AHMEDABAD_STOCK_EXCHANGE("IN-Ahmedabad-Stock-Exchange"),
    JP_SAPPORO_SECURITIES_EXCHANGE_SSE("JP-Sapporo-Securities-Exchange-SSE"),
    RW_RWANDA_STOCK_EXCHANGE_RSE("RW-Rwanda-Stock-Exchange-RSE"),
    RS_BELGRADE_STOCK_EXCHANGE_XBEL("RS-Belgrade-Stock-Exchange-XBEL"),
    NL_EURONEXT_AMSTERDAM_XAMS("NL-Euronext-Amsterdam-XAMS"),
    IR_TEHRAN_STOCK_EXCHANGE_TSE("IR-Tehran-Stock-Exchange-TSE"),
    HU_BUDAPEST_STOCK_EXCHANGE_XBUD("HU-Budapest-Stock-Exchange-XBUD"),
    IR_IRAN_MERCANTILE_EXCHANGE_IME("IR-Iran-Mercantile-Exchange-IME"),
    IN_MCX_STOCK_EXCHANGE("IN-MCX-Stock-Exchange"),
    PK_KARACHI_STOCK_EXCHANGE("PK-Karachi-Stock-Exchange"),
    PG_PORT_MORESBY_STOCK_EXCHANGE("PG-Port-Moresby-Stock-Exchange"),
    AF_AFGHANISTAN_STOCK_EXCHANGE_AFX("AF-Afghanistan-Stock-Exchange-AFX"),
    IN_MANGALORE_STOCK_EXCHANGE("IN-Mangalore-Stock-Exchange"),
    DE_BOERSE_DUESSELDORF_XDUS("DE-Boerse-Duesseldorf-XDUS"),
    KY_CAYMAN_ISLANDS_STOCK_EXCHANGE_CSX("KY-Cayman-Islands-Stock-Exchange-CSX"),
    HK_HONG_KONG_STOCK_EXCHANGE_SEHK("HK-Hong-Kong-Stock-Exchange-SEHK"),
    AU_APTEX("AU-APTEX"),
    KG_KYRGYZ_STOCK_EXCHANGE_KSE("KG-Kyrgyz-Stock-Exchange-KSE"),
    US_BATS_EXCHANGE_BZX("US-BATS-Exchange-BZX"),
    UY_BOLSA_ELECTRONICA_DE_VALORES_DE_URUGUAY_BEVSA("UY-Bolsa-Electronica-de-Valores-de-Uruguay-BEVSA"),
    VN_HANOI_SECURITIES_TRADING_CENTER_HASTC("VN-Hanoi-Securities-Trading-Center-HASTC"),
    ZW_ZIMBABWE_STOCK_EXCHANGE_ZSE("ZW-Zimbabwe-Stock-Exchange-ZSE"),
    CA_AEQUITAS_NEO_AEQUITAS_NEO("CA-Aequitas-Neo-Aequitas-Neo"),
    IR_IRANIAN_ENERGY_EXCHANGE_IRENEX("IR-Iranian-Energy-Exchange-IRENEX"),
    JP_MOTHERS_MOTHERS("JP-Mothers-Mothers"),
    TW_TAIWAN_STOCK_EXCHANGE_TWSE("TW-Taiwan-Stock-Exchange-TWSE"),
    UA_UKRAINIAN_EXCHANGE_XUAX("UA-Ukrainian-Exchange-XUAX"),
    FJ_SOUTH_PACIFIC_STOCK_EXCHANGE("FJ-South-Pacific-Stock-Exchange"),
    AE_ABU_DHABI_SECURITIES_MARKET_ADSM("AE-Abu-Dhabi-Securities-Market-ADSM"),
    ME_MONTENEGRO_STOCK_EXCHANGE_XMNX("ME-Montenegro-Stock-Exchange-XMNX"),
    BR_BOLSA_DE_VALORES_MINAS_ESPIRITO_SANTO_BRASILIA_BOVMESB("BR-Bolsa-de-Valores-Minas-Espirito-Santo-Brasilia-BOVMESB"),
    US_CHICAGO_BOARD_OPTIONS_EXCHANGE_CBOE("US-Chicago-Board-Options-Exchange-CBOE"),
    AG_EASTERN_CARIBBEAN_SECURITIES_EXCHANGE_ECSE("AG-Eastern-Caribbean-Securities-Exchange-ECSE"),
    GE_GEORGIAN_STOCK_EXCHANGE_SSB("GE-Georgian-Stock-Exchange-SSB"),
    IN_MEERUT_STOCK_EXCHANGE("IN-Meerut-Stock-Exchange"),
    CI_BOURSE_REGIONALE_DES_VALEURS_MOBILIERES_BRVM("CI-Bourse-Regionale-des-Valeurs-Mobilieres-BRVM"),
    IN_JAIPUR_STOCK_EXCHANGE("IN-Jaipur-Stock-Exchange"),
    BR_BM_F_BOVESPA_BOVESPA("BR-BM-F-Bovespa-Bovespa"),
    MN_MONGOLIAN_STOCK_EXCHANGE_MSE("MN-Mongolian-Stock-Exchange-MSE"),
    SY_DAMASCUS_SECURITIES_EXCHANGE_DSE("SY-Damascus-Securities-Exchange-DSE"),
    KE_NAIROBI_SECURITIES_EXCHANGE_NSE("KE-Nairobi-Securities-Exchange-NSE"),
    TT_TRINIDAD_AND_TOBAGO_STOCK_EXCHANGE_TTSE("TT-Trinidad-and-Tobago-Stock-Exchange-TTSE"),
    LC_EASTERN_CARIBBEAN_SECURITIES_EXCHANGE_ECSE("LC-Eastern-Caribbean-Securities-Exchange-ECSE"),
    TH_THAILAND_FUTURES_EXCHANGE_TFEX("TH-Thailand-Futures-Exchange-TFEX"),
    KZ_KAZAKHSTAN_STOCK_EXCHANGE_XKAZ("KZ-Kazakhstan-Stock-Exchange-XKAZ"),
    KR_KOREA_EXCHANGE_KRX("KR-Korea-Exchange-KRX"),
    CR_BOLSA_NACIONAL_DE_VALORES_BNV("CR-Bolsa-Nacional-de-Valores-BNV"),
    GB_LONDON_STOCK_EXCHANGE_XLON("GB-London-Stock-Exchange-XLON"),
    EC_BOLSA_DE_VALORES_DE_GUAYAQUIL_BVG("EC-Bolsa-de-Valores-de-Guayaquil-BVG"),
    FR_MATIF_EURONEXT_XMAT_XPAR("FR-MATIF-Euronext-XMAT-XPAR"),
    AR_MERCADO_ABIERTO_ELECTRONICO_MAE("AR-Mercado-Abierto-Electronico-MAE"),
    MW_MALAWI_STOCK_EXCHANGE_MSE("MW-Malawi-Stock-Exchange-MSE"),
    GI_GIBRALTAR_STOCK_EXCHANGE_GSXL("GI-Gibraltar-Stock-Exchange-GSXL"),
    FR_EURONEXT_PARIS_XPAR("FR-Euronext-Paris-XPAR"),
    NG_ABUJA_SECURITIES_AND_COMMODITIES_EXCHANGE_ASCE("NG-Abuja-Securities-and-Commodities-Exchange-ASCE"),
    TH_BOND_ELECTRONIC_EXCHANGE_BEX("TH-Bond-Electronic-Exchange-BEX"),
    US_NEW_YORK_STOCK_EXCHANGE_NYSE("US-New-York-Stock-Exchange-NYSE"),
    TN_BOURSE_DE_TUNIS_BVMT("TN-Bourse-de-Tunis-BVMT"),
    NG_NIGERIAN_STOCK_EXCHANGE_NSE("NG-Nigerian-Stock-Exchange-NSE"),
    IN_DELHI_STOCK_EXCHANGE_ASSOCIATION("IN-Delhi-Stock-Exchange-Association"),
    DE_BORSE_STUTTGART_XSTU("DE-Borse-Stuttgart-XSTU"),
    GR_ATHENS_STOCK_EXCHANGE_XATH("GR-Athens-Stock-Exchange-XATH"),
    US_NYSE_ARCA_NYSE_ARCA("US-NYSE-Arca-NYSE-Arca"),
    MT_MALTA_STOCK_EXCHANGE_XMAL("MT-Malta-Stock-Exchange-XMAL"),
    CL_VALPARAISO_STOCK_EXCHANGE_BOVALPO("CL-Valparaiso-Stock-Exchange-BOVALPO"),
    IQ_IRAQ_STOCK_EXCHANGE_ISX("IQ-Iraq-Stock-Exchange-ISX"),
    NO_OSLO_STOCK_EXCHANGE_XOSL("NO-Oslo-Stock-Exchange-XOSL"),
    GE_CAUFEX_ELECTRONIC_COMMODITIES_AND_DERIVATIVES_FINANCIAL_EXCHANGE("GE-Caufex-Electronic-Commodities-and-Derivatives-Financial-Exchange"),
    CW_DUTCH_CARIBBEAN_SECURITIES_EXCHANGE_DCSX("CW-Dutch-Caribbean-Securities-Exchange-DCSX"),
    SE_STOCKHOLM_STOCK_EXCHANGE_XSTO("SE-Stockholm-Stock-Exchange-XSTO"),
    BD_DHAKA_STOCK_EXCHANGE_DSE("BD-Dhaka-Stock-Exchange-DSE"),
    CM_DOUALA_STOCK_EXCHANGE_DSX("CM-Douala-Stock-Exchange-DSX"),
    AT_WIENER_BORSE_XWBO("AT-Wiener-Borse-XWBO"),
    IN_HYDERABAD_STOCK_EXCHANGE("IN-Hyderabad-Stock-Exchange"),
    AE_DUBAI_FINANCIAL_MARKET_DFM("AE-Dubai-Financial-Market-DFM"),
    IT_BORSA_ITALIANA_XMIL("IT-Borsa-Italiana-XMIL"),
    GD_EASTERN_CARIBBEAN_SECURITIES_EXCHANGE_ECSE("GD-Eastern-Caribbean-Securities-Exchange-ECSE"),
    HK_HONG_KONG_EXCHANGES_AND_CLEARING_HKEX("HK-Hong-Kong-Exchanges-and-Clearing-HKEx"),
    BY_BELARUSIAN_CURRENCY_AND_STOCK_EXCHANGE_BCSE("BY-Belarusian-Currency-and-Stock-Exchange-BCSE"),
    DE_HAMBURG_STOCK_EXCHANGE_XHAM_XHAN("DE-Hamburg-Stock-Exchange-XHAM-XHAN"),
    UZ_THE_REPUBLICAN_STOCK_EXCHANGE_RSE("UZ-The-Republican-Stock-Exchange-RSE"),
    PS_PALESTINE_SECURITIES_EXCHANGE_PSE("PS-Palestine-Securities-Exchange-PSE"),
    NA_NAMIBIA_STOCK_EXCHANGE_NSX("NA-Namibia-Stock-Exchange-NSX"),
    SI_LJUBLJANA_STOCK_EXCHANGE_XLJU("SI-Ljubljana-Stock-Exchange-XLJU"),
    MD_MOLDOVA_STOCK_EXCHANGE_XMOL("MD-Moldova-Stock-Exchange-XMOL"),
    TR_BORSA_ISTANBUL_ISE("TR-Borsa-Istanbul-ISE"),
    VN_HO_CHI_MINH_STOCK_EXCHANGE_HOSE("VN-Ho-Chi-Minh-Stock-Exchange-HOSE"),
    ES_BOLSA_DE_VALORES_DE_VALENCIA_BMEX("ES-Bolsa-de-Valores-de-Valencia-BMEX"),
    PK_LAHORE_STOCK_EXCHANGE("PK-Lahore-Stock-Exchange"),
    IN_GUWAHATI_STOCK_EXCHANGE("IN-Guwahati-Stock-Exchange"),
    US_NASDAQ_NASDAQ("US-NASDAQ-NASDAQ"),
    LT_VILNIUS_STOCK_EXCHANGE_XLIT("LT-Vilnius-Stock-Exchange-XLIT"),
    BS_BAHAMAS_SECURITIES_EXCHANGE_BISX("BS-Bahamas-Securities-Exchange-BISX");

    private String value;

    StockExchangeNameEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StockExchangeNameEnum fromValue(String input) {
      for (StockExchangeNameEnum b : StockExchangeNameEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("stock_exchange_name")
  private StockExchangeNameEnum stock_exchange_name = null;

  @JsonProperty("stock_exchange_ticker")
  private String stock_exchange_ticker = null;

  public V1customerbeneficiariesCompanyStockExchanges stock_exchange_name(StockExchangeNameEnum stock_exchange_name) {
    this.stock_exchange_name = stock_exchange_name;
    return this;
  }

   /**
   * Get stock_exchange_name
   * @return stock_exchange_name
  **/
  public StockExchangeNameEnum getStockExchangeName() {
    return stock_exchange_name;
  }

  public void setStockExchangeName(StockExchangeNameEnum stock_exchange_name) {
    this.stock_exchange_name = stock_exchange_name;
  }

  public V1customerbeneficiariesCompanyStockExchanges stock_exchange_ticker(String stock_exchange_ticker) {
    this.stock_exchange_ticker = stock_exchange_ticker;
    return this;
  }

   /**
   * Get stock_exchange_ticker
   * @return stock_exchange_ticker
  **/
  public String getStockExchangeTicker() {
    return stock_exchange_ticker;
  }

  public void setStockExchangeTicker(String stock_exchange_ticker) {
    this.stock_exchange_ticker = stock_exchange_ticker;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1customerbeneficiariesCompanyStockExchanges v1customerbeneficiaries_company_stock_exchanges = (V1customerbeneficiariesCompanyStockExchanges) o;
    return Objects.equals(this.stock_exchange_name, v1customerbeneficiaries_company_stock_exchanges.stock_exchange_name) &&
        Objects.equals(this.stock_exchange_ticker, v1customerbeneficiaries_company_stock_exchanges.stock_exchange_ticker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stock_exchange_name, stock_exchange_ticker);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1customerbeneficiariesCompanyStockExchanges {\n");
    
    sb.append("    stock_exchange_name: ").append(toIndentedString(stock_exchange_name)).append("\n");
    sb.append("    stock_exchange_ticker: ").append(toIndentedString(stock_exchange_ticker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
