/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * CardIdSuspendBody
 */

public class CardIdSuspendBody {
  /**
   * Sets the reason why card was suspended
   */
  public enum SuspendReasonEnum {
    CARD_LOST("card-lost");

    private String value;

    SuspendReasonEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SuspendReasonEnum fromValue(String input) {
      for (SuspendReasonEnum b : SuspendReasonEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("suspend_reason")
  private SuspendReasonEnum suspend_reason = null;

  public CardIdSuspendBody suspend_reason(SuspendReasonEnum suspend_reason) {
    this.suspend_reason = suspend_reason;
    return this;
  }

   /**
   * Sets the reason why card was suspended
   * @return suspend_reason
  **/
  public SuspendReasonEnum getSuspendReason() {
    return suspend_reason;
  }

  public void setSuspendReason(SuspendReasonEnum suspend_reason) {
    this.suspend_reason = suspend_reason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardIdSuspendBody card_id_suspend_body = (CardIdSuspendBody) o;
    return Objects.equals(this.suspend_reason, card_id_suspend_body.suspend_reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suspend_reason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardIdSuspendBody {\n");
    
    sb.append("    suspend_reason: ").append(toIndentedString(suspend_reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
