/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * DevcustomertransactionsreceivefullsimulationReceiverAddress
 */

public class DevcustomertransactionsreceivefullsimulationReceiverAddress {
  @JsonProperty("country")
  private String country = null;

  @JsonProperty("lines")
  private String lines = null;

  public DevcustomertransactionsreceivefullsimulationReceiverAddress country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public DevcustomertransactionsreceivefullsimulationReceiverAddress lines(String lines) {
    this.lines = lines;
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  public String getLines() {
    return lines;
  }

  public void setLines(String lines) {
    this.lines = lines;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DevcustomertransactionsreceivefullsimulationReceiverAddress devcustomertransactionsreceivefullsimulation_receiver_address = (DevcustomertransactionsreceivefullsimulationReceiverAddress) o;
    return Objects.equals(this.country, devcustomertransactionsreceivefullsimulation_receiver_address.country) &&
        Objects.equals(this.lines, devcustomertransactionsreceivefullsimulation_receiver_address.lines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, lines);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DevcustomertransactionsreceivefullsimulationReceiverAddress {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
