/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse200106
 */

public class InlineResponse200106 {
  @JsonProperty("debit_mandate_id")
  private String debit_mandate_id = null;

  public InlineResponse200106 debit_mandate_id(String debit_mandate_id) {
    this.debit_mandate_id = debit_mandate_id;
    return this;
  }

   /**
   * Get debit_mandate_id
   * @return debit_mandate_id
  **/
  public String getDebitMandateId() {
    return debit_mandate_id;
  }

  public void setDebitMandateId(String debit_mandate_id) {
    this.debit_mandate_id = debit_mandate_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200106 inline_response_200_106 = (InlineResponse200106) o;
    return Objects.equals(this.debit_mandate_id, inline_response_200_106.debit_mandate_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(debit_mandate_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200106 {\n");
    
    sb.append("    debit_mandate_id: ").append(toIndentedString(debit_mandate_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
