/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.RBSwagger.model.V1customercompliancefirewallrulescomplianceFirewallTypehistoryDatasets;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse200123
 */

public class InlineResponse200123 {
  @JsonProperty("compliance_firewall_rules")
  private String compliance_firewall_rules = null;

  @JsonProperty("firewall_id")
  private String firewall_id = null;

  @JsonProperty("datasets")
  private List<V1customercompliancefirewallrulescomplianceFirewallTypehistoryDatasets> datasets = null;

  public InlineResponse200123 compliance_firewall_rules(String compliance_firewall_rules) {
    this.compliance_firewall_rules = compliance_firewall_rules;
    return this;
  }

   /**
   * Get compliance_firewall_rules
   * @return compliance_firewall_rules
  **/
  public String getComplianceFirewallRules() {
    return compliance_firewall_rules;
  }

  public void setComplianceFirewallRules(String compliance_firewall_rules) {
    this.compliance_firewall_rules = compliance_firewall_rules;
  }

  public InlineResponse200123 firewall_id(String firewall_id) {
    this.firewall_id = firewall_id;
    return this;
  }

   /**
   * Get firewall_id
   * @return firewall_id
  **/
  public String getFirewallId() {
    return firewall_id;
  }

  public void setFirewallId(String firewall_id) {
    this.firewall_id = firewall_id;
  }

  public InlineResponse200123 datasets(List<V1customercompliancefirewallrulescomplianceFirewallTypehistoryDatasets> datasets) {
    this.datasets = datasets;
    return this;
  }

  public InlineResponse200123 addDatasetsItem(V1customercompliancefirewallrulescomplianceFirewallTypehistoryDatasets datasetsItem) {
    if (this.datasets == null) {
      this.datasets = new ArrayList<>();
    }
    this.datasets.add(datasetsItem);
    return this;
  }

   /**
   * Get datasets
   * @return datasets
  **/
  public List<V1customercompliancefirewallrulescomplianceFirewallTypehistoryDatasets> getDatasets() {
    return datasets;
  }

  public void setDatasets(List<V1customercompliancefirewallrulescomplianceFirewallTypehistoryDatasets> datasets) {
    this.datasets = datasets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200123 inline_response_200_123 = (InlineResponse200123) o;
    return Objects.equals(this.compliance_firewall_rules, inline_response_200_123.compliance_firewall_rules) &&
        Objects.equals(this.firewall_id, inline_response_200_123.firewall_id) &&
        Objects.equals(this.datasets, inline_response_200_123.datasets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compliance_firewall_rules, firewall_id, datasets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200123 {\n");
    
    sb.append("    compliance_firewall_rules: ").append(toIndentedString(compliance_firewall_rules)).append("\n");
    sb.append("    firewall_id: ").append(toIndentedString(firewall_id)).append("\n");
    sb.append("    datasets: ").append(toIndentedString(datasets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
