/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.RBSwagger.model.V1customerbeneficiariesDefaultAccount;
/**
 * InlineResponse20088Payee
 */

public class InlineResponse20088Payee {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("account")
  private V1customerbeneficiariesDefaultAccount account = null;

  public InlineResponse20088Payee name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20088Payee account(V1customerbeneficiariesDefaultAccount account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  public V1customerbeneficiariesDefaultAccount getAccount() {
    return account;
  }

  public void setAccount(V1customerbeneficiariesDefaultAccount account) {
    this.account = account;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20088Payee inline_response_200_88_payee = (InlineResponse20088Payee) o;
    return Objects.equals(this.name, inline_response_200_88_payee.name) &&
        Objects.equals(this.account, inline_response_200_88_payee.account);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, account);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20088Payee {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
