/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.RBSwagger.model.DevcustomertransactionsreceivefullsimulationReceiver;
import com.transfer_funds.RBSwagger.model.DevcustomertransactionsreceivefullsimulationReceiverAccount;
import com.transfer_funds.RBSwagger.model.DevcustomertransactionsreceivefullsimulationSenderAgent;
import java.math.BigDecimal;
import java.time.LocalDateTime;
/**
 * V1customertransactionsTransactionInfo
 */

public class V1customertransactionsTransactionInfo {
  @JsonProperty("receiver_account")
  private DevcustomertransactionsreceivefullsimulationReceiverAccount receiver_account = null;

  @JsonProperty("purpose")
  private String purpose = null;

  @JsonProperty("clearing_system")
  private String clearing_system = null;

  @JsonProperty("created_at")
  private LocalDateTime created_at = null;

  @JsonProperty("instructed_agent")
  private DevcustomertransactionsreceivefullsimulationSenderAgent instructed_agent = null;

  @JsonProperty("remittance_information_unstructured")
  private String remittance_information_unstructured = null;

  @JsonProperty("settlement_method")
  private String settlement_method = null;

  @JsonProperty("end_to_end_id")
  private String end_to_end_id = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("transaction_id")
  private String transaction_id = null;

  @JsonProperty("amount")
  private BigDecimal amount = null;

  @JsonProperty("reference_account")
  private DevcustomertransactionsreceivefullsimulationReceiverAccount reference_account = null;

  @JsonProperty("settlement_date")
  private String settlement_date = null;

  @JsonProperty("receiver")
  private DevcustomertransactionsreceivefullsimulationReceiver receiver = null;

  @JsonProperty("service_level")
  private String service_level = null;

  @JsonProperty("ultimate_receiver")
  private DevcustomertransactionsreceivefullsimulationReceiver ultimate_receiver = null;

  @JsonProperty("sender_agent")
  private DevcustomertransactionsreceivefullsimulationSenderAgent sender_agent = null;

  @JsonProperty("message_id")
  private String message_id = null;

  @JsonProperty("clearing_system_proprietary")
  private String clearing_system_proprietary = null;

  @JsonProperty("purpose_category")
  private String purpose_category = null;

  @JsonProperty("instructing_agent")
  private DevcustomertransactionsreceivefullsimulationSenderAgent instructing_agent = null;

  @JsonProperty("local_instrument")
  private String local_instrument = null;

  @JsonProperty("settlement_account")
  private DevcustomertransactionsreceivefullsimulationReceiverAccount settlement_account = null;

  @JsonProperty("ultimate_sender")
  private DevcustomertransactionsreceivefullsimulationReceiver ultimate_sender = null;

  @JsonProperty("sender")
  private DevcustomertransactionsreceivefullsimulationReceiver sender = null;

  @JsonProperty("charge_bearer")
  private String charge_bearer = null;

  @JsonProperty("message_schema")
  private String message_schema = null;

  @JsonProperty("sender_account")
  private DevcustomertransactionsreceivefullsimulationReceiverAccount sender_account = null;

  @JsonProperty("local_instrument_proprietary")
  private String local_instrument_proprietary = null;

  @JsonProperty("receiver_agent")
  private DevcustomertransactionsreceivefullsimulationSenderAgent receiver_agent = null;

  @JsonProperty("purpose_category_proprietary")
  private String purpose_category_proprietary = null;

  @JsonProperty("instruction_id")
  private String instruction_id = null;

  public V1customertransactionsTransactionInfo receiver_account(DevcustomertransactionsreceivefullsimulationReceiverAccount receiver_account) {
    this.receiver_account = receiver_account;
    return this;
  }

   /**
   * Get receiver_account
   * @return receiver_account
  **/
  public DevcustomertransactionsreceivefullsimulationReceiverAccount getReceiverAccount() {
    return receiver_account;
  }

  public void setReceiverAccount(DevcustomertransactionsreceivefullsimulationReceiverAccount receiver_account) {
    this.receiver_account = receiver_account;
  }

  public V1customertransactionsTransactionInfo purpose(String purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * Get purpose
   * @return purpose
  **/
  public String getPurpose() {
    return purpose;
  }

  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }

  public V1customertransactionsTransactionInfo clearing_system(String clearing_system) {
    this.clearing_system = clearing_system;
    return this;
  }

   /**
   * Get clearing_system
   * @return clearing_system
  **/
  public String getClearingSystem() {
    return clearing_system;
  }

  public void setClearingSystem(String clearing_system) {
    this.clearing_system = clearing_system;
  }

  public V1customertransactionsTransactionInfo created_at(LocalDateTime created_at) {
    this.created_at = created_at;
    return this;
  }

   /**
   * Get created_at
   * @return created_at
  **/
  public LocalDateTime getCreatedAt() {
    return created_at;
  }

  public void setCreatedAt(LocalDateTime created_at) {
    this.created_at = created_at;
  }

  public V1customertransactionsTransactionInfo instructed_agent(DevcustomertransactionsreceivefullsimulationSenderAgent instructed_agent) {
    this.instructed_agent = instructed_agent;
    return this;
  }

   /**
   * Get instructed_agent
   * @return instructed_agent
  **/
  public DevcustomertransactionsreceivefullsimulationSenderAgent getInstructedAgent() {
    return instructed_agent;
  }

  public void setInstructedAgent(DevcustomertransactionsreceivefullsimulationSenderAgent instructed_agent) {
    this.instructed_agent = instructed_agent;
  }

  public V1customertransactionsTransactionInfo remittance_information_unstructured(String remittance_information_unstructured) {
    this.remittance_information_unstructured = remittance_information_unstructured;
    return this;
  }

   /**
   * Get remittance_information_unstructured
   * @return remittance_information_unstructured
  **/
  public String getRemittanceInformationUnstructured() {
    return remittance_information_unstructured;
  }

  public void setRemittanceInformationUnstructured(String remittance_information_unstructured) {
    this.remittance_information_unstructured = remittance_information_unstructured;
  }

  public V1customertransactionsTransactionInfo settlement_method(String settlement_method) {
    this.settlement_method = settlement_method;
    return this;
  }

   /**
   * Get settlement_method
   * @return settlement_method
  **/
  public String getSettlementMethod() {
    return settlement_method;
  }

  public void setSettlementMethod(String settlement_method) {
    this.settlement_method = settlement_method;
  }

  public V1customertransactionsTransactionInfo end_to_end_id(String end_to_end_id) {
    this.end_to_end_id = end_to_end_id;
    return this;
  }

   /**
   * Get end_to_end_id
   * @return end_to_end_id
  **/
  public String getEndToEndId() {
    return end_to_end_id;
  }

  public void setEndToEndId(String end_to_end_id) {
    this.end_to_end_id = end_to_end_id;
  }

  public V1customertransactionsTransactionInfo currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public V1customertransactionsTransactionInfo transaction_id(String transaction_id) {
    this.transaction_id = transaction_id;
    return this;
  }

   /**
   * Get transaction_id
   * @return transaction_id
  **/
  public String getTransactionId() {
    return transaction_id;
  }

  public void setTransactionId(String transaction_id) {
    this.transaction_id = transaction_id;
  }

  public V1customertransactionsTransactionInfo amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public V1customertransactionsTransactionInfo reference_account(DevcustomertransactionsreceivefullsimulationReceiverAccount reference_account) {
    this.reference_account = reference_account;
    return this;
  }

   /**
   * Get reference_account
   * @return reference_account
  **/
  public DevcustomertransactionsreceivefullsimulationReceiverAccount getReferenceAccount() {
    return reference_account;
  }

  public void setReferenceAccount(DevcustomertransactionsreceivefullsimulationReceiverAccount reference_account) {
    this.reference_account = reference_account;
  }

  public V1customertransactionsTransactionInfo settlement_date(String settlement_date) {
    this.settlement_date = settlement_date;
    return this;
  }

   /**
   * Get settlement_date
   * @return settlement_date
  **/
  public String getSettlementDate() {
    return settlement_date;
  }

  public void setSettlementDate(String settlement_date) {
    this.settlement_date = settlement_date;
  }

  public V1customertransactionsTransactionInfo receiver(DevcustomertransactionsreceivefullsimulationReceiver receiver) {
    this.receiver = receiver;
    return this;
  }

   /**
   * Get receiver
   * @return receiver
  **/
  public DevcustomertransactionsreceivefullsimulationReceiver getReceiver() {
    return receiver;
  }

  public void setReceiver(DevcustomertransactionsreceivefullsimulationReceiver receiver) {
    this.receiver = receiver;
  }

  public V1customertransactionsTransactionInfo service_level(String service_level) {
    this.service_level = service_level;
    return this;
  }

   /**
   * Get service_level
   * @return service_level
  **/
  public String getServiceLevel() {
    return service_level;
  }

  public void setServiceLevel(String service_level) {
    this.service_level = service_level;
  }

  public V1customertransactionsTransactionInfo ultimate_receiver(DevcustomertransactionsreceivefullsimulationReceiver ultimate_receiver) {
    this.ultimate_receiver = ultimate_receiver;
    return this;
  }

   /**
   * Get ultimate_receiver
   * @return ultimate_receiver
  **/
  public DevcustomertransactionsreceivefullsimulationReceiver getUltimateReceiver() {
    return ultimate_receiver;
  }

  public void setUltimateReceiver(DevcustomertransactionsreceivefullsimulationReceiver ultimate_receiver) {
    this.ultimate_receiver = ultimate_receiver;
  }

  public V1customertransactionsTransactionInfo sender_agent(DevcustomertransactionsreceivefullsimulationSenderAgent sender_agent) {
    this.sender_agent = sender_agent;
    return this;
  }

   /**
   * Get sender_agent
   * @return sender_agent
  **/
  public DevcustomertransactionsreceivefullsimulationSenderAgent getSenderAgent() {
    return sender_agent;
  }

  public void setSenderAgent(DevcustomertransactionsreceivefullsimulationSenderAgent sender_agent) {
    this.sender_agent = sender_agent;
  }

  public V1customertransactionsTransactionInfo message_id(String message_id) {
    this.message_id = message_id;
    return this;
  }

   /**
   * Get message_id
   * @return message_id
  **/
  public String getMessageId() {
    return message_id;
  }

  public void setMessageId(String message_id) {
    this.message_id = message_id;
  }

  public V1customertransactionsTransactionInfo clearing_system_proprietary(String clearing_system_proprietary) {
    this.clearing_system_proprietary = clearing_system_proprietary;
    return this;
  }

   /**
   * Get clearing_system_proprietary
   * @return clearing_system_proprietary
  **/
  public String getClearingSystemProprietary() {
    return clearing_system_proprietary;
  }

  public void setClearingSystemProprietary(String clearing_system_proprietary) {
    this.clearing_system_proprietary = clearing_system_proprietary;
  }

  public V1customertransactionsTransactionInfo purpose_category(String purpose_category) {
    this.purpose_category = purpose_category;
    return this;
  }

   /**
   * Get purpose_category
   * @return purpose_category
  **/
  public String getPurposeCategory() {
    return purpose_category;
  }

  public void setPurposeCategory(String purpose_category) {
    this.purpose_category = purpose_category;
  }

  public V1customertransactionsTransactionInfo instructing_agent(DevcustomertransactionsreceivefullsimulationSenderAgent instructing_agent) {
    this.instructing_agent = instructing_agent;
    return this;
  }

   /**
   * Get instructing_agent
   * @return instructing_agent
  **/
  public DevcustomertransactionsreceivefullsimulationSenderAgent getInstructingAgent() {
    return instructing_agent;
  }

  public void setInstructingAgent(DevcustomertransactionsreceivefullsimulationSenderAgent instructing_agent) {
    this.instructing_agent = instructing_agent;
  }

  public V1customertransactionsTransactionInfo local_instrument(String local_instrument) {
    this.local_instrument = local_instrument;
    return this;
  }

   /**
   * Get local_instrument
   * @return local_instrument
  **/
  public String getLocalInstrument() {
    return local_instrument;
  }

  public void setLocalInstrument(String local_instrument) {
    this.local_instrument = local_instrument;
  }

  public V1customertransactionsTransactionInfo settlement_account(DevcustomertransactionsreceivefullsimulationReceiverAccount settlement_account) {
    this.settlement_account = settlement_account;
    return this;
  }

   /**
   * Get settlement_account
   * @return settlement_account
  **/
  public DevcustomertransactionsreceivefullsimulationReceiverAccount getSettlementAccount() {
    return settlement_account;
  }

  public void setSettlementAccount(DevcustomertransactionsreceivefullsimulationReceiverAccount settlement_account) {
    this.settlement_account = settlement_account;
  }

  public V1customertransactionsTransactionInfo ultimate_sender(DevcustomertransactionsreceivefullsimulationReceiver ultimate_sender) {
    this.ultimate_sender = ultimate_sender;
    return this;
  }

   /**
   * Get ultimate_sender
   * @return ultimate_sender
  **/
  public DevcustomertransactionsreceivefullsimulationReceiver getUltimateSender() {
    return ultimate_sender;
  }

  public void setUltimateSender(DevcustomertransactionsreceivefullsimulationReceiver ultimate_sender) {
    this.ultimate_sender = ultimate_sender;
  }

  public V1customertransactionsTransactionInfo sender(DevcustomertransactionsreceivefullsimulationReceiver sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public DevcustomertransactionsreceivefullsimulationReceiver getSender() {
    return sender;
  }

  public void setSender(DevcustomertransactionsreceivefullsimulationReceiver sender) {
    this.sender = sender;
  }

  public V1customertransactionsTransactionInfo charge_bearer(String charge_bearer) {
    this.charge_bearer = charge_bearer;
    return this;
  }

   /**
   * Get charge_bearer
   * @return charge_bearer
  **/
  public String getChargeBearer() {
    return charge_bearer;
  }

  public void setChargeBearer(String charge_bearer) {
    this.charge_bearer = charge_bearer;
  }

  public V1customertransactionsTransactionInfo message_schema(String message_schema) {
    this.message_schema = message_schema;
    return this;
  }

   /**
   * Get message_schema
   * @return message_schema
  **/
  public String getMessageSchema() {
    return message_schema;
  }

  public void setMessageSchema(String message_schema) {
    this.message_schema = message_schema;
  }

  public V1customertransactionsTransactionInfo sender_account(DevcustomertransactionsreceivefullsimulationReceiverAccount sender_account) {
    this.sender_account = sender_account;
    return this;
  }

   /**
   * Get sender_account
   * @return sender_account
  **/
  public DevcustomertransactionsreceivefullsimulationReceiverAccount getSenderAccount() {
    return sender_account;
  }

  public void setSenderAccount(DevcustomertransactionsreceivefullsimulationReceiverAccount sender_account) {
    this.sender_account = sender_account;
  }

  public V1customertransactionsTransactionInfo local_instrument_proprietary(String local_instrument_proprietary) {
    this.local_instrument_proprietary = local_instrument_proprietary;
    return this;
  }

   /**
   * Get local_instrument_proprietary
   * @return local_instrument_proprietary
  **/
  public String getLocalInstrumentProprietary() {
    return local_instrument_proprietary;
  }

  public void setLocalInstrumentProprietary(String local_instrument_proprietary) {
    this.local_instrument_proprietary = local_instrument_proprietary;
  }

  public V1customertransactionsTransactionInfo receiver_agent(DevcustomertransactionsreceivefullsimulationSenderAgent receiver_agent) {
    this.receiver_agent = receiver_agent;
    return this;
  }

   /**
   * Get receiver_agent
   * @return receiver_agent
  **/
  public DevcustomertransactionsreceivefullsimulationSenderAgent getReceiverAgent() {
    return receiver_agent;
  }

  public void setReceiverAgent(DevcustomertransactionsreceivefullsimulationSenderAgent receiver_agent) {
    this.receiver_agent = receiver_agent;
  }

  public V1customertransactionsTransactionInfo purpose_category_proprietary(String purpose_category_proprietary) {
    this.purpose_category_proprietary = purpose_category_proprietary;
    return this;
  }

   /**
   * Get purpose_category_proprietary
   * @return purpose_category_proprietary
  **/
  public String getPurposeCategoryProprietary() {
    return purpose_category_proprietary;
  }

  public void setPurposeCategoryProprietary(String purpose_category_proprietary) {
    this.purpose_category_proprietary = purpose_category_proprietary;
  }

  public V1customertransactionsTransactionInfo instruction_id(String instruction_id) {
    this.instruction_id = instruction_id;
    return this;
  }

   /**
   * Get instruction_id
   * @return instruction_id
  **/
  public String getInstructionId() {
    return instruction_id;
  }

  public void setInstructionId(String instruction_id) {
    this.instruction_id = instruction_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1customertransactionsTransactionInfo v1customertransactions_transaction_info = (V1customertransactionsTransactionInfo) o;
    return Objects.equals(this.receiver_account, v1customertransactions_transaction_info.receiver_account) &&
        Objects.equals(this.purpose, v1customertransactions_transaction_info.purpose) &&
        Objects.equals(this.clearing_system, v1customertransactions_transaction_info.clearing_system) &&
        Objects.equals(this.created_at, v1customertransactions_transaction_info.created_at) &&
        Objects.equals(this.instructed_agent, v1customertransactions_transaction_info.instructed_agent) &&
        Objects.equals(this.remittance_information_unstructured, v1customertransactions_transaction_info.remittance_information_unstructured) &&
        Objects.equals(this.settlement_method, v1customertransactions_transaction_info.settlement_method) &&
        Objects.equals(this.end_to_end_id, v1customertransactions_transaction_info.end_to_end_id) &&
        Objects.equals(this.currency, v1customertransactions_transaction_info.currency) &&
        Objects.equals(this.transaction_id, v1customertransactions_transaction_info.transaction_id) &&
        Objects.equals(this.amount, v1customertransactions_transaction_info.amount) &&
        Objects.equals(this.reference_account, v1customertransactions_transaction_info.reference_account) &&
        Objects.equals(this.settlement_date, v1customertransactions_transaction_info.settlement_date) &&
        Objects.equals(this.receiver, v1customertransactions_transaction_info.receiver) &&
        Objects.equals(this.service_level, v1customertransactions_transaction_info.service_level) &&
        Objects.equals(this.ultimate_receiver, v1customertransactions_transaction_info.ultimate_receiver) &&
        Objects.equals(this.sender_agent, v1customertransactions_transaction_info.sender_agent) &&
        Objects.equals(this.message_id, v1customertransactions_transaction_info.message_id) &&
        Objects.equals(this.clearing_system_proprietary, v1customertransactions_transaction_info.clearing_system_proprietary) &&
        Objects.equals(this.purpose_category, v1customertransactions_transaction_info.purpose_category) &&
        Objects.equals(this.instructing_agent, v1customertransactions_transaction_info.instructing_agent) &&
        Objects.equals(this.local_instrument, v1customertransactions_transaction_info.local_instrument) &&
        Objects.equals(this.settlement_account, v1customertransactions_transaction_info.settlement_account) &&
        Objects.equals(this.ultimate_sender, v1customertransactions_transaction_info.ultimate_sender) &&
        Objects.equals(this.sender, v1customertransactions_transaction_info.sender) &&
        Objects.equals(this.charge_bearer, v1customertransactions_transaction_info.charge_bearer) &&
        Objects.equals(this.message_schema, v1customertransactions_transaction_info.message_schema) &&
        Objects.equals(this.sender_account, v1customertransactions_transaction_info.sender_account) &&
        Objects.equals(this.local_instrument_proprietary, v1customertransactions_transaction_info.local_instrument_proprietary) &&
        Objects.equals(this.receiver_agent, v1customertransactions_transaction_info.receiver_agent) &&
        Objects.equals(this.purpose_category_proprietary, v1customertransactions_transaction_info.purpose_category_proprietary) &&
        Objects.equals(this.instruction_id, v1customertransactions_transaction_info.instruction_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiver_account, purpose, clearing_system, created_at, instructed_agent, remittance_information_unstructured, settlement_method, end_to_end_id, currency, transaction_id, amount, reference_account, settlement_date, receiver, service_level, ultimate_receiver, sender_agent, message_id, clearing_system_proprietary, purpose_category, instructing_agent, local_instrument, settlement_account, ultimate_sender, sender, charge_bearer, message_schema, sender_account, local_instrument_proprietary, receiver_agent, purpose_category_proprietary, instruction_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1customertransactionsTransactionInfo {\n");
    
    sb.append("    receiver_account: ").append(toIndentedString(receiver_account)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    clearing_system: ").append(toIndentedString(clearing_system)).append("\n");
    sb.append("    created_at: ").append(toIndentedString(created_at)).append("\n");
    sb.append("    instructed_agent: ").append(toIndentedString(instructed_agent)).append("\n");
    sb.append("    remittance_information_unstructured: ").append(toIndentedString(remittance_information_unstructured)).append("\n");
    sb.append("    settlement_method: ").append(toIndentedString(settlement_method)).append("\n");
    sb.append("    end_to_end_id: ").append(toIndentedString(end_to_end_id)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    transaction_id: ").append(toIndentedString(transaction_id)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    reference_account: ").append(toIndentedString(reference_account)).append("\n");
    sb.append("    settlement_date: ").append(toIndentedString(settlement_date)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    service_level: ").append(toIndentedString(service_level)).append("\n");
    sb.append("    ultimate_receiver: ").append(toIndentedString(ultimate_receiver)).append("\n");
    sb.append("    sender_agent: ").append(toIndentedString(sender_agent)).append("\n");
    sb.append("    message_id: ").append(toIndentedString(message_id)).append("\n");
    sb.append("    clearing_system_proprietary: ").append(toIndentedString(clearing_system_proprietary)).append("\n");
    sb.append("    purpose_category: ").append(toIndentedString(purpose_category)).append("\n");
    sb.append("    instructing_agent: ").append(toIndentedString(instructing_agent)).append("\n");
    sb.append("    local_instrument: ").append(toIndentedString(local_instrument)).append("\n");
    sb.append("    settlement_account: ").append(toIndentedString(settlement_account)).append("\n");
    sb.append("    ultimate_sender: ").append(toIndentedString(ultimate_sender)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    charge_bearer: ").append(toIndentedString(charge_bearer)).append("\n");
    sb.append("    message_schema: ").append(toIndentedString(message_schema)).append("\n");
    sb.append("    sender_account: ").append(toIndentedString(sender_account)).append("\n");
    sb.append("    local_instrument_proprietary: ").append(toIndentedString(local_instrument_proprietary)).append("\n");
    sb.append("    receiver_agent: ").append(toIndentedString(receiver_agent)).append("\n");
    sb.append("    purpose_category_proprietary: ").append(toIndentedString(purpose_category_proprietary)).append("\n");
    sb.append("    instruction_id: ").append(toIndentedString(instruction_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
