/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.RBSwagger.model.V1customerbeneficiariesCompany1;
import com.transfer_funds.RBSwagger.model.V1customerendusersenduserIdPerson;
/**
 * CustomerEndusersBody
 */

public class CustomerEndusersBody {
  @JsonProperty("person")
  private V1customerendusersenduserIdPerson person = null;

  @JsonProperty("company")
  private V1customerbeneficiariesCompany1 company = null;

  @JsonProperty("enduser_meta")
  private Object enduser_meta = null;

  public CustomerEndusersBody person(V1customerendusersenduserIdPerson person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public V1customerendusersenduserIdPerson getPerson() {
    return person;
  }

  public void setPerson(V1customerendusersenduserIdPerson person) {
    this.person = person;
  }

  public CustomerEndusersBody company(V1customerbeneficiariesCompany1 company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  public V1customerbeneficiariesCompany1 getCompany() {
    return company;
  }

  public void setCompany(V1customerbeneficiariesCompany1 company) {
    this.company = company;
  }

  public CustomerEndusersBody enduser_meta(Object enduser_meta) {
    this.enduser_meta = enduser_meta;
    return this;
  }

   /**
   * Get enduser_meta
   * @return enduser_meta
  **/
  public Object getEnduserMeta() {
    return enduser_meta;
  }

  public void setEnduserMeta(Object enduser_meta) {
    this.enduser_meta = enduser_meta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerEndusersBody customer_endusers_body = (CustomerEndusersBody) o;
    return Objects.equals(this.person, customer_endusers_body.person) &&
        Objects.equals(this.company, customer_endusers_body.company) &&
        Objects.equals(this.enduser_meta, customer_endusers_body.enduser_meta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, company, enduser_meta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerEndusersBody {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    enduser_meta: ").append(toIndentedString(enduser_meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
