/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse200122
 */

public class InlineResponse200122 {
  @JsonProperty("webhook_url")
  private String webhook_url = null;

  @JsonProperty("webhook_secret")
  private String webhook_secret = null;

  public InlineResponse200122 webhook_url(String webhook_url) {
    this.webhook_url = webhook_url;
    return this;
  }

   /**
   * Get webhook_url
   * @return webhook_url
  **/
  public String getWebhookUrl() {
    return webhook_url;
  }

  public void setWebhookUrl(String webhook_url) {
    this.webhook_url = webhook_url;
  }

  public InlineResponse200122 webhook_secret(String webhook_secret) {
    this.webhook_secret = webhook_secret;
    return this;
  }

   /**
   * Get webhook_secret
   * @return webhook_secret
  **/
  public String getWebhookSecret() {
    return webhook_secret;
  }

  public void setWebhookSecret(String webhook_secret) {
    this.webhook_secret = webhook_secret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200122 inline_response_200_122 = (InlineResponse200122) o;
    return Objects.equals(this.webhook_url, inline_response_200_122.webhook_url) &&
        Objects.equals(this.webhook_secret, inline_response_200_122.webhook_secret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webhook_url, webhook_secret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200122 {\n");
    
    sb.append("    webhook_url: ").append(toIndentedString(webhook_url)).append("\n");
    sb.append("    webhook_secret: ").append(toIndentedString(webhook_secret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
