/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.RBSwagger.model.InlineResponse20088Payee;
import java.time.LocalDateTime;
/**
 * InlineResponse20088
 */

public class InlineResponse20088 {
  @JsonProperty("payee")
  private InlineResponse20088Payee payee = null;

  @JsonProperty("reference")
  private String reference = null;

  @JsonProperty("holder_id")
  private String holder_id = null;

  @JsonProperty("created_at")
  private LocalDateTime created_at = null;

  @JsonProperty("mandate_id")
  private String mandate_id = null;

  @JsonProperty("ledger_id")
  private String ledger_id = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    REJECTING("mandate-status-rejecting"),
    ACTIVE("mandate-status-active"),
    CANCELLING("mandate-status-cancelling"),
    PENDING("mandate-status-pending"),
    CANCELLED("mandate-status-cancelled"),
    REJECTED("mandate-status-rejected");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  public InlineResponse20088 payee(InlineResponse20088Payee payee) {
    this.payee = payee;
    return this;
  }

   /**
   * Get payee
   * @return payee
  **/
  public InlineResponse20088Payee getPayee() {
    return payee;
  }

  public void setPayee(InlineResponse20088Payee payee) {
    this.payee = payee;
  }

  public InlineResponse20088 reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public InlineResponse20088 holder_id(String holder_id) {
    this.holder_id = holder_id;
    return this;
  }

   /**
   * Get holder_id
   * @return holder_id
  **/
  public String getHolderId() {
    return holder_id;
  }

  public void setHolderId(String holder_id) {
    this.holder_id = holder_id;
  }

  public InlineResponse20088 created_at(LocalDateTime created_at) {
    this.created_at = created_at;
    return this;
  }

   /**
   * Get created_at
   * @return created_at
  **/
  public LocalDateTime getCreatedAt() {
    return created_at;
  }

  public void setCreatedAt(LocalDateTime created_at) {
    this.created_at = created_at;
  }

  public InlineResponse20088 mandate_id(String mandate_id) {
    this.mandate_id = mandate_id;
    return this;
  }

   /**
   * Get mandate_id
   * @return mandate_id
  **/
  public String getMandateId() {
    return mandate_id;
  }

  public void setMandateId(String mandate_id) {
    this.mandate_id = mandate_id;
  }

  public InlineResponse20088 ledger_id(String ledger_id) {
    this.ledger_id = ledger_id;
    return this;
  }

   /**
   * Get ledger_id
   * @return ledger_id
  **/
  public String getLedgerId() {
    return ledger_id;
  }

  public void setLedgerId(String ledger_id) {
    this.ledger_id = ledger_id;
  }

  public InlineResponse20088 status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20088 inline_response_200_88 = (InlineResponse20088) o;
    return Objects.equals(this.payee, inline_response_200_88.payee) &&
        Objects.equals(this.reference, inline_response_200_88.reference) &&
        Objects.equals(this.holder_id, inline_response_200_88.holder_id) &&
        Objects.equals(this.created_at, inline_response_200_88.created_at) &&
        Objects.equals(this.mandate_id, inline_response_200_88.mandate_id) &&
        Objects.equals(this.ledger_id, inline_response_200_88.ledger_id) &&
        Objects.equals(this.status, inline_response_200_88.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payee, reference, holder_id, created_at, mandate_id, ledger_id, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20088 {\n");
    
    sb.append("    payee: ").append(toIndentedString(payee)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    holder_id: ").append(toIndentedString(holder_id)).append("\n");
    sb.append("    created_at: ").append(toIndentedString(created_at)).append("\n");
    sb.append("    mandate_id: ").append(toIndentedString(mandate_id)).append("\n");
    sb.append("    ledger_id: ").append(toIndentedString(ledger_id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
