/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ProductsPartnerProductBody
 */

public class ProductsPartnerProductBody {
  @JsonProperty("api_key")
  private String api_key = null;

  @JsonProperty("client_id")
  private String client_id = null;

  public ProductsPartnerProductBody api_key(String api_key) {
    this.api_key = api_key;
    return this;
  }

   /**
   * Get api_key
   * @return api_key
  **/
  public String getApiKey() {
    return api_key;
  }

  public void setApiKey(String api_key) {
    this.api_key = api_key;
  }

  public ProductsPartnerProductBody client_id(String client_id) {
    this.client_id = client_id;
    return this;
  }

   /**
   * Get client_id
   * @return client_id
  **/
  public String getClientId() {
    return client_id;
  }

  public void setClientId(String client_id) {
    this.client_id = client_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductsPartnerProductBody products_partner_product_body = (ProductsPartnerProductBody) o;
    return Objects.equals(this.api_key, products_partner_product_body.api_key) &&
        Objects.equals(this.client_id, products_partner_product_body.client_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(api_key, client_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductsPartnerProductBody {\n");
    
    sb.append("    api_key: ").append(toIndentedString(api_key)).append("\n");
    sb.append("    client_id: ").append(toIndentedString(client_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
