/*
 * Railsbank customer API
 * Public API for Railsbank customers
 *
 * OpenAPI spec version: api
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.transfer_funds.RBSwagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.transfer_funds.RBSwagger.model.DevcustomertransactionsreceivefullsimulationReceiver;
import com.transfer_funds.RBSwagger.model.DevcustomertransactionsreceivefullsimulationReceiverAccount;
import com.transfer_funds.RBSwagger.model.DevcustomertransactionsreceivefullsimulationSenderAgent;
import java.math.BigDecimal;
/**
 * ReceiveFullsimulationBody
 */

public class ReceiveFullsimulationBody {
  @JsonProperty("transaction_id")
  private String transaction_id = null;

  @JsonProperty("amount")
  private BigDecimal amount = null;

  @JsonProperty("settlement_date")
  private String settlement_date = null;

  @JsonProperty("receiver")
  private DevcustomertransactionsreceivefullsimulationReceiver receiver = null;

  @JsonProperty("receiver_account")
  private DevcustomertransactionsreceivefullsimulationReceiverAccount receiver_account = null;

  @JsonProperty("purpose")
  private String purpose = null;

  /**
   * Gets or Sets asset_class
   */
  public enum AssetClassEnum {
    COMMODITY("commodity"),
    CURRENCY("currency");

    private String value;

    AssetClassEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AssetClassEnum fromValue(String input) {
      for (AssetClassEnum b : AssetClassEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("asset_class")
  private AssetClassEnum asset_class = null;

  @JsonProperty("sender_agent")
  private DevcustomertransactionsreceivefullsimulationSenderAgent sender_agent = null;

  @JsonProperty("message_id")
  private String message_id = null;

  @JsonProperty("purpose_category")
  private String purpose_category = null;

  @JsonProperty("instructing_agent")
  private DevcustomertransactionsreceivefullsimulationSenderAgent instructing_agent = null;

  /**
   * Gets or Sets partner_product
   */
  public enum PartnerProductEnum {
    EXAMPLEBANK_SGD_2("ExampleBank-SGD-2"),
    PAYRNET_SGD_2("PayrNet-SGD-2"),
    BANKING_AUD_1("Banking-AUD-1"),
    PAYRNET_SGD_1("PayrNet-SGD-1"),
    EXAMPLEBANK_SGD_1("ExampleBank-SGD-1"),
    PAYRNET_GBP_DEBIT_SEND("PayrNet-GBP-Debit-Send"),
    PAYRNET_GBP_2("PayrNet-GBP-2"),
    EXAMPLEBANK_USD_1("ExampleBank-USD-1"),
    RAILSBANK_KYC_4("Railsbank-KYC-4"),
    EXAMPLEBANK_AUD_1("ExampleBank-AUD-1"),
    EXAMPLEBANK_FX_1("ExampleBank-FX-1"),
    PAYRNET_USD_1("PayrNet-USD-1"),
    EXAMPLEBANK_USD_2("ExampleBank-USD-2"),
    EXAMPLEBANK_EUR_3("ExampleBank-EUR-3"),
    RAILSBANK_KYC_1("Railsbank-KYC-1"),
    EXAMPLEBANK_GBP_2("ExampleBank-GBP-2"),
    PAYRNET_MULTI_CCY_1("PayrNet-Multi-CCY-1"),
    RAILSBANK_CREDIT_CARD_1("Railsbank-Credit-Card-1"),
    GOLDBLOC_CONVERSION_1("Goldbloc-Conversion-1"),
    RAILSBANK_AML_SCREENING_1("Railsbank-AML-Screening-1"),
    PAYRNET_EUR_3("PayrNet-EUR-3"),
    RAILSBANK_USD_CREDIT_1("Railsbank-USD-Credit-1"),
    ONFIDO_IDV_1("Onfido-IDV-1"),
    EXAMPLEBANK_EUR_1("ExampleBank-EUR-1"),
    PAYRNET_USD_2("PayrNet-USD-2"),
    RAILSBANK_DEBIT_CARD_3("Railsbank-Debit-Card-3"),
    PAYRNET_EUR_1("PayrNet-EUR-1"),
    RAILSBANK_CONVERSION_1("Railsbank-Conversion-1"),
    PAYRNET_GBP_1("PayrNet-GBP-1"),
    RAILSBANK_DEBIT_CARD_1("Railsbank-Debit-Card-1"),
    RAILSBANK_VIRTUAL_1("Railsbank-Virtual-1"),
    RAILSBANK_KYC_2("Railsbank-KYC-2"),
    EXAMPLEBANK_USD_CREDIT_1("ExampleBank-USD-Credit-1"),
    EXAMPLEBANK_GBP_DEBIT_SEND("ExampleBank-GBP-Debit-Send"),
    EXAMPLEBANK_GBP_1("ExampleBank-GBP-1"),
    RAILSBANK_IDENTITY_AND_VERIFICATION_SERVICE_1("Railsbank-Identity-and-Verification-Service-1"),
    RAILSBANK_DEBIT_CARD_2("Railsbank-Debit-Card-2"),
    PAYRNET_FX_1("PayrNet-FX-1");

    private String value;

    PartnerProductEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PartnerProductEnum fromValue(String input) {
      for (PartnerProductEnum b : PartnerProductEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("partner_product")
  private PartnerProductEnum partner_product = null;

  @JsonProperty("instructed_agent")
  private DevcustomertransactionsreceivefullsimulationSenderAgent instructed_agent = null;

  @JsonProperty("remittance_information_unstructured")
  private String remittance_information_unstructured = null;

  @JsonProperty("reference")
  private String reference = null;

  @JsonProperty("sender")
  private DevcustomertransactionsreceivefullsimulationReceiver sender = null;

  @JsonProperty("end_to_end_id")
  private String end_to_end_id = null;

  @JsonProperty("message_schema")
  private String message_schema = null;

  @JsonProperty("sender_account")
  private DevcustomertransactionsreceivefullsimulationReceiverAccount sender_account = null;

  /**
   * Gets or Sets asset_type
   */
  public enum AssetTypeEnum {
    PLN("pln"),
    AUD("aud"),
    CHF("chf"),
    CAD("cad"),
    SEK("sek"),
    GOLDBLOC("goldbloc"),
    USD("usd"),
    NOK("nok"),
    WHISKY("whisky"),
    VIRTUAL_CURRENCY("virtual-currency"),
    JPY("jpy"),
    HUF("huf"),
    NZD("nzd"),
    GOLD("gold"),
    CZK("czk"),
    SGD("sgd"),
    RON("ron"),
    GBP("gbp"),
    HRK("hrk"),
    EUR("eur");

    private String value;

    AssetTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AssetTypeEnum fromValue(String input) {
      for (AssetTypeEnum b : AssetTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("asset_type")
  private AssetTypeEnum asset_type = null;

  @JsonProperty("receiver_agent")
  private DevcustomertransactionsreceivefullsimulationSenderAgent receiver_agent = null;

  public ReceiveFullsimulationBody transaction_id(String transaction_id) {
    this.transaction_id = transaction_id;
    return this;
  }

   /**
   * Get transaction_id
   * @return transaction_id
  **/
  public String getTransactionId() {
    return transaction_id;
  }

  public void setTransactionId(String transaction_id) {
    this.transaction_id = transaction_id;
  }

  public ReceiveFullsimulationBody amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public ReceiveFullsimulationBody settlement_date(String settlement_date) {
    this.settlement_date = settlement_date;
    return this;
  }

   /**
   * Get settlement_date
   * @return settlement_date
  **/
  public String getSettlementDate() {
    return settlement_date;
  }

  public void setSettlementDate(String settlement_date) {
    this.settlement_date = settlement_date;
  }

  public ReceiveFullsimulationBody receiver(DevcustomertransactionsreceivefullsimulationReceiver receiver) {
    this.receiver = receiver;
    return this;
  }

   /**
   * Get receiver
   * @return receiver
  **/
  public DevcustomertransactionsreceivefullsimulationReceiver getReceiver() {
    return receiver;
  }

  public void setReceiver(DevcustomertransactionsreceivefullsimulationReceiver receiver) {
    this.receiver = receiver;
  }

  public ReceiveFullsimulationBody receiver_account(DevcustomertransactionsreceivefullsimulationReceiverAccount receiver_account) {
    this.receiver_account = receiver_account;
    return this;
  }

   /**
   * Get receiver_account
   * @return receiver_account
  **/
  public DevcustomertransactionsreceivefullsimulationReceiverAccount getReceiverAccount() {
    return receiver_account;
  }

  public void setReceiverAccount(DevcustomertransactionsreceivefullsimulationReceiverAccount receiver_account) {
    this.receiver_account = receiver_account;
  }

  public ReceiveFullsimulationBody purpose(String purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * Get purpose
   * @return purpose
  **/
  public String getPurpose() {
    return purpose;
  }

  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }

  public ReceiveFullsimulationBody asset_class(AssetClassEnum asset_class) {
    this.asset_class = asset_class;
    return this;
  }

   /**
   * Get asset_class
   * @return asset_class
  **/
  public AssetClassEnum getAssetClass() {
    return asset_class;
  }

  public void setAssetClass(AssetClassEnum asset_class) {
    this.asset_class = asset_class;
  }

  public ReceiveFullsimulationBody sender_agent(DevcustomertransactionsreceivefullsimulationSenderAgent sender_agent) {
    this.sender_agent = sender_agent;
    return this;
  }

   /**
   * Get sender_agent
   * @return sender_agent
  **/
  public DevcustomertransactionsreceivefullsimulationSenderAgent getSenderAgent() {
    return sender_agent;
  }

  public void setSenderAgent(DevcustomertransactionsreceivefullsimulationSenderAgent sender_agent) {
    this.sender_agent = sender_agent;
  }

  public ReceiveFullsimulationBody message_id(String message_id) {
    this.message_id = message_id;
    return this;
  }

   /**
   * Get message_id
   * @return message_id
  **/
  public String getMessageId() {
    return message_id;
  }

  public void setMessageId(String message_id) {
    this.message_id = message_id;
  }

  public ReceiveFullsimulationBody purpose_category(String purpose_category) {
    this.purpose_category = purpose_category;
    return this;
  }

   /**
   * Get purpose_category
   * @return purpose_category
  **/
  public String getPurposeCategory() {
    return purpose_category;
  }

  public void setPurposeCategory(String purpose_category) {
    this.purpose_category = purpose_category;
  }

  public ReceiveFullsimulationBody instructing_agent(DevcustomertransactionsreceivefullsimulationSenderAgent instructing_agent) {
    this.instructing_agent = instructing_agent;
    return this;
  }

   /**
   * Get instructing_agent
   * @return instructing_agent
  **/
  public DevcustomertransactionsreceivefullsimulationSenderAgent getInstructingAgent() {
    return instructing_agent;
  }

  public void setInstructingAgent(DevcustomertransactionsreceivefullsimulationSenderAgent instructing_agent) {
    this.instructing_agent = instructing_agent;
  }

  public ReceiveFullsimulationBody partner_product(PartnerProductEnum partner_product) {
    this.partner_product = partner_product;
    return this;
  }

   /**
   * Get partner_product
   * @return partner_product
  **/
  public PartnerProductEnum getPartnerProduct() {
    return partner_product;
  }

  public void setPartnerProduct(PartnerProductEnum partner_product) {
    this.partner_product = partner_product;
  }

  public ReceiveFullsimulationBody instructed_agent(DevcustomertransactionsreceivefullsimulationSenderAgent instructed_agent) {
    this.instructed_agent = instructed_agent;
    return this;
  }

   /**
   * Get instructed_agent
   * @return instructed_agent
  **/
  public DevcustomertransactionsreceivefullsimulationSenderAgent getInstructedAgent() {
    return instructed_agent;
  }

  public void setInstructedAgent(DevcustomertransactionsreceivefullsimulationSenderAgent instructed_agent) {
    this.instructed_agent = instructed_agent;
  }

  public ReceiveFullsimulationBody remittance_information_unstructured(String remittance_information_unstructured) {
    this.remittance_information_unstructured = remittance_information_unstructured;
    return this;
  }

   /**
   * Get remittance_information_unstructured
   * @return remittance_information_unstructured
  **/
  public String getRemittanceInformationUnstructured() {
    return remittance_information_unstructured;
  }

  public void setRemittanceInformationUnstructured(String remittance_information_unstructured) {
    this.remittance_information_unstructured = remittance_information_unstructured;
  }

  public ReceiveFullsimulationBody reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public ReceiveFullsimulationBody sender(DevcustomertransactionsreceivefullsimulationReceiver sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public DevcustomertransactionsreceivefullsimulationReceiver getSender() {
    return sender;
  }

  public void setSender(DevcustomertransactionsreceivefullsimulationReceiver sender) {
    this.sender = sender;
  }

  public ReceiveFullsimulationBody end_to_end_id(String end_to_end_id) {
    this.end_to_end_id = end_to_end_id;
    return this;
  }

   /**
   * Get end_to_end_id
   * @return end_to_end_id
  **/
  public String getEndToEndId() {
    return end_to_end_id;
  }

  public void setEndToEndId(String end_to_end_id) {
    this.end_to_end_id = end_to_end_id;
  }

  public ReceiveFullsimulationBody message_schema(String message_schema) {
    this.message_schema = message_schema;
    return this;
  }

   /**
   * Get message_schema
   * @return message_schema
  **/
  public String getMessageSchema() {
    return message_schema;
  }

  public void setMessageSchema(String message_schema) {
    this.message_schema = message_schema;
  }

  public ReceiveFullsimulationBody sender_account(DevcustomertransactionsreceivefullsimulationReceiverAccount sender_account) {
    this.sender_account = sender_account;
    return this;
  }

   /**
   * Get sender_account
   * @return sender_account
  **/
  public DevcustomertransactionsreceivefullsimulationReceiverAccount getSenderAccount() {
    return sender_account;
  }

  public void setSenderAccount(DevcustomertransactionsreceivefullsimulationReceiverAccount sender_account) {
    this.sender_account = sender_account;
  }

  public ReceiveFullsimulationBody asset_type(AssetTypeEnum asset_type) {
    this.asset_type = asset_type;
    return this;
  }

   /**
   * Get asset_type
   * @return asset_type
  **/
  public AssetTypeEnum getAssetType() {
    return asset_type;
  }

  public void setAssetType(AssetTypeEnum asset_type) {
    this.asset_type = asset_type;
  }

  public ReceiveFullsimulationBody receiver_agent(DevcustomertransactionsreceivefullsimulationSenderAgent receiver_agent) {
    this.receiver_agent = receiver_agent;
    return this;
  }

   /**
   * Get receiver_agent
   * @return receiver_agent
  **/
  public DevcustomertransactionsreceivefullsimulationSenderAgent getReceiverAgent() {
    return receiver_agent;
  }

  public void setReceiverAgent(DevcustomertransactionsreceivefullsimulationSenderAgent receiver_agent) {
    this.receiver_agent = receiver_agent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReceiveFullsimulationBody receive_fullsimulation_body = (ReceiveFullsimulationBody) o;
    return Objects.equals(this.transaction_id, receive_fullsimulation_body.transaction_id) &&
        Objects.equals(this.amount, receive_fullsimulation_body.amount) &&
        Objects.equals(this.settlement_date, receive_fullsimulation_body.settlement_date) &&
        Objects.equals(this.receiver, receive_fullsimulation_body.receiver) &&
        Objects.equals(this.receiver_account, receive_fullsimulation_body.receiver_account) &&
        Objects.equals(this.purpose, receive_fullsimulation_body.purpose) &&
        Objects.equals(this.asset_class, receive_fullsimulation_body.asset_class) &&
        Objects.equals(this.sender_agent, receive_fullsimulation_body.sender_agent) &&
        Objects.equals(this.message_id, receive_fullsimulation_body.message_id) &&
        Objects.equals(this.purpose_category, receive_fullsimulation_body.purpose_category) &&
        Objects.equals(this.instructing_agent, receive_fullsimulation_body.instructing_agent) &&
        Objects.equals(this.partner_product, receive_fullsimulation_body.partner_product) &&
        Objects.equals(this.instructed_agent, receive_fullsimulation_body.instructed_agent) &&
        Objects.equals(this.remittance_information_unstructured, receive_fullsimulation_body.remittance_information_unstructured) &&
        Objects.equals(this.reference, receive_fullsimulation_body.reference) &&
        Objects.equals(this.sender, receive_fullsimulation_body.sender) &&
        Objects.equals(this.end_to_end_id, receive_fullsimulation_body.end_to_end_id) &&
        Objects.equals(this.message_schema, receive_fullsimulation_body.message_schema) &&
        Objects.equals(this.sender_account, receive_fullsimulation_body.sender_account) &&
        Objects.equals(this.asset_type, receive_fullsimulation_body.asset_type) &&
        Objects.equals(this.receiver_agent, receive_fullsimulation_body.receiver_agent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transaction_id, amount, settlement_date, receiver, receiver_account, purpose, asset_class, sender_agent, message_id, purpose_category, instructing_agent, partner_product, instructed_agent, remittance_information_unstructured, reference, sender, end_to_end_id, message_schema, sender_account, asset_type, receiver_agent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiveFullsimulationBody {\n");
    
    sb.append("    transaction_id: ").append(toIndentedString(transaction_id)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    settlement_date: ").append(toIndentedString(settlement_date)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    receiver_account: ").append(toIndentedString(receiver_account)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    asset_class: ").append(toIndentedString(asset_class)).append("\n");
    sb.append("    sender_agent: ").append(toIndentedString(sender_agent)).append("\n");
    sb.append("    message_id: ").append(toIndentedString(message_id)).append("\n");
    sb.append("    purpose_category: ").append(toIndentedString(purpose_category)).append("\n");
    sb.append("    instructing_agent: ").append(toIndentedString(instructing_agent)).append("\n");
    sb.append("    partner_product: ").append(toIndentedString(partner_product)).append("\n");
    sb.append("    instructed_agent: ").append(toIndentedString(instructed_agent)).append("\n");
    sb.append("    remittance_information_unstructured: ").append(toIndentedString(remittance_information_unstructured)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    end_to_end_id: ").append(toIndentedString(end_to_end_id)).append("\n");
    sb.append("    message_schema: ").append(toIndentedString(message_schema)).append("\n");
    sb.append("    sender_account: ").append(toIndentedString(sender_account)).append("\n");
    sb.append("    asset_type: ").append(toIndentedString(asset_type)).append("\n");
    sb.append("    receiver_agent: ").append(toIndentedString(receiver_agent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
